Repository bbc/psammead, pull requests merged in 2018-12, with the labels that each got.

#80 Move test helpers to psammead
  package-lock.json
  package.json
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/README.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/index.js
Labels: alpha-2, high priority

#83 Add presentation pattern note to CONTRIBUTING
  CONTRIBUTING.md
Labels: alpha-2

#79 Migrate Headings components into component package
  package-lock.json
  package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/README.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-headings/src/index.jsx
  packages/components/psammead-headings/src/index.stories.jsx
  packages/components/psammead-headings/src/index.test.jsx
Labels: alpha-2, high priority

#89 Cleanup - Update packagelock files
  packages/utilities/gel-constants/package-lock.json
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-test-helpers/package-lock.json
Labels: alpha-2

#111 Update psammead-visually-hidden-text package lock
  packages/components/psammead-visually-hidden-text/package-lock.json
Labels: alpha-2

#113 Update repo and homepage urls for visually hidden text
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
Labels: alpha-2

#119 Bump headings for babel 7
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
Labels: alpha-2

#125 Bump VisuallyHiddenText package for Babel 7
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
Labels: bug

#114 Readme - update publishing details
  README.md
Labels: documentation

#121 Fix Babel/Storybook Setup
  .storybook/.babelrc
  babel.config.js
  package-lock.json
  package.json
Labels: alpha-2, bug, high priority

#126 Add tick box to prompt people to assign PR/issue
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#152 fixes #145, restructures README and adds test command
  README.md
Labels: mergeable

#151 Fix Psammead Storybook styles & fonts
  .storybook/config.js
  README.md
  package-lock.json
  package.json
Labels: mergeable

#134 Fix psammead-paragraph styling
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-paragraph/src/index.jsx
Labels: mergeable

#161 Update publish instructions
  README.md
Labels: alpha-2, documentation

#150 fixes #139 - describes global styles required for components
  README.md
Labels: documentation

#163 Add documentation for usage of babel-plugin-styled-components
  README.md
Labels: alpha-2, documentation

#164 Bump Psammead Paragraph
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
Labels: bug

#172 Add common sections to Visually Hidden Text README
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/README.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
Labels: documentation

#174 Clean up primary readme
  README.md
Labels: alpha-2, documentation

#106 Add InlineLink component
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/README.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-inline-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-inline-link/src/index.jsx
  packages/components/psammead-inline-link/src/index.stories.jsx
  packages/components/psammead-inline-link/src/index.test.jsx
Labels: alpha-2

#143 Add github pages publishing script
  .gitignore
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
Labels: alpha-2

#105 Adds Brand component to Psammead
  babel.config.js
  package-lock.json
  package.json
  packages/components/example-button/package-lock.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-brand/src/index.test.jsx
Labels: alpha-2, high priority

#173 Update PR welcome links in readme
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/README.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/README.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/README.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
  packages/utilities/gel-constants/CHANGELOG.md
  packages/utilities/gel-constants/README.md
  packages/utilities/gel-constants/package-lock.json
  packages/utilities/gel-constants/package.json
  packages/utilities/gel-foundations-styled-components/CHANGELOG.md
  packages/utilities/gel-foundations-styled-components/README.md
  packages/utilities/gel-foundations-styled-components/package-lock.json
  packages/utilities/gel-foundations-styled-components/package.json
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/README.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/README.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/README.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
Labels: alpha-2

#176 Do not collect coverage from dist
  package.json
Labels: alpha-2, bug, should

#129 Add Copyright component
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/README.md
  packages/components/psammead-copyright/__snapshots__/index.test.jsx.snap
  packages/components/psammead-copyright/index.jsx
  packages/components/psammead-copyright/index.stories.jsx
  packages/components/psammead-copyright/index.test.jsx
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
Labels: mergeable

#187 Update Copyright badge & directory structure
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/README.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-copyright/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-copyright/src/index.jsx
  packages/components/psammead-copyright/src/index.stories.jsx
  packages/components/psammead-copyright/src/index.test.jsx
Labels: high priority

#186 Caption component
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/README.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-caption/src/index.stories.jsx
  packages/components/psammead-caption/src/index.test.jsx
Labels: alpha-2

#188 Simplify jenkinsfile
  Jenkinsfile
  Makefile
  package.json
Labels: high priority

#197 Revert "Add ignore pattern for jest tests, to avoid running tests against dist/"
  package.json
Labels: high priority

#202 Brand: import GEL_GROUP_3_SCREEN_WIDTH_MAX correctly
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
Labels: alpha-2, bug, must

#194 Add storybook to jenkinsfile
  Jenkinsfile
  Makefile
Labels: alpha-2, high priority, must

#196 Verify NPM and Node versions
  package.json
  scripts/enforceVersions.sh
Labels: alpha-2, should

#180 Add script to publish packages
  README.md
  package-lock.json
  package.json
  scripts/publish/index.js
  scripts/publish/src/getPackages.js
  scripts/publish/src/getRegistryVersion.js
  scripts/publish/src/publish.js
  scripts/publish/src/publishConfig.js
  scripts/publish/src/report.js
  scripts/publish/src/shouldPublish.js
  scripts/publish/src/slackNotification.js
  scripts/publish/test/getPackages.test.js
  scripts/publish/test/getRegistryVersion.test.js
  scripts/publish/test/publish.test.js
  scripts/publish/test/publishConfig.test.js
  scripts/publish/test/report.test.js
  scripts/publish/test/shouldPublish.test.js
  scripts/publish/test/slackNotification.test.js
Labels: alpha-2, high priority

#206 Add utilities README
  packages/utilities/README.md
Labels: documentation

#208 Add NPM Publishing to CI
  Jenkinsfile
  Makefile
Labels: alpha-2, high priority, must

#207 Add Readme to all storybook stories
  .storybook/addons.js
  .storybook/config.js
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-caption/src/index.stories.jsx
  packages/components/psammead-copyright/src/index.stories.jsx
  packages/components/psammead-headings/src/index.stories.jsx
  packages/components/psammead-inline-link/src/index.stories.jsx
  packages/components/psammead-paragraph/src/index.stories.jsx
  packages/components/psammead-sitewide-links/src/index.stories.jsx
  packages/components/psammead-visually-hidden-text/src/index.stories.jsx
Labels: alpha-2, mergeable

#185 Jenkins - notify Slack
  Jenkinsfile
Labels: alpha-2, high priority, mergeable, must

#210 adds assistive technology section to README
  README.md
Labels: documentation

#213 Add image placeholder to Psammead
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/README.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image-placeholder/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-image-placeholder/src/index.jsx
  packages/components/psammead-image-placeholder/src/index.stories.jsx
  packages/components/psammead-image-placeholder/src/index.test.jsx
Labels: alpha-2, mergeable, should

#223 Add name description to readme
  README.md
Labels: alpha-2, could, mergeable

#221 Create gel-foundations component and delete gel-constants and gel-foundations-styled-components
  packages/utilities/gel-constants/CHANGELOG.md
  packages/utilities/gel-constants/README.md
  packages/utilities/gel-constants/package-lock.json
  packages/utilities/gel-foundations-styled-components/CHANGELOG.md
  packages/utilities/gel-foundations-styled-components/package-lock.json
  packages/utilities/gel-foundations-styled-components/package.json
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/README.md
  packages/utilities/gel-foundations/breakpoints.js
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/spacings.js
  packages/utilities/gel-foundations/src/breakpoints.js
  packages/utilities/gel-foundations/src/spacings.js
  packages/utilities/gel-foundations/src/typography.js
  packages/utilities/gel-foundations/typography.js
  packages/utilities/gel-foundations/typography_sizes_web.md
Labels: alpha-2, mergeable, should

#179 Add Code Climate badges to main README
  Jenkinsfile
  Makefile
  README.md
Labels: mergeable

#212 Update utility package READMEs
  packages/components/psammead-image-placeholder/package-lock.json
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/README.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/README.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/README.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/README.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
Labels: alpha-2

#228 Ensure packages are https
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
Labels: bug, mergeable

#225 Migrate Image component from Simorgh
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/README.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-image/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-image/src/index.jsx
  packages/components/psammead-image/src/index.stories.jsx
  packages/components/psammead-image/src/index.test.jsx
Labels: alpha-2, high priority, mergeable

#227 Use @bbc/gel-foundations in Psammead
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-copyright/src/index.jsx
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/index.jsx
  packages/components/psammead-inline-link/README.md
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/README.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/index.jsx
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/Link/index.jsx
  packages/components/psammead-sitewide-links/src/List/index.jsx
  packages/components/psammead-sitewide-links/src/index.jsx
  packages/utilities/README.md
  packages/utilities/gel-foundations/README.md
Labels: alpha-2, mergeable, should

#230 Add README decorator to Image & ImagePlaceholder stories
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image-placeholder/src/index.stories.jsx
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-image/src/index.stories.jsx
Labels: mergeable

#220 Re-home Simorgh Figure in Psammead
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/README.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-figure/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-figure/src/index.jsx
  packages/components/psammead-figure/src/index.stories.jsx
  packages/components/psammead-figure/src/index.test.jsx
Labels: alpha-2, should

#231 Add Storybook badges to package READMEs
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/README.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/README.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/README.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/README.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/README.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/README.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/README.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/README.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/README.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
Labels: high priority

#244 Accessiblity Swarm info in Contributing.md
  CONTRIBUTING.md
Labels: documentation
