Repository bbc/psammead, pull requests merged in 2019-02, with the labels that each got.

#291 Update appearance of psammead-paragraph
  package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-paragraph/src/index.jsx
Labels: v1.0

#290 Move typography to use rem instead of em for font size
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/typography.js
Labels: must, v1.0

#305 Update Headline & Subheading colour to Shadow
  .storybook/config.js
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-headings/src/index.jsx
Labels: mergeable

#314 Remove example button
  README.md
  package-lock.json
  package.json
  packages/components/example-button/CHANGELOG.md
  packages/components/example-button/README.MD
  packages/components/example-button/package-lock.json
  packages/components/example-button/package.json
  packages/components/example-button/src/README.md
  packages/components/example-button/src/index.jsx
  packages/components/example-button/src/index.stories.jsx
  packages/components/example-button/src/index.test.jsx
  packages/components/example-button/src/styles/styledExampleButton.js
Labels: high priority, mergeable

#304 Add fontface definitions to Psammead
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/README.md
  packages/utilities/gel-foundations/index.test.jsx
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/typography.js
  packages/utilities/gel-foundations/typography_sizes_web.md
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/README.md
  packages/utilities/psammead-styles/font-faces.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/fonts.js
Labels: mergeable
