Repository bbc/psammead, pull requests merged in 2019-09, with the labels that each got.

#1942 Talos - Bump react, react-test-renderer, react-dom...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-amp-geo/CHANGELOG.md
  packages/components/psammead-amp-geo/package-lock.json
  packages/components/psammead-amp-geo/package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
Labels: simorgh-core-stream

#1927 Talos README.md
  scripts/talos/README.md
Labels: Heracles, documentation, high priority, simorgh-core-stream, talos

#325 Create yeoman template
  .yeoman/README.md
  .yeoman/index.js
  .yeoman/index.test.js
  .yeoman/src/fs-actions/index.js
  .yeoman/src/fs-actions/index.test.js
  .yeoman/src/get-existing/index.js
  .yeoman/src/get-existing/index.test.js
  .yeoman/src/questions/index.js
  .yeoman/src/questions/index.test.js
  .yeoman/templates/CHANGELOG.md
  .yeoman/templates/README.md
  .yeoman/templates/package.json
  .yeoman/templates/src/index.jsx
  .yeoman/templates/src/index.stories.jsx
  .yeoman/templates/src/index.test.jsx
  README.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#1961 Talos - Bump @bbc/psammead-locales, @bbc/psammead-assets, @bbc/psammead-brand...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#1960 update eslint-config-airbnb to 18.0.1
  .eslintrc.js
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-inline-link/src/index.stories.jsx
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Amp/index.jsx
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/index.stories.jsx
  packages/components/psammead-story-promo-list/src/index.test.jsx
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/IndexAlsos/index.jsx
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
  packages/utilities/moment-timezone-include/CHANGELOG.md
  packages/utilities/moment-timezone-include/package-lock.json
  packages/utilities/moment-timezone-include/package.json
  packages/utilities/moment-timezone-include/src/replaceOriginalTimezoneData/index.js
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/input-provider.jsx
Labels: simorgh-core-stream

#1968 Talos - Bump @bbc/psammead-brand, @bbc/psammead-inline-link, @bbc/psammead-media-player...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#1966 Change scanner
  CHANGELOG.md
  Jenkinsfile
  package-lock.json
  package.json
  scripts/changeScanner/getChanges.js
  scripts/changeScanner/getChanges.test.js
  scripts/changeScanner/index.js
  scripts/changeScanner/index.test.js
Labels: simorgh-core-stream

#1948 Create storybook stories to show different font types
  package.json
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/index.stories.jsx
Labels: shared-components

#1958 update psammead-test-helper
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/index.js
Labels: simorgh-core-stream

#1974 Fix change scanner scope
  .yeoman/index.test.js
  scripts/changeScanner/getChanges.js
  scripts/changeScanner/getChanges.test.js
Labels: simorgh-core-stream

#1940 Updated npm scripts
  CHANGELOG.md
  Makefile
  README.md
  package-lock.json
  package.json
  packages/components/README.md
  scripts/forcePackageLockHttps.sh
Labels: Iolaus, documentation, simorgh-core-stream

#1844 Adding Pashto and Persian locales to psammead locales
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/fa.js
  packages/utilities/psammead-locales/moment/fa.test.js
  packages/utilities/psammead-locales/moment/helpers/jalaali.js
  packages/utilities/psammead-locales/moment/helpers/jalaali.test.js
  packages/utilities/psammead-locales/moment/helpers/stringHelper.js
  packages/utilities/psammead-locales/moment/helpers/stringHelper.test.js
  packages/utilities/psammead-locales/moment/ps.js
  packages/utilities/psammead-locales/moment/ps.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-current-epic, articles-features-stream, high priority

#1989 Make talos findable again
  Jenkinsfile
  Makefile
Labels: high priority, simorgh-core-stream

#1993 Talos - Bump @bbc/psammead-amp-geo, @bbc/psammead-brand, @bbc/psammead-caption...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/src/index.test.jsx
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#1992 Update the psammead-locale package
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-current-epic, articles-features-stream

#1996 Make test less flakey
  .yeoman/index.test.js
Labels: simorgh-core-stream

#1997 Talos - Bump @bbc/psammead-brand, @bbc/psammead-caption, @bbc/psammead-consent-banner...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: simorgh-core-stream

#2003 Update psammead-locale package to remove "side-effect"
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-current-epic, articles-features-stream

#1998 Add note about role text to accessibility notes for image source
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/README.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
Labels: a11y, ws-frontpage-stream

#1994 Add comment to test helper logic
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/index.js
Labels: simorgh-core-stream

#2011 Refactor input provider
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/decorators.js
  packages/utilities/psammead-storybook-helpers/src/index.stories.jsx
  packages/utilities/psammead-storybook-helpers/src/index.test.jsx
  packages/utilities/psammead-storybook-helpers/src/input-provider.jsx
Labels: simorgh-core-stream

#2010 Talos - Bump @bbc/psammead-copyright
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2012 Talos - Bump @bbc/psammead-test-helpers
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2014 Add padding-top to top story on desktop and tablet
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo-list/src/index.jsx
Labels: bug, high priority, ws-frontpage-stream

#2013 psammead-locale bug fix for IE11
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/ig.js
  packages/utilities/psammead-locales/moment/pcm.js
  packages/utilities/psammead-locales/moment/ps.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-current-epic, articles-features-stream

#1987 Fix StoryPromo font size on IE11
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: bug, high priority, ws-frontpage-stream

#2016 Avoid more trailing commas in function calls for IE11
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/.prettierrc
  packages/utilities/psammead-locales/moment/fa.js
  packages/utilities/psammead-locales/moment/helpers/jalaali.js
  packages/utilities/psammead-locales/moment/helpers/jalaali.test.js
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/ps.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-current-epic, articles-features-stream

#2018 Talos - Bump @bbc/psammead-locales
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-current-epic, articles-features-stream

#2000 Add Persian and Pashto locales to Storybook
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-current-epic, articles-features-stream

#1926 use new input provider in storybook
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/index.stories.jsx
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/index.stories.jsx
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-figure/src/index.stories.jsx
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/index.stories.jsx
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-inline-link/src/index.stories.jsx
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/index.stories.jsx
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/index.stories.jsx
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/index.stories.jsx
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/index.stories.jsx
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
  packages/components/psammead-visually-hidden-text/src/index.stories.jsx
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/index.stories.jsx
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/typography.stories.jsx
Labels: simorgh-core-stream

#2017 Talos - Bump @bbc/psammead-story-promo
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
Labels: ws-frontpage-stream

#2001 Remove Punjabi numerals in Moment
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/pa-in.js
  packages/utilities/psammead-locales/moment/pa-in.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: high priority, ws-frontpage-stream

#2020 IE11 ES6 fixes
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/ar.js
  packages/utilities/psammead-locales/moment/fa.js
  packages/utilities/psammead-locales/moment/ps.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-current-epic, articles-features-stream

#2044 Persian client bundle timestamp format fix
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/fa.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-current-epic, articles-features-stream

#2048 Fix Punjabi numerals
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/pa-in.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: bug, high priority, ws-frontpage-stream

#2049 More talos logging
  scripts/utilities/runExec/index.js
Labels: simorgh-core-stream

#2042 Update input provider readme
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
Labels: simorgh-core-stream

#2057 Talos - Wait for all promises before continuing
  scripts/talos/index.js
Labels: simorgh-core-stream

#1949 Fix alpha version bumping
  CHANGELOG.md
  scripts/bumpPackages/index.js
  scripts/bumpPackages/index.test.js
Labels: simorgh-core-stream, ws-frontpage-stream

#2081 Talos - Bump @bbc/psammead-amp-geo, @bbc/psammead-brand, @bbc/psammead-caption...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
Labels: high priority, simorgh-core-stream

#2082 Talos - Bump @bbc/psammead-brand, @bbc/psammead-caption, @bbc/psammead-consent-banner...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: simorgh-core-stream

#2040 Fix summary visibility for breakpoints below 1008px
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: high priority, ws-frontpage-stream

#2084 Talos - Bump @bbc/psammead-story-promo
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-frontpage-stream

#2083 Talos - Bump babel-eslint, lint-staged, eslint-config-prettier...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2087 Bumped jalaali-js
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: simorgh-core-stream

#2088 Remove template literals from Jalaali helper for IE11 compat
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/helpers/jalaali.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-current-epic, articles-features-stream

#2089 Upgrade Node to 10.16.3
  .nvmrc
  CHANGELOG.md
  Jenkinsfile
Labels: infra-tooling-stream

#2086 Dep bot config
  .dependabot/config.yml
Labels: simorgh-core-stream

#2090 Talos - Bump @bbc/psammead-locales
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-current-epic, articles-features-stream

#2093 Update yeoman tests
  .yeoman/index.test.js
Labels: simorgh-core-stream

#2092 Refactored navigation component
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/index.stories.jsx
Labels: simorgh-core-stream

#1933 Changes to Timestamp Container stories, Moment locales stories
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/index.stories.jsx
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: Heracles, simorgh-core-stream

#2094 Correct translation for 'ago' in Punjabi timestamps
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/pa-in.js
  packages/utilities/psammead-locales/moment/pa-in.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: bug, high priority, ws-frontpage-stream

#2104 add function to detect and render helmet for use in snapshots
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/__snapshots__/index.test.jsx.snap
  packages/utilities/psammead-test-helpers/index.test.jsx
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/index.js
  packages/utilities/psammead-test-helpers/src/renderWithHelmet.js
Labels: shared-components, ws-media-stream

#2110 Override moment numerals - Hindi
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/hi.js
  packages/utilities/psammead-locales/moment/hi.test.js
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-frontpage-stream

#2118 Override numerals in moment - Marathi
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/mr.js
  packages/utilities/psammead-locales/moment/mr.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-frontpage-stream

#2120 Add Scottish colour and scotland service to fonts
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/colours.js
  packages/utilities/psammead-styles/src/font-families.js
Labels: articles-features-stream, articles-next-epic, low-priority

#2127 Brand - new backgroundColour & logoColour props
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-brand/src/index.test.jsx
Labels: articles-features-stream, shared-components

#2145 Talos - Bump @bbc/psammead-styles
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
Labels: shared-components

#2124 Override numerals in moment - Tamil
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/ta.js
  packages/utilities/psammead-locales/moment/ta.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-frontpage-stream

#2117 Optimise Navigation direction prop
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
  packages/components/psammead-navigation/testHelpers/arabic.js
Labels: ws-frontpage-stream

#2139 Use global styles in storybook
  .storybook/config.js
Labels: shared-components

#2147 Talos - Bump @bbc/psammead-brand, @bbc/psammead-caption, @bbc/psammead-consent-banner...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/index.stories.jsx
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: articles-features-stream, shared-components, ws-frontpage-stream, ws-media-stream

#2114 Override moment formats
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/pt-br.js
  packages/utilities/psammead-locales/moment/pt-br.test.js
  packages/utilities/psammead-locales/moment/ru.js
  packages/utilities/psammead-locales/moment/ru.test.js
  packages/utilities/psammead-locales/moment/sr-cyrl.js
  packages/utilities/psammead-locales/moment/sr-cyrl.test.js
  packages/utilities/psammead-locales/moment/sr.js
  packages/utilities/psammead-locales/moment/sr.test.js
  packages/utilities/psammead-locales/moment/uk.js
  packages/utilities/psammead-locales/moment/uk.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
Labels: ws-frontpage-stream

#2144 Add Skin Prop to Media Player
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
  packages/components/psammead-media-player/src/index.stories.jsx
  packages/components/psammead-media-player/src/index.test.jsx
Labels: ws-media- LiveRadioV1, ws-media-stream

#2125 Refactor async/await to promise
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/index.js
Labels: simorgh-core-stream

#2149 Override numerals in moment - Gujarati
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/gu.js
  packages/utilities/psammead-locales/moment/gu.test.js
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-frontpage-stream

#2141 Override numerals in moment - Nepali
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/ne.js
  packages/utilities/psammead-locales/moment/ne.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-frontpage-stream

#2119 Add missing visually hidden text on StoryPromo
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/index.stories.jsx
Labels: bug, ws-frontpage-stream

#2162 Talos - Bump @bbc/psammead-locales @bbc/psammead-storybook-helper @bbc/psammead-story-promo
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2166 remove async keyword from test helpers
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/renderWithHelmet.js
Labels: shared-components, ws-media-stream

#2169 Add exports for scripts
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/index.test.jsx
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/scripts.js
Labels: shared-components, ws-frontpage-stream

#2138 Talos - Bump eslint-config-prettier, @storybook/addon-viewport, @storybook/theming...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2170 Add ignores for codeclimate warnings in test files
  .codeclimate.yml
Labels: simorgh-core-stream

#2115 Move Media Icons from psammead-media-indicator into psammead-assets
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/README.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs.jsx
  packages/utilities/psammead-assets/src/svgs.stories.jsx
  packages/utilities/psammead-assets/src/svgs.test.jsx
  packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
Labels: shared-components, ws-frontpage-stream, ws-media-stream

#2177 Minor docs fixes
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  documentation/accessibility-testing-on-device.md
  documentation/architecture-decision-records/ADR0003-definition_of_done.md
  packages/components/README.md
Labels: simorgh-core-stream

#2163 bump 3rd party dependencies
  CHANGELOG.md
  package-lock.json
  package.json
  packages/README.md
Labels: simorgh-core-stream

#2095 feat: cover base level packages #1967
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/changeScanner/getChanges.js
  scripts/changeScanner/getChanges.test.js
Labels: simorgh-core-stream

#2168 Rewrite a lot of the repo's documentation
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Code-Standards-and-Ways-of-Working.md
  README.md
  documentation/Chromaticqa-Guide.md
  documentation/Spacing-Units.md
  documentation/accessibility-testing-on-device.md
  documentation/architecture-decision-records/ADR0001-i18n_library.md
  documentation/architecture-decision-records/ADR0002-type_groups.md
  documentation/architecture-decision-records/ADR0003-definition_of_done.md
  packages/README.md
  packages/components/README.md
  packages/utilities/README.md
  scripts/talos/README.md
Labels: simorgh-core-stream

#2183 Fix typo in link
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Code-Standards-and-Ways-of-Working.md
  README.md
  packages/README.md
  scripts/talos/README.md
Labels: simorgh-core-stream

#2165 Override default moment relative time - Tamil, Kyrgyz, Marathi
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/ky.js
  packages/utilities/psammead-locales/moment/ky.test.js
  packages/utilities/psammead-locales/moment/mr.js
  packages/utilities/psammead-locales/moment/mr.test.js
  packages/utilities/psammead-locales/moment/ta.js
  packages/utilities/psammead-locales/moment/ta.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: high priority, ws-frontpage-stream

#2192 BBC Scotland SVG
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/README.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/__snapshots__/svgs.test.jsx.snap
  packages/utilities/psammead-assets/src/svgs.jsx
  packages/utilities/psammead-assets/src/svgs/scotland.jsx
Labels: articles-features-stream, shared-components

#2191 Talos - Bump @bbc/psammead-amp-geo, @bbc/psammead-brand, @bbc/psammead-caption...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Amp/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
Labels: simorgh-core-stream

#2194 Talos - Bump @bbc/psammead-assets
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
Labels: shared-components

#2181 Simplifies stories
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/index.stories.jsx
Labels: articles-features-stream, discussion, shared-components

#2196 Create locales for Hausa and Somali
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/ha.js
  packages/utilities/psammead-locales/moment/ha.test.js
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/so.js
  packages/utilities/psammead-locales/moment/so.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-frontpage-stream

#2187 Create locales for Afaan Oromoo and Amharic
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/am.js
  packages/utilities/psammead-locales/moment/am.test.js
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/om.js
  packages/utilities/psammead-locales/moment/om.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-frontpage-stream

#2193 Create locales for Gahuza and Tigrinya
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/rw.js
  packages/utilities/psammead-locales/moment/rw.test.js
  packages/utilities/psammead-locales/moment/ti.js
  packages/utilities/psammead-locales/moment/ti.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-frontpage-stream

#2178 Update 'ps' (Pashto) locale
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/ps.js
  packages/utilities/psammead-locales/moment/ps.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-current-epic, articles-features-stream

#2199 Pull in media icons from psammead-assets
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-indicator/src/mediaIcons.jsx
Labels: shared-components, ws-frontpage-stream

#2184 Override moment relative timestamp translations - Yoruba, Uzbek
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/uz.js
  packages/utilities/psammead-locales/moment/uz.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-frontpage-stream

#2189 Add stories in storybook for media icons in psammead-assets
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs.stories.jsx
Labels: shared-components, ws-frontpage-stream

#2210 Override moment relative timestamp translations for Nepali and Serbian services.
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/ne.js
  packages/utilities/psammead-locales/moment/ne.test.js
  packages/utilities/psammead-locales/moment/sr-cyrl.js
  packages/utilities/psammead-locales/moment/sr-cyrl.test.js
  packages/utilities/psammead-locales/moment/sr.js
  packages/utilities/psammead-locales/moment/sr.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-frontpage-stream

#2186 Override moment relative timestamp translations - Sinhala, Thai, Ukrainian
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/si.js
  packages/utilities/psammead-locales/moment/si.test.js
  packages/utilities/psammead-locales/moment/th.js
  packages/utilities/psammead-locales/moment/th.test.js
  packages/utilities/psammead-locales/moment/uk.js
  packages/utilities/psammead-locales/moment/uk.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-frontpage-stream

#2230 Talos - Bump @bbc/psammead-assets, @bbc/psammead-locales, @bbc/psammead-storybook-helpers
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#2231 Amend 'ps' (Pashto) locale
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/ps.js
  packages/utilities/psammead-locales/moment/ps.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-current-epic, articles-features-stream

#2232 Override azeri moment locale
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/az.js
  packages/utilities/psammead-locales/moment/az.test.js
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: blocking, high priority, ws-frontpage-stream

#2238 Bump dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream

#2227 Update moment month translations
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/bn.js
  packages/utilities/psammead-locales/moment/bn.test.js
  packages/utilities/psammead-locales/moment/gu.js
  packages/utilities/psammead-locales/moment/gu.test.js
  packages/utilities/psammead-locales/moment/hi.js
  packages/utilities/psammead-locales/moment/hi.test.js
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/sw.js
  packages/utilities/psammead-locales/moment/sw.test.js
  packages/utilities/psammead-locales/moment/ur.js
  packages/utilities/psammead-locales/moment/ur.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-fp-phase2, ws-frontpage-stream

#2237 Talos - Bump @bbc/psammead-locales
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-current-epic, articles-features-stream, ws-frontpage-stream

#2243 Talos - Bump @bbc/psammead-locales
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream

#2247 update article embed URL for MediaPlayer stories
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/index.stories.jsx
Labels: articles-av-epic, articles-features-stream, bug

#2250 Update Mundo, Brasil and Turkish fonts
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/font-families.js
Labels: articles-features-stream, articles-next-13

#2251 Talos - Bump @bbc/psammead-styles
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
Labels: articles-features-stream, articles-next-13, infra-tooling-stream, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2252 Talos - Bump @bbc/psammead-brand, @bbc/psammead-caption, @bbc/psammead-consent-banner...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream

#2240 Moment locale deprecation warning
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/index.jsx
  packages/containers/psammead-timestamp-container/src/index.stories.jsx
  packages/containers/psammead-timestamp-container/src/timestampUtilities.js
  packages/containers/psammead-timestamp-container/src/timestampUtilities.test.js
Labels: simorgh-core-stream, ws-frontpage-stream

#2229 Convert fonts to overridable functions
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/fonts.test.js.snap
  packages/utilities/psammead-styles/src/fonts.js
  packages/utilities/psammead-styles/src/fonts.test.js
  packages/utilities/psammead-styles/src/index.stories.jsx
Labels: simorgh-core-stream

#2274 Update the description of the repo
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: simorgh-core-stream
