Repository bbc/psammead, pull requests merged in 2019-12, with the labels that each got.

#2698 Add test for list styling to psammead-bulleted-lists
  packages/components/psammead-bulleted-list/CHANGELOG.md
  packages/components/psammead-bulleted-list/package-lock.json
  packages/components/psammead-bulleted-list/package.json
  packages/components/psammead-bulleted-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulleted-list/src/index.jsx
  packages/components/psammead-bulleted-list/src/index.test.jsx
Labels: ws-media-asset-page-v2, ws-media-stream

#2719 Add section label with role and aria-labelledby
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Title/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Title/index.jsx
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
Labels: most-read, shared-components

#2744 Add transparent border around the PlayCTA
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/index.jsx
Labels: ws-frontpage-stream

#2745 Add `dir` prop to Amp and Canonical MenuButton.
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
Labels: ws-frontpage-stream

#2747 Fix MenuButton not acting as block element.
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
Labels: ws-frontpage-stream

#2748 Update Dev Dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2720 Update inline link story
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-inline-link/src/index.stories.jsx
Labels: shared-components

#2755 Bulletin - add padding right above 600px
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/index.jsx
Labels: bug, high priority, ws-frontpage-stream

#2753 Add article paths to storybook helper
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
Labels: shared-components

#2750 Add pseudo element to ScriptLink.
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-script-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-script-link/src/index.jsx
Labels: ws-frontpage-stream

#2760 Bulletin fix padding
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/index.jsx
Labels: high priority, ws-frontpage-stream

#2761 Bulletin: rename type to mediaType
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/index.jsx
  packages/components/psammead-bulletin/src/index.stories.jsx
  packages/components/psammead-bulletin/src/index.test.jsx
Labels: high priority, ws-frontpage-stream

#2764 Bulletin - Use mediaType
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/index.jsx
Labels: ws-fp-phase3, ws-frontpage-stream

#2746 Add a11y role to list and spacing to list item
  packages/components/psammead-bulleted-list/CHANGELOG.md
  packages/components/psammead-bulleted-list/README.md
  packages/components/psammead-bulleted-list/package-lock.json
  packages/components/psammead-bulleted-list/package.json
  packages/components/psammead-bulleted-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulleted-list/src/index.jsx
  packages/components/psammead-bulleted-list/src/index.stories.jsx
  packages/components/psammead-bulleted-list/src/index.test.jsx
Labels: ws-media-stream

#2756 Remove alpha tag from Bulletin
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/README.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/index.stories.jsx
Labels: ws-fp-phase3, ws-frontpage-stream

#2759 Change menu button height depending on script in use
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
  packages/components/psammead-navigation/src/DropdownNavigation/index.test.jsx
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
Labels: ws-frontpage-stream

#2773 Resolve media-player warnings on unit tests
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Guidance/index.test.jsx
  packages/components/psammead-media-player/src/Placeholder/index.test.jsx
  packages/components/psammead-media-player/src/index.test.jsx
Labels: ws-frontpage-stream, ws-media-stream

#2765 Add article paths to serviceKnobs
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/index.js
  packages/utilities/psammead-storybook-helpers/src/index.test.jsx
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.jsx
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.test.jsx
Labels: shared-components

#2775 Talos - Bump @bbc/psammead-storybook-helpers
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2769 Add prop `isOpen` to Navigation
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.test.jsx
Labels: ws-frontpage-stream

#2771 Use a react button to spread styled-component props
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
Labels: ws-frontpage-stream

#2778 Fix nav menu border in High Contrast
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
Labels: ws-frontpage-stream

#2763 Use article paths from storybook-helpers
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Item/index.test.jsx
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/List/index.test.jsx
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/index.stories.jsx
  packages/components/psammead-most-read/src/index.test.jsx
  packages/components/psammead-most-read/src/testHelpers/fixtureData.js
  packages/components/psammead-most-read/src/testHelpers/itemsHelper.js
Labels: shared-components

#2749 Use nepali numerals
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/ne.js
  packages/utilities/psammead-locales/moment/ne.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-features-stream, articles-rollout, shared-components, ws-frontpage-stream

#2782 Talos - Bump @bbc/psammead-locales
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-calendars/CHANGELOG.md
  packages/utilities/psammead-calendars/package-lock.json
  packages/utilities/psammead-calendars/package.json
Labels: articles-features-stream

#2779 Merge amp handlers correctly
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
  packages/components/psammead-navigation/src/DropdownNavigation/index.test.jsx
  packages/components/psammead-navigation/src/ScrollableNavigation/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
Labels: ws-frontpage-stream

#2785 Add `id`, `ampOpenClass` props to Navigation
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.test.jsx
Labels: ws-frontpage-stream

#2798 Convert psammead-bulleted-list bullet svg completely to base64
  packages/components/psammead-bulleted-list/CHANGELOG.md
  packages/components/psammead-bulleted-list/package-lock.json
  packages/components/psammead-bulleted-list/package.json
  packages/components/psammead-bulleted-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulleted-list/src/index.jsx
Labels: ws-media-stream

#2787 Update useMediaQuery hook to ensure server/client markup is consistent
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/hooks/useMediaQuery.js
  packages/components/psammead-navigation/src/index.jsx
Labels: ws-frontpage-stream

#2799 Refactor navigation props
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
  packages/components/psammead-navigation/src/DropdownNavigation/index.test.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
Labels: ws-frontpage-stream

#2797 Use grid from psammead-grid
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/List/index.jsx
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
Labels: shared-components

#2786 Add a onClick handler prop for the ScriptLink
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/README.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-script-link/src/index.jsx
  packages/components/psammead-script-link/src/index.test.jsx
Labels: ws-frontpage-stream

#2796 Fix padding and margin on outer grid
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-grid/src/index.jsx
Labels: grid, shared-components, ws-frontpage-stream

#2801 Move media query hooks to Simorgh
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/ScrollableNavigation/index.jsx
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/hooks/useMediaQuery.js
  packages/components/psammead-navigation/src/hooks/useMediaQuery.test.js
  packages/components/psammead-navigation/src/index.stories.jsx
  packages/components/psammead-navigation/src/index.test.jsx
Labels: ws-frontpage-stream

#2804 Talos - Bump @bbc/gel-foundations, @bbc/psammead-amp-geo, @bbc/psammead-assets...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2808 Dependency Updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2809 Remove alpha tag from bulleted-list
  packages/components/psammead-bulleted-list/CHANGELOG.md
  packages/components/psammead-bulleted-list/README.md
  packages/components/psammead-bulleted-list/package-lock.json
  packages/components/psammead-bulleted-list/package.json
Labels: ws-media-stream

#2806 Fix cursor on placeholder for no-js
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Placeholder/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
Labels: articles-av-epic, articles-features-stream

#2810 Ensure Nav is always red on desktop
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
Labels: ws-frontpage-stream

#2802 Spread Navigation props
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/ScrollableNavigation/index.jsx
  packages/components/psammead-navigation/src/index.jsx
Labels: ws-frontpage-stream

#2815 Remove display:inline on outer grids
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/README.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-grid/src/index.jsx
Labels: grid, shared-components

#2816 Update npm version
  .npmrc
  Jenkinsfile
Labels: infra-tooling-stream

#2826 Add AMP_ADS_JS boilerplate
  CHANGELOG.md
  package-lock.json
  package.json
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/__snapshots__/amp-boilerplate.test.jsx.snap
  packages/utilities/psammead-assets/src/amp-boilerplate.jsx
  packages/utilities/psammead-assets/src/amp-boilerplate.test.jsx
Labels: simorgh-core-stream

#2827 Talos - Bump @bbc/psammead-assets
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-embed-error/CHANGELOG.md
  packages/components/psammead-embed-error/package-lock.json
  packages/components/psammead-embed-error/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2830 Talos - Bump @bbc/psammead-bulletin, @bbc/psammead-embed-error, @bbc/psammead-image-placeholder...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2831 Dependency updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2828 Add guide on things to do when creating new component
  CHANGELOG.md
  Creating-a-new-component.md
  README.md
  package-lock.json
  package.json
  packages/README.md
Labels: articles-features-stream, shared-components, ws-frontpage-stream, ws-media-stream

#2834 remove code owner restriction from /packages dir
  .github/CODEOWNERS
Labels: infra-tooling-stream

#2829 Navigation - remove references to Skip to content link
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/index.stories.jsx
  packages/components/psammead-navigation/src/index.test.jsx
Labels: ws-frontpage-stream

#2835 Update code owners
  .github/CODEOWNERS
Labels: infra-tooling-stream, simorgh-core-stream

#2833 Fix script link read&write on IE
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-script-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-script-link/src/index.jsx
Labels: ws-frontpage-stream

#2843 Bumping dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Heracles, simorgh-core-stream

#2846 Remove package jest-fetch-mock
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Heracles, simorgh-core-stream

#2855 Export Nepali numerals
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
  packages/utilities/psammead-locales/src/numerals/__snapshots__/index.test.js.snap
  packages/utilities/psammead-locales/src/numerals/index.js
Labels: shared-components, ws-frontpage-stream

#2717 Update MostReadList with UX changes and various fixes
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Item/index.jsx
  packages/components/psammead-most-read/src/Item/index.test.jsx
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/List/index.jsx
  packages/components/psammead-most-read/src/List/index.test.jsx
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/index.jsx
  packages/components/psammead-most-read/src/index.stories.jsx
  packages/components/psammead-most-read/src/index.test.jsx
  packages/components/psammead-most-read/src/testHelpers/itemsHelper.js
Labels: most-read, shared-components

#2853 Remove alpha tag for Script Link component
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/README.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
Labels: ws-frontpage-stream
