Repository bbc/psammead, pull requests merged in 2019-01, with the labels that each got.

#250 Documentation / script process for adding custom tests to Psammead
  CONTRIBUTING.md
  package.json
Labels: alpha-3, documentation, mergeable

#245 Make component documentation more consistent
  CONTRIBUTING.md
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/README.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/README.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/README.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/README.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/README.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/README.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/README.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/README.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/README.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/README.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
Labels: mergeable

#251 Fix Storybook badge in READMEs
  README.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-caption/README.md
  packages/components/psammead-copyright/README.md
  packages/components/psammead-figure/README.md
  packages/components/psammead-headings/README.md
  packages/components/psammead-image-placeholder/README.md
  packages/components/psammead-image/README.md
  packages/components/psammead-inline-link/README.md
  packages/components/psammead-paragraph/README.md
  packages/components/psammead-sitewide-links/README.md
  packages/components/psammead-visually-hidden-text/README.md
Labels: mergeable

#255 Bump psammead-test-helpers version
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
Labels: high priority

#239 Use lerna bootstrap to hoist dependencies
  README.md
  package-lock.json
  package.json
  packages/components/example-button/package-lock.json
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/utilities/psammead-test-helpers/package-lock.json
Labels: mergeable

#258 Add and use method to test a package's exported values
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/README.md
  packages/utilities/psammead-test-helpers/index.test.jsx
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/index.js
Labels: alpha-2, could, mergeable

#253 Add support for high contrast mode and print and no css
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
Labels: alpha-3

#264 Update all the package-locks
  Makefile
  README.md
  package-lock.json
  package.json
  packages/components/example-button/package-lock.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
Labels: high priority

#259 Increase package utilities test coverage
  package-lock.json
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/README.md
  packages/utilities/gel-foundations/index.test.jsx
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/README.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/README.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
Labels: alpha-2, could, mergeable

#248 Remove padding top and bottom from inline links
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-inline-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-inline-link/src/index.jsx
Labels: alpha-3, mergeable

#275 Fixes storybook links by changing bbc-news -> bbc
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .storybook/config.js
  CONTRIBUTING.md
  Makefile
  README.md
  package-lock.json
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/README.md
  packages/components/psammead-caption/package.json
  packages/components/psammead-copyright/README.md
  packages/components/psammead-copyright/package.json
  packages/components/psammead-figure/README.md
  packages/components/psammead-figure/package.json
  packages/components/psammead-headings/README.md
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/README.md
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image/README.md
  packages/components/psammead-image/package.json
  packages/components/psammead-inline-link/README.md
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-paragraph/README.md
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-sitewide-links/README.md
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-visually-hidden-text/README.md
  packages/components/psammead-visually-hidden-text/package.json
  packages/utilities/gel-foundations/README.md
  packages/utilities/gel-foundations/package.json
  packages/utilities/psammead-assets/README.md
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-styles/README.md
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-test-helpers/README.md
  packages/utilities/psammead-test-helpers/package.json
Labels: documentation, mergeable
