Repository bbc/psammead, pull requests merged in 2019-05, with the labels that each got.

#490 Update and Minify SVGs + Add Persian
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/README.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/__snapshots__/svgs.test.jsx.snap
  packages/utilities/psammead-assets/src/svgs.jsx
  packages/utilities/psammead-assets/src/svgs.stories.jsx
  packages/utilities/psammead-assets/src/svgs.test.jsx
Labels: ws-frontpage-stream

#488 Story Promo - mobile widths
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: ws-frontpage-stream

#494 Remove latin script default from @bbc-psammead/timestamp
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/README.md
  packages/components/psammead-timestamp/src/index.jsx
  packages/components/psammead-timestamp/src/index.test.jsx
Labels: ws-frontpage-stream

#502 Bump timestamp version number
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
Labels: high priority, ws-frontpage-stream

#493 Make padding optional
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/README.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-timestamp/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-timestamp/src/index.jsx
  packages/components/psammead-timestamp/src/index.stories.jsx
  packages/components/psammead-timestamp/src/index.test.jsx
Labels: ws-frontpage-stream

#492 Make width optional
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/README.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-image/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-image/src/index.jsx
  packages/components/psammead-image/src/index.stories.jsx
  packages/components/psammead-image/src/index.test.jsx
  packages/components/psammead-image/src/testHelpers/stories.jsx
Labels: ws-frontpage-stream

#496 Add dir storybook decorator
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/decorators.js
  packages/utilities/psammead-storybook-helpers/src/index.js
  packages/utilities/psammead-storybook-helpers/src/index.stories.jsx
  packages/utilities/psammead-storybook-helpers/src/index.test.jsx
Labels: ws-frontpage-stream

#505 colours: update pebble; add metal
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/colours.js
Labels: ws-frontpage-stream

#498 Update stories to use new inputProvider
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/index.stories.jsx
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-figure/src/index.stories.jsx
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/index.stories.jsx
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-inline-link/src/index.stories.jsx
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/index.stories.jsx
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/index.stories.jsx
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
  packages/components/psammead-visually-hidden-text/src/index.stories.jsx
Labels: articles-features-stream, ws-frontpage-stream

#486 Create story promo list component
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/README.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo-list/src/index.jsx
  packages/components/psammead-story-promo-list/src/index.stories.jsx
  packages/components/psammead-story-promo-list/src/index.test.jsx
  packages/components/psammead-story-promo-list/testHelpers/fixtureData.js
Labels: ws-frontpage-stream

#491 Caption paragraph padding
  package-lock.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-caption/src/index.stories.jsx
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-figure/src/index.stories.jsx
Labels: articles-features-stream, high priority

#504 Pass an optional prop of 'id' to SubHeading
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/README.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-headings/src/index.jsx
  packages/components/psammead-headings/src/index.stories.jsx
  packages/components/psammead-headings/src/index.test.jsx
Labels: articles-features-stream

#512 Update dirDecorator to pass script and dir to storybook function
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/decorators.js
  packages/utilities/psammead-storybook-helpers/src/index.stories.jsx
  packages/utilities/psammead-storybook-helpers/src/index.test.jsx
Labels: ws-frontpage-stream

#511 Fixing 12 high security vulnerabilities
  package-lock.json
  package.json
Labels: security, simorgh-core-stream

#489 Add grid fallback to story promo
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-story-promo/src/index.stories.jsx
Labels: ws-frontpage-stream

#510 Create story promo list component
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/README.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo-list/src/index.jsx
  packages/components/psammead-story-promo-list/src/index.stories.jsx
  packages/components/psammead-story-promo-list/src/index.test.jsx
  packages/components/psammead-story-promo-list/testHelpers/fixtureData.js
Labels: ws-frontpage-stream

#515 Replace storybook addon with dirDecorator
  .storybook/addons.js
  .storybook/config.js
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/index.stories.jsx
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-timestamp/src/index.stories.jsx
Labels: ws-frontpage-stream

#514 Upgrade to Node 10
  .nvmrc
  CHANGELOG.md
  Jenkinsfile
  package-lock.json
  package.json
Labels: infra-tooling-stream

#517 Remove unused GEL Types
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/index.test.jsx
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/propTypes/scripts/index.js
  packages/utilities/gel-foundations/src/scripts/latin-and-cyrillic.js
  packages/utilities/gel-foundations/src/typography.js
Labels: ws-frontpage-stream

#525 Update getVersionScript to return array of published package versions
  scripts/publish/src/getRegistryVersion.js
  scripts/publish/test/getRegistryVersion.test.js
Labels: articles-features-stream, infra-tooling-stream, ws-frontpage-stream

#524 Update caption
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-caption/src/index.stories.jsx
Labels: articles-features-stream

#529 Update the patch version of Node
  Jenkinsfile
Labels: infra-tooling-stream

#513 Add Link to Story Promo
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
Labels: ws-frontpage-stream

#480 Control height of Brand SVG
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-brand/src/index.test.jsx
Labels: ws-frontpage-stream

#535 Fix broken story
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/index.stories.jsx
Labels: ws-frontpage-stream

#536 Storybook: add viewport addon
  .storybook/addons.js
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-frontpage-stream

#532 Pull Timestamp container into Psammead.
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/README.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/src/helpers/testHelpers.js
  packages/containers/psammead-timestamp-container/src/index.jsx
  packages/containers/psammead-timestamp-container/src/index.stories.jsx
  packages/containers/psammead-timestamp-container/src/index.test.jsx
  packages/containers/psammead-timestamp-container/src/relativeTimestamp.js
  packages/containers/psammead-timestamp-container/src/relativeTimestamp.test.js
  packages/containers/psammead-timestamp-container/src/timestampUtilities.js
  packages/containers/psammead-timestamp-container/src/timestampUtilities.test.js
Labels: articles-features-stream, ws-frontpage-stream

#449 Create Section Label
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/README.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.jsx
  packages/components/psammead-section-label/src/index.stories.jsx
  packages/components/psammead-section-label/src/index.test.jsx
Labels: ws-frontpage-stream

#534 Remove Timestamp padding from StoryPromo and StoryPromoList
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/README.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo-list/src/index.jsx
  packages/components/psammead-story-promo-list/src/index.stories.jsx
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/index.stories.jsx
Labels: ws-frontpage-stream

#528 Dynamic brand link
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-brand/src/index.test.jsx
Labels: ws-frontpage-stream

#537 Display Psammead-styles colours in Storybook
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/index.stories.jsx
Labels: ws-frontpage-stream

#546 Story Promo Style tweaks
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#548 Bump reith font version from 2.302 to 2.511
  README.md
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/fonts.js
Labels: articles-features-stream

#522 Add mediaIndicator to story promo
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
Labels: ws-frontpage-stream

#554 Storybook stories cleanup
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-caption/src/index.stories.jsx
  packages/components/psammead-copyright/src/index.stories.jsx
  packages/components/psammead-figure/src/index.stories.jsx
  packages/components/psammead-headings/src/index.stories.jsx
  packages/components/psammead-image-placeholder/src/index.stories.jsx
  packages/components/psammead-image/src/index.amp.stories.jsx
  packages/components/psammead-image/src/index.stories.jsx
  packages/components/psammead-inline-link/src/index.stories.jsx
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-paragraph/src/index.stories.jsx
  packages/components/psammead-section-label/src/index.stories.jsx
  packages/components/psammead-sitewide-links/src/index.stories.jsx
  packages/components/psammead-story-promo-list/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-timestamp/src/index.stories.jsx
  packages/components/psammead-visually-hidden-text/src/index.stories.jsx
  packages/containers/psammead-timestamp-container/src/index.stories.jsx
  packages/utilities/psammead-assets/src/svgs.stories.jsx
  packages/utilities/psammead-storybook-helpers/src/index.stories.jsx
  packages/utilities/psammead-styles/src/index.stories.jsx
Labels: articles-features-stream, ws-frontpage-stream

#550 Add audio support to mediaIndicator
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/README.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-media-indicator/src/index.test.jsx
  packages/components/psammead-media-indicator/src/mediaIcons.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#547 Add Typography story in Storybook
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/typography.stories.jsx
Labels: articles-features-stream, ws-frontpage-stream

#540 Updating react version
  package-lock.json
  package.json
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
Labels: simorgh-core-stream
