Repository bbc/psammead, pull requests merged in 2019-04, with the labels that each got.

#410 Update caption padding to match article
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
Labels: high priority

#353 Add support for different scripts typographies
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/README.md
  packages/utilities/gel-foundations/index.test.jsx
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/scripts.js
  packages/utilities/gel-foundations/src/getTypeSizes.js
  packages/utilities/gel-foundations/src/scripts.js
  packages/utilities/gel-foundations/src/scripts/arabic-pashto.js
  packages/utilities/gel-foundations/src/scripts/arabic.js
  packages/utilities/gel-foundations/src/scripts/bengali.js
  packages/utilities/gel-foundations/src/scripts/burmese.js
  packages/utilities/gel-foundations/src/scripts/devanagari-and-gurmukhi.js
  packages/utilities/gel-foundations/src/scripts/latin-and-cyrillic.js
  packages/utilities/gel-foundations/src/scripts/latin-with-diacritics.js
  packages/utilities/gel-foundations/src/scripts/no-ascenders-or-descenders.js
  packages/utilities/gel-foundations/src/scripts/sinhalese.js
  packages/utilities/gel-foundations/src/scripts/tamil.js
  packages/utilities/gel-foundations/src/scripts/thai.js
  packages/utilities/gel-foundations/src/typography.js
  packages/utilities/gel-foundations/tests/getTypeSizes.test.js
Labels: WS Component Library

#378 Add psammead-storybook-helpers package
  packages/utilities/README.md
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/index.js
  packages/utilities/psammead-storybook-helpers/src/index.test.jsx
  packages/utilities/psammead-storybook-helpers/src/input-provider.js
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
Labels: WS Component Library

#364 React i18n library ADR
  documentation/architecture-decision-records/ADR0001-i18n_library.md
  documentation/architecture-decision-records/ADR0002-type_groups.md
Labels: WS Component Library

#418 Add language variants knob to Headline and SubHeading
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/index.stories.jsx
Labels: ws-frontpage-stream

#417 Add text input knob to Copyright
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-copyright/src/index.stories.jsx
Labels: ws-frontpage-stream

#419 Add language variants knob to Inline Link stories
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-inline-link/src/index.stories.jsx
Labels: ws-frontpage-stream

#414 Add new typography method in Paragraph component
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/README.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-paragraph/src/index.jsx
  packages/components/psammead-paragraph/src/index.stories.jsx
  packages/components/psammead-paragraph/src/index.test.jsx
Labels: ws-frontpage-stream

#423 Storybook update
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-frontpage-stream

#413 Add new typography method in Caption component
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/README.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-caption/src/index.stories.jsx
  packages/components/psammead-caption/src/index.test.jsx
Labels: ws-frontpage-stream

#420 Add language variants knob to Paragraph stories
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/index.stories.jsx
Labels: ws-frontpage-stream

#412 H2 styling tweaks round 2
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-headings/src/index.jsx
Labels: article-features-stream

#431 Add custom scripts propTypes in gel-foundations
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/index.test.jsx
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/prop-types.js
  packages/utilities/gel-foundations/src/prop-types.js
  packages/utilities/gel-foundations/src/propTypes/scripts/groups.js
  packages/utilities/gel-foundations/src/propTypes/scripts/index.js
  packages/utilities/gel-foundations/src/propTypes/scripts/sizes.js
Labels: ws-frontpage-stream

#440 Create initial timestamp component
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/README.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-timestamp/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-timestamp/src/index.jsx
  packages/components/psammead-timestamp/src/index.stories.jsx
  packages/components/psammead-timestamp/src/index.test.jsx
Labels: ws-frontpage-stream

#432 Alphabetise text variants
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
Labels: ws-frontpage-stream

#444 Add service svg's to assets
  .storybook/stories.pattern
  CHANGELOG.md
  package-lock.json
  package.json
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/README.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/__snapshots__/svgs.test.jsx.snap
  packages/utilities/psammead-assets/src/svgs.js
  packages/utilities/psammead-assets/src/svgs.jsx
  packages/utilities/psammead-assets/src/svgs.stories.jsx
  packages/utilities/psammead-assets/src/svgs.test.jsx
Labels: ws-frontpage-stream

#430 Add text knobs to remaining stories
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-figure/src/index.stories.jsx
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/index.stories.jsx
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
  packages/components/psammead-visually-hidden-text/src/index.stories.jsx
Labels: ws-frontpage-stream

#428 Add custom propTypes shape to Headings component
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/index.jsx
Labels: ws-frontpage-stream

#446 De-italicise italics in caption
  CHANGELOG.md
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-caption/src/index.stories.jsx
Labels: articles-features-stream

#459 Add custom propTypes shape to Caption and Paragraph components
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-caption/src/index.stories.jsx
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/index.jsx
Labels: ws-frontpage-stream

#457 Enable passing different svgs to Brand component
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-brand/src/index.test.jsx
Labels: ws-frontpage-stream

#453 Create Story promo component (ws frontpage card)
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
Labels: ws-frontpage-stream

#448 Add media indicator
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/README.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-media-indicator/src/index.test.jsx
Labels: ws-frontpage-stream

#461 Make timestamp typography style agnostic
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/README.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-timestamp/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-timestamp/src/index.jsx
  packages/components/psammead-timestamp/src/index.stories.jsx
  packages/components/psammead-timestamp/src/index.test.jsx
Labels: ws-frontpage-stream

#474 Update Story promo headline to use Great Primer
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: ws-frontpage-stream

#476 Fail gracefully when svg not provided
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-brand/src/index.test.jsx
Labels: ws-frontpage-stream

#468 Refactor inputProvider
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/index.stories.jsx
  packages/utilities/psammead-storybook-helpers/src/index.test.jsx
  packages/utilities/psammead-storybook-helpers/src/input-provider.js
  packages/utilities/psammead-storybook-helpers/src/input-provider.jsx
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
Labels: ws-frontpage-stream

#484 Add default labels to issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: infra-tooling-stream, ws-frontpage-stream

#485 Set the correct slack channel name
  Jenkinsfile
Labels: infra-tooling-stream
