Repository bbc/psammead, pull requests merged in 2019-06, with the labels that each got.

#530 A11y storybook addon
  .storybook/addons.js
  .storybook/config.js
  package-lock.json
  package.json
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#575 Minor fixes for unit test bugs
  package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo-list/src/index.test.jsx
Labels: articles-features-stream, bug, onward-journeys-stream, simorgh-core-stream, ws-frontpage-stream

#576 Display Site wide links in one column under 240px
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/List/index.jsx
  packages/components/psammead-sitewide-links/src/__snapshots__/index.test.jsx.snap
Labels: ws-fp-v1, ws-frontpage-stream

#587 Make timestamp :metal:
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-timestamp/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-timestamp/src/index.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#595 Fix code owners notification on packages
  .github/CODEOWNERS
Labels: ws-frontpage-stream

#592 update timestamp container to use latest timestamp; pass padding
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/README.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/src/index.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#588 Story Promo headline - Apply Pica under 600px
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#611 Update section label to use border
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#585 Dynamic sitewide link rows
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/List/index.jsx
  packages/components/psammead-sitewide-links/src/List/index.test.jsx
  packages/components/psammead-sitewide-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/index.test.jsx
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#586 Update GEL Typography values
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/scripts/arabic-pashto.js
  packages/utilities/gel-foundations/src/scripts/arabic.js
  packages/utilities/gel-foundations/src/scripts/bengali.js
  packages/utilities/gel-foundations/src/scripts/burmese.js
  packages/utilities/gel-foundations/src/scripts/devanagari-and-gurmukhi.js
  packages/utilities/gel-foundations/src/scripts/latin-and-cyrillic.js
  packages/utilities/gel-foundations/src/scripts/latin-with-diacritics.js
  packages/utilities/gel-foundations/src/scripts/no-ascenders-or-descenders.js
  packages/utilities/gel-foundations/src/scripts/sinhalese.js
  packages/utilities/gel-foundations/src/scripts/tamil.js
  packages/utilities/gel-foundations/src/scripts/thai.js
  packages/utilities/gel-foundations/tests/getTypeSizes.test.js
Labels: articles-features-stream, ws-fp-v1, ws-frontpage-stream

#616 Remove alpha tag from section label
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/README.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
Labels: ws-fp-v1, ws-frontpage-stream

#617 Allow dynamic placement of copyright component
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package.json
  packages/components/psammead-copyright/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-copyright/src/index.jsx
  packages/components/psammead-copyright/src/index.stories.jsx
  packages/components/psammead-copyright/src/index.test.jsx
Labels: articles-current-epic, articles-features-stream

#628 Fix changelog title for story promo
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
Labels: ws-frontpage-stream

#631 Update Storybook version plus other dependecies
  CHANGELOG.md
  package-lock.json
  package.json
  packages/utilities/psammead-assets/src/svgs.test.jsx
Labels: articles-features-stream, high priority, ws-frontpage-stream

#609 Add lang attribute to brand component
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-brand/src/index.test.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#641 Upgrade Node.js to 10.16.0 & npm to 6.9.0
  .npmrc
  .nvmrc
  CHANGELOG.md
  Jenkinsfile
  package-lock.json
  package.json
Labels: infra-tooling-stream

#578 Add Top story promo styling to existing story promo component
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#610 Hides section header when width <600px
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/README.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.jsx
  packages/components/psammead-section-label/src/index.stories.jsx
  packages/components/psammead-section-label/src/index.test.jsx
Labels: ws-frontpage-stream

#634 Fix the command injection vulnerability is getRegistryVersion.js
  scripts/publish/src/getRegistryVersion.js
  scripts/publish/test/getRegistryVersion.test.js
Labels: infra-tooling-stream, security, simorgh-core-stream

#642 Update brand component story on Storybook
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.stories.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#644 Improve screenreader UX for media indicator
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/README.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-media-indicator/src/index.test.jsx
  packages/components/psammead-media-indicator/src/mediaIcons.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#643 Update timestamp container to accept locale as prop
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/README.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/src/index.jsx
  packages/containers/psammead-timestamp-container/src/index.stories.jsx
  packages/containers/psammead-timestamp-container/src/index.test.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#618 Option to fade images in
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/README.md
  packages/components/psammead-image/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-image/src/index.jsx
  packages/components/psammead-image/src/index.stories.jsx
  packages/components/psammead-image/src/index.test.jsx
  packages/components/psammead-image/src/testHelpers/stories.jsx
Labels: articles-current-epic, articles-features-stream

#638 Create Psammead locale with Igbo & Pidgin Moment Locale
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/ig.js
  packages/utilities/psammead-locales/moment/ig.test.jsx
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/pcm.js
  packages/utilities/psammead-locales/moment/pcm.test.jsx
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
  packages/utilities/psammead-locales/src/.keep
Labels: ws-fp-v1, ws-frontpage-stream

#649 Brand should have max width of 80rem
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#661 Update gel-foundations version in timestamp
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-timestamp/src/__snapshots__/index.test.jsx.snap
Labels: ws-fp-v1, ws-frontpage-stream

#665 Bump psammead-image to 0.4.0
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
Labels: articles-current-epic, articles-features-stream, high priority

#663 Add unit tests to Story Promo
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/index.test.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#604 Remove nanoid
  package-lock.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/List/index.jsx
  packages/components/psammead-sitewide-links/src/index.stories.jsx
Labels: simorgh-core-stream

#666 Timestamp container datetime bug
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/src/index.jsx
  packages/containers/psammead-timestamp-container/src/timestampUtilities.js
Labels: articles-features-stream, ws-frontpage-stream

#669 Update many dependencies in one go
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#676 Add Nassim Persian fonts to psammead-styles
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/fonts.js
Labels: articles-features-stream, articles-next-epic, high priority

#672 Add margin to top of story promo list
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo-list/src/index.jsx
Labels: blocking, ws-fp-v1, ws-frontpage-stream

#679 Update package versions to v1
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
Labels: ws-fp-v1, ws-frontpage-stream

#667 add consent banner to psammead
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/README.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-consent-banner/src/index.jsx
  packages/components/psammead-consent-banner/src/index.stories.jsx
  packages/components/psammead-consent-banner/src/index.test.jsx
Labels: simorgh-core-stream

#677 Update @bbc/gel-foundations in all psammead packages
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
Labels: articles-features-stream, high priority, ws-frontpage-stream

#637 Create Navigation Component
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
  packages/components/psammead-navigation/src/index.test.jsx
  packages/components/psammead-navigation/testHelpers/igbo.js
  packages/components/psammead-navigation/testHelpers/pidgin.js
  packages/components/psammead-navigation/testHelpers/yoruba.js
Labels: ws-fp-v1, ws-frontpage-stream

#684 Fix brand padding
  package-lock.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
Labels: simorgh-core-stream, ws-fp-v1, ws-frontpage-stream

#694 Media Indicator and Link position bugs
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#711 Give Navigation a max-width of 80rem
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#704 Remove `fill` in SVGs
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/__snapshots__/svgs.test.jsx.snap
  packages/utilities/psammead-assets/src/svgs.jsx
Labels: ws-frontpage-stream

#674 Update inputProvider to toggle on serviceName not language
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/decorators.js
  packages/utilities/psammead-storybook-helpers/src/index.stories.jsx
  packages/utilities/psammead-storybook-helpers/src/index.test.jsx
  packages/utilities/psammead-storybook-helpers/src/input-provider.jsx
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
Labels: ws-fp-v1, ws-frontpage-stream

#690 Tidy and ensure more robust fade in
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-image/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-image/src/index.jsx
Labels: articles-current-epic, articles-features-stream

#703 Add sizes support to psammead image
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/README.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-image/src/__snapshots__/index.amp.test.jsx.snap
  packages/components/psammead-image/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-image/src/index.amp.jsx
  packages/components/psammead-image/src/index.jsx
  packages/components/psammead-image/src/testHelpers/fixtureData.js
  packages/components/psammead-image/src/testHelpers/snapshotTests.jsx
  packages/components/psammead-image/src/testHelpers/stories.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#712 Update storypromo dependencies
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.test.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#701 Add REM usage document into Psammead
  documentation/Spacing-Units.md
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/README.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
Labels: articles-features-stream, ws-frontpage-stream
