Repository bbc/psammead, pull requests merged in 2019-07, with the labels that each got.

#722 Hover gap below media indicator
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#741 Remove alpha tag from Story Promo List
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/README.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
Labels: ws-fp-v1, ws-frontpage-stream

#740 Remove alpha tag from Navigation
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
Labels: ws-fp-v1, ws-frontpage-stream

#707 New inline link styling
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/README.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-inline-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-inline-link/src/index.jsx
  packages/components/psammead-inline-link/src/index.stories.jsx
Labels: articles-current-epic, articles-features-stream

#747 Add role of text to brand vis hid text
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.test.jsx
Labels: high priority, ws-fp-v1, ws-frontpage-stream

#706 Fix frontpages amp img not showing in IE
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: bug, high priority, ws-fp-v1, ws-frontpage-stream

#760 Story Promo List - Add missing change to CHANGELOG
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
Labels: ws-frontpage-stream

#761 Inline link color should be ebon
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-inline-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-inline-link/src/index.jsx
Labels: articles-current-epic, articles-features-stream

#767 Ensure psammead-styles version is bumped
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#763 Use metal for caption and inlineLink
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-inline-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-inline-link/src/index.jsx
Labels: articles-features-stream, articles-next-epic

#745 Update inline link story and bump packge info for Caption
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/index.stories.jsx
Labels: articles-features-stream

#758 Add ability to limit service options
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/index.stories.jsx
  packages/utilities/psammead-storybook-helpers/src/index.test.jsx
  packages/utilities/psammead-storybook-helpers/src/input-provider.jsx
Labels: ws-frontpage-stream

#746 Add story containing inline link to Paragraph
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/index.stories.jsx
Labels: articles-features-stream

#764 Add method to get serifbold font
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/font-families.js
  packages/utilities/psammead-styles/src/font-styles.js
Labels: blocking, ws-frontpage-stream

#775 Inline link viewport padding readme
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/README.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
Labels: articles-current-epic, articles-features-stream

#732 use @testing-library/react to generate snapshots
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/index.js
Labels: simorgh-core-stream

#789 Use rem for the Brand SVG height
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
Labels: a11y, ws-frontpage-stream

#788 Use rem instead of px in the Media Indicator SVGs
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/mediaIcons.jsx
Labels: a11y, ws-frontpage-stream

#787 Brand - High contrast colour in Firefox
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs.stories.jsx
Labels: articles-current-epic, articles-features-stream, bug, high priority, shared-components

#776 Make media indicator shorter under 400px
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/README.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-media-indicator/src/index.test.jsx
Labels: ws-frontpage-stream

#893 get knobs values at story render time
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/src/index.stories.jsx
Labels: low-priority, ws-frontpage-stream

#612 Create accessibility-testing-on-device.md
  documentation/accessibility-testing-on-device.md
Labels: a11y, documentation

#942 Revert inline link styling updates
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-inline-link/src/index.jsx
Labels: articles-current-epic, articles-features-stream

#943 pack bump for inline link so it deploys
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
Labels: articles-current-epic, articles-features-stream

#935 high contrast media indicator icons
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/mediaIcons.jsx
Labels: a11y, ws-fp-v1, ws-frontpage-stream

#938 Add margin 0 to reset browser default margins
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
  packages/components/psammead-visually-hidden-text/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-visually-hidden-text/src/index.jsx
Labels: ws-frontpage-stream

#937 Remove alpha tag from StoryPromo
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
Labels: ws-frontpage-stream

#766 bump-dependency in psammead
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#941 Apply font based on service: Paragraph
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/README.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-paragraph/src/index.jsx
  packages/components/psammead-paragraph/src/index.stories.jsx
  packages/components/psammead-paragraph/src/index.test.jsx
Labels: ws-frontpage-stream

#1019 bump inline-link to revert styling changes
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
Labels: articles-current-epic, articles-features-stream

#1021 why didn't this update first time
  packages/components/psammead-caption/package-lock.json
Labels: articles-current-epic, articles-features-stream

#892 bump dependencies
  package-lock.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/gel-foundations/package-lock.json
Labels: simorgh-core-stream

#1037 Reset lock back
  package-lock.json
Labels: simorgh-core-stream

#939 Apply font based on service - Caption
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/README.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-caption/src/index.stories.jsx
  packages/components/psammead-caption/src/index.test.jsx
Labels: ws-frontpage-stream

#1017 Apply font based on the service: Timestamp
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/README.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-timestamp/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-timestamp/src/index.jsx
  packages/components/psammead-timestamp/src/index.stories.jsx
  packages/components/psammead-timestamp/src/index.test.jsx
Labels: ws-frontpage-stream

#1018 Apply font style based on service: SitewideLinks
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/README.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/index.jsx
  packages/components/psammead-sitewide-links/src/index.stories.jsx
  packages/components/psammead-sitewide-links/src/index.test.jsx
Labels: ws-frontpage-stream

#1022 Apply font based on service: StoryPromo
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
Labels: ws-frontpage-stream

#1038 bump component dependencies in psammead components
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: simorgh-core-stream

#1064 Fix Copyright import path in example
  packages/components/psammead-figure/README.md
Labels: articles-features-stream, documentation, simorgh-core-stream, ws-frontpage-stream

#940 Apply font based on service: MediaIndicator
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/README.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-media-indicator/src/index.test.jsx
Labels: ws-frontpage-stream

#1039 Add package change scanner
  Jenkinsfile
  Makefile
  package.json
  scripts/changeScanner/getChanges.js
  scripts/changeScanner/getChanges.test.js
  scripts/changeScanner/index.js
  scripts/changeScanner/index.test.js
Labels: simorgh-core-stream

#1082 Bump lodash
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
Labels: articles-features-stream, dependencies, security, simorgh-core-stream, ws-frontpage-stream

#1025 Apply font based on service: ConsentBanner
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/README.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-consent-banner/src/index.jsx
  packages/components/psammead-consent-banner/src/index.stories.jsx
  packages/components/psammead-consent-banner/src/index.test.jsx
Labels: ws-frontpage-stream

#1083 Bump dependency in psammead
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
Labels: dependencies, simorgh-core-stream

#1087 bump psammead-styles in psammead-timestamp
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
Labels: dependencies, simorgh-core-stream

#1155 update dev dependency
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
Labels: dependencies, simorgh-core-stream

#1179 use latest versions
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-test-helpers/CHANGELOG.md
Labels: dependencies, simorgh-core-stream

#1180 Bumping more dependencies
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
Labels: dependencies, simorgh-core-stream

#1027 Apply font style based on service: Navigation
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
  packages/components/psammead-navigation/src/index.test.jsx
Labels: ws-frontpage-stream

#1181 More dependencies bumps
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: dependencies, simorgh-core-stream

#1182 Another batch of dependency bumps
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/README.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/src/index.jsx
  packages/containers/psammead-timestamp-container/src/index.stories.jsx
  packages/containers/psammead-timestamp-container/src/index.test.jsx
Labels: dependencies, simorgh-core-stream

#1089 Remove extra margin in story promo on desktop
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: ws-fp-v1, ws-frontpage-stream

#1203 Bumping dependencies
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo-list/src/index.stories.jsx
  packages/components/psammead-story-promo-list/src/index.test.jsx
Labels: dependencies, simorgh-core-stream

#1205 update dependencies
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
Labels: dependencies, simorgh-core-stream

#1026 Fix storybook propType warnings
  packages/components/psammead-figure/src/index.stories.jsx
  packages/utilities/psammead-locales/moment/index.stories.jsx
Labels: articles-features-stream, shared-components, ws-frontpage-stream

#1183 Build ESM for packages
  .eslintignore
  .gitignore
  CHANGELOG.md
  README.md
  babel.config.js
  package-lock.json
  package.json
Labels: simorgh-core-stream

#1066 Fix serifMedium font
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/font-families.js
Labels: ws-frontpage-stream

#1237 fix vulnerabilities
  package-lock.json
Labels: simorgh-core-stream

#1215 Fix san serif typo
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/font-families.js
Labels: bug, styling, ws-frontpage-stream

#1023 Inline link padding on default styling
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/README.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-inline-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-inline-link/src/index.jsx
Labels: articles-features-stream

#974 Apply font based on service: SectionLabel
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/README.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.jsx
  packages/components/psammead-section-label/src/index.stories.jsx
  packages/components/psammead-section-label/src/index.test.jsx
Labels: ws-frontpage-stream

#791 Update psammead readme
  README.md
  packages/components/README.md
  packages/components/psammead-image-placeholder/CHANGELOG.md
Labels: simorgh-core-stream

#1244 Add service locale to inputProvider callback
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/index.test.jsx
  packages/utilities/psammead-storybook-helpers/src/input-provider.jsx
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
Labels: simorgh-core-stream

#1212 Make Gel foundations ESM usable
  .stylelintrc
  CHANGELOG.md
  babel.config.js
  package-lock.json
  package.json
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/breakpoints.js
  packages/utilities/gel-foundations/breakpoints/package.json
  packages/utilities/gel-foundations/index.test.jsx
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/prop-types.js
  packages/utilities/gel-foundations/prop-types/package.json
  packages/utilities/gel-foundations/scripts.js
  packages/utilities/gel-foundations/scripts/package.json
  packages/utilities/gel-foundations/spacings.js
  packages/utilities/gel-foundations/spacings/package.json
  packages/utilities/gel-foundations/src/prop-types.js
  packages/utilities/gel-foundations/src/prop-types/index.js
  packages/utilities/gel-foundations/src/prop-types/scripts/groups.js
  packages/utilities/gel-foundations/src/prop-types/scripts/index.js
  packages/utilities/gel-foundations/src/prop-types/scripts/sizes.js
  packages/utilities/gel-foundations/src/scripts.js
  packages/utilities/gel-foundations/typography.js
  packages/utilities/gel-foundations/typography/package.json
Labels: simorgh-core-stream

#1214 ESM entry in psammead-assets
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/amp-boilerplate.js
  packages/utilities/psammead-assets/amp-boilerplate/package.json
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs.jsx
  packages/utilities/psammead-assets/src/svgs/bbcBlocks.js
  packages/utilities/psammead-assets/src/svgs/igbo.jsx
  packages/utilities/psammead-assets/src/svgs/news.jsx
  packages/utilities/psammead-assets/src/svgs/persian.jsx
  packages/utilities/psammead-assets/src/svgs/pidgin.jsx
  packages/utilities/psammead-assets/src/svgs/thai.jsx
  packages/utilities/psammead-assets/src/svgs/yoruba.jsx
  packages/utilities/psammead-assets/svgs.js
  packages/utilities/psammead-assets/svgs/package.json
Labels: simorgh-core-stream

#1243 add the photogallery icon
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/README.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-media-indicator/src/index.test.jsx
  packages/components/psammead-media-indicator/src/mediaIcons.jsx
Labels: ws-fp-phase2, ws-frontpage-stream

#1360 Bump psammead assets due to NPM issue
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
Labels: simorgh-core-stream

#1241 Apply font based on service: Headings
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/README.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-headings/src/index.jsx
  packages/components/psammead-headings/src/index.stories.jsx
  packages/components/psammead-headings/src/index.test.jsx
Labels: ws-frontpage-stream

#1358 Only run jest tests on changed files
  package.json
Labels: infra-tooling-stream, simorgh-core-stream

#890 CLI for bumping packages and changelogs
  babel.config.js
  package-lock.json
  package.json
  scripts/bumpChangelogs/cli.js
  scripts/bumpChangelogs/getChangelogCommitMessage.js
  scripts/bumpChangelogs/getNewChangelogContent.js
  scripts/bumpChangelogs/index.js
  scripts/bumpChangelogs/index.test.js
  scripts/bumpChangelogs/mockChangelogs.js
  scripts/bumpChangelogs/writeChangelog.js
  scripts/bumpPackages/cli.js
  scripts/bumpPackages/getVersionBumpCommitMessage.js
  scripts/bumpPackages/index.js
  scripts/bumpPackages/index.test.js
  scripts/publish/index.js
  scripts/publish/test/getPackages.test.js
  scripts/regeneratePackageLocks/index.js
  scripts/regeneratePackageLocks/index.test.js
  scripts/regeneratePackageLocks/removeExistingPackageLock.js
  scripts/regeneratePackageLocks/runNpmInstall.js
  scripts/utilities/commitChanges/index.js
  scripts/utilities/commitChanges/index.test.js
  scripts/utilities/getPackageNames/index.js
  scripts/utilities/getPackageNames/index.test.js
  scripts/utilities/getPackagePath/index.js
  scripts/utilities/getPackagePath/index.test.js
  scripts/utilities/getPackages/index.js
  scripts/utilities/getPackages/index.test.js
  scripts/utilities/initialPrompt/index.js
  scripts/utilities/initialPrompt/index.test.js
  scripts/utilities/promptPackageInput/index.js
  scripts/utilities/promptPackageInput/index.test.js
  scripts/utilities/promptPackageMultiSelect/index.js
  scripts/utilities/promptPackageMultiSelect/index.test.js
  scripts/utilities/promptStageAndCommit/index.js
  scripts/utilities/promptStageAndCommit/index.test.js
  scripts/utilities/readFile/index.js
  scripts/utilities/readFile/index.test.js
  scripts/utilities/stageFile/index.js
  scripts/utilities/stageFile/index.test.js
Labels: simorgh-core-stream

#1245 Add service knob to timestamp-container
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/index.stories.jsx
Labels: simorgh-core-stream

#1405 fix pre-wrap hover bug
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-inline-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-inline-link/src/index.jsx
Labels: articles-features-stream

#1362 SitewideLinks should not use same styling as InlineLink
  package-lock.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/Link/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/Link/index.jsx
  packages/components/psammead-sitewide-links/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/__snapshots__/index.test.jsx.snap
Labels: articles-features-stream, shared-components, ws-frontpage-stream

#1240 Remove unused offscreen text from psammead-media-indicator
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/README.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-media-indicator/src/index.test.jsx
Labels: ws-frontpage-stream

#1352 Correct timestamp formatting
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/src/index.jsx
  packages/containers/psammead-timestamp-container/src/timestampUtilities.js
Labels: ws-fp-phase2, ws-frontpage-stream

#1184 CSS tree validator with custom processor
  .stylelintrc
  lib/stylelint/processorRemoveMixins.js
  lib/stylelint/processorRemoveMixins.test.js
  package-lock.json
  package.json
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-story-promo/src/index.jsx
Labels: simorgh-core-stream

#1365 Bump everything to psammead-styles 1.2.0
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: dependencies, high priority, simorgh-core-stream, ws-frontpage-stream

#1409 Bump media-indicator to 2.3.0
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
Labels: ws-frontpage-stream

#1363 Log publishes to later use to create bumping PR
  .gitignore
  Jenkinsfile
  Makefile
  package.json
  scripts/publish/src/publish.js
  scripts/publish/test/publish.test.js
  scripts/updateDependants/index.js
Labels: high priority, simorgh-core-stream

#1366 Consent banner stories for all services
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/index.stories.jsx
Labels: shared-components

#1416 Add protection for missing file
  Jenkinsfile
  scripts/updateDependants/index.js
Labels: high priority, simorgh-core-stream

#1413 revert styling, remove alpha, bump version
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-inline-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-inline-link/src/index.jsx
Labels: articles-features-stream

#1399 Module to update packages that depend on packages
  package-lock.json
  scripts/upgradeDependencies/index.js
  scripts/upgradeDependencies/index.test.js
  scripts/upgradeDependencies/parseUpgradedPackages.js
Labels: simorgh-core-stream

#1368 Styled Components pure transpilation to aide dead code elimination
  babel.config.js
Labels: simorgh-core-stream

#1479 update import of scripts
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/input-provider.jsx
Labels: simorgh-core-stream

#1367 Create amp-geo component
  packages/components/psammead-amp-geo/CHANGELOG.md
  packages/components/psammead-amp-geo/README.md
  packages/components/psammead-amp-geo/package-lock.json
  packages/components/psammead-amp-geo/package.json
  packages/components/psammead-amp-geo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-amp-geo/src/index.jsx
  packages/components/psammead-amp-geo/src/index.test.jsx
Labels: shared-components

#1408 Use new custom grid detector
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/List/index.jsx
  packages/components/psammead-sitewide-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: ws-fp-phase2, ws-frontpage-stream

#1502 Add media type knob to story promo story
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/index.stories.jsx
Labels: ws-frontpage-stream

#1430 adds overrides for Yoruba relative timestamps
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/ig.test.js
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/pcm.test.js
  packages/utilities/psammead-locales/moment/yo.js
  packages/utilities/psammead-locales/moment/yo.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: blocking, ws-fp-phase2, ws-frontpage-stream

#1517 Clear unit test warnings: SectionLabel
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.test.jsx
Labels: ws-frontpage-stream

#1067 localising relative timestamps
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/src/index.stories.jsx
  packages/containers/psammead-timestamp-container/src/relativeTimestamp.js
  packages/containers/psammead-timestamp-container/src/relativeTimestamp.test.js
  packages/containers/psammead-timestamp-container/src/timestampUtilities.js
  packages/containers/psammead-timestamp-container/src/timestampUtilities.test.js
Labels: ws-fp-phase2, ws-frontpage-stream

#1518 Clear unit test warnings
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.test.jsx
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-image/src/__snapshots__/index.amp.test.jsx.snap
  packages/components/psammead-image/src/testHelpers/snapshotTests.jsx
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/List/index.test.jsx
  packages/components/psammead-sitewide-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/index.test.jsx
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/index.test.jsx
Labels: ws-frontpage-stream

#1477 Add Numerals to Psammead Locale
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/numerals/index.stories.jsx
  packages/utilities/psammead-locales/numerals/package.json
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
  packages/utilities/psammead-locales/src/.keep
  packages/utilities/psammead-locales/src/numerals/__snapshots__/index.test.js.snap
  packages/utilities/psammead-locales/src/numerals/index.js
  packages/utilities/psammead-locales/src/numerals/index.test.js
Labels: most-read, shared-components

#1516 Font families
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/README.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/font-families.js
  packages/utilities/psammead-styles/src/font-styles.js
  packages/utilities/psammead-styles/src/fonts.js
Labels: articles-current-epic, articles-features-stream, high priority, shared-components, ws-frontpage-stream

#1532 fix flaking tests on 31st of the month
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/timestampUtilities.test.js
Labels: bug, high priority, shared-components, ws-frontpage-stream

#1522 Clear storybook warnings in Figure
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-figure/src/index.stories.jsx
Labels: ws-frontpage-stream

#1511 Setup chromaticqa
  .storybook/config.js
  Jenkinsfile
  package-lock.json
  package.json
Labels: simorgh-core-stream

#1524 Change copyright text prop-type
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/README.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/index.jsx
  packages/components/psammead-sitewide-links/src/index.test.jsx
Labels: shared-components, ws-frontpage-stream

#1521 Moment timezone include
  .eslintignore
  package.json
  packages/utilities/moment-timezone-include/.gitignore
  packages/utilities/moment-timezone-include/CHANGELOG.md
  packages/utilities/moment-timezone-include/README.md
  packages/utilities/moment-timezone-include/package-lock.json
  packages/utilities/moment-timezone-include/package.json
  packages/utilities/moment-timezone-include/src/index.js
  packages/utilities/moment-timezone-include/src/index.test.js
  packages/utilities/moment-timezone-include/src/postInstall/index.js
  packages/utilities/moment-timezone-include/src/postInstall/index.test.js
  packages/utilities/moment-timezone-include/src/replaceOriginalTimezoneData/index.js
  packages/utilities/moment-timezone-include/src/replaceOriginalTimezoneData/index.test.js
  packages/utilities/moment-timezone-include/src/writeNewTimezoneData/index.js
  packages/utilities/moment-timezone-include/src/writeNewTimezoneData/index.test.js
  packages/utilities/moment-timezone-include/src/writeToNestedFile/index.js
  packages/utilities/moment-timezone-include/src/writeToNestedFile/index.test.js
Labels: simorgh-core-stream
