Repository bbc/psammead, pull requests merged in 2019-10, with the labels that each got.

#2277 Fix changelog formatting
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2190 Add moment calendar conversion utility
  packages/utilities/psammead-calendars/CHANGELOG.md
  packages/utilities/psammead-calendars/README.md
  packages/utilities/psammead-calendars/package-lock.json
  packages/utilities/psammead-calendars/package.json
  packages/utilities/psammead-calendars/src/calendars.stories.jsx
  packages/utilities/psammead-calendars/src/calendars/jalaali.js
  packages/utilities/psammead-calendars/src/calendars/jalaali.test.js
  packages/utilities/psammead-calendars/src/index.js
Labels: articles-current-epic, articles-features-stream, shared-components, simorgh-core-stream

#2213 Grid
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/README.md
  packages/components/psammead-grid/documentation/8-column-grid-with-items-6-2-2-2-with-labels.png
  packages/components/psammead-grid/documentation/Screenshot-example-with-gelMargins-and-gelGutters.png
  packages/components/psammead-grid/documentation/Screenshot-example-without-gelMargins-and-gelGutters.png
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-grid/src/index.jsx
  packages/components/psammead-grid/src/index.stories.jsx
  packages/components/psammead-grid/src/index.test.jsx
  packages/components/psammead-grid/src/testHelpers.jsx
Labels: articles-features-stream, grid, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2273 Talos - Bump @bbc/psammead-styles
  .storybook/config.js
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/global-styles.test.jsx
Labels: simorgh-core-stream, ws-frontpage-stream

#2289 Talos - Bump @bbc/psammead-brand, @bbc/psammead-caption, @bbc/psammead-consent-banner...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: simorgh-core-stream, ws-frontpage-stream

#2284 Add AV audio skin story - AMP player
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/index.stories.jsx
Labels: ws-media- LiveRadioV1, ws-media-stream

#2281 Amp validation allowfullscreen attribute
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Amp/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Amp/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
Labels: ws-media- LiveRadioV1, ws-media-stream

#2288 Fix datestamps discrepancies
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/es.js
  packages/utilities/psammead-locales/moment/es.test.js
  packages/utilities/psammead-locales/moment/pt-br.js
  packages/utilities/psammead-locales/moment/pt-br.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: bug, ws-frontpage-stream

#2280 Remove scrolling="no" from Media Player
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.stories.jsx
Labels: a11y, articles-av-epic, articles-features-stream, ws-media- LiveRadioV1, ws-media-stream

#2293 Fix psammead grid
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
Labels: simorgh-core-stream

#2297 define placeholderSrc
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.test.jsx
Labels: Heracles, bug, simorgh-core-stream

#2290 Create en-gb locale
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/en-gb.js
  packages/utilities/psammead-locales/moment/en-gb.test.js
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-features-stream, articles-next-13, simorgh-core-stream

#2298 Talos - Bump @bbc/psammead-locales
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2304 Add utility package rich-text-transforms
  packages/utilities/psammead-rich-text-transforms/CHANGELOG.md
  packages/utilities/psammead-rich-text-transforms/README.md
  packages/utilities/psammead-rich-text-transforms/index.js
  packages/utilities/psammead-rich-text-transforms/package-lock.json
  packages/utilities/psammead-rich-text-transforms/package.json
  packages/utilities/psammead-rich-text-transforms/src/candy-xml.js
  packages/utilities/psammead-rich-text-transforms/src/models/fragment.js
  packages/utilities/psammead-rich-text-transforms/src/models/index.js
  packages/utilities/psammead-rich-text-transforms/src/models/url-link.js
  packages/utilities/psammead-rich-text-transforms/src/string.js
  packages/utilities/psammead-rich-text-transforms/test/candy-xml.test.js
  packages/utilities/psammead-rich-text-transforms/test/models/fragment.test.js
  packages/utilities/psammead-rich-text-transforms/test/models/url-link.test.js
  packages/utilities/psammead-rich-text-transforms/test/string.test.js
Labels: simorgh-core-stream, ws-media-asset-page-v1, ws-media-stream

#2308 Fix styling for IE for useful links
  packages/components/psammead-useful-links/CHANGELOG.md
  packages/components/psammead-useful-links/package-lock.json
  packages/components/psammead-useful-links/package.json
  packages/components/psammead-useful-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-useful-links/src/index.jsx
Labels: ws-fp-phase3, ws-frontpage-stream

#2253 Create psammead-play-button for use in Media Player placeholder
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/README.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
  packages/components/psammead-play-button/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-play-button/src/index.jsx
  packages/components/psammead-play-button/src/index.stories.jsx
  packages/components/psammead-play-button/src/index.test.jsx
Labels: a11y-swarm, articles-av-epic, articles-features-stream, ux

#2309 Add brand assets for CF, Naidheachdan and Weather
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/__snapshots__/svgs.test.jsx.snap
  packages/utilities/psammead-assets/src/svgs.jsx
  packages/utilities/psammead-assets/src/svgs/cymrufyw.jsx
  packages/utilities/psammead-assets/src/svgs/naidheachdan.jsx
  packages/utilities/psammead-assets/src/svgs/weather.jsx
Labels: articles-features-stream, articles-next-13

#2314 Talos - Bump @bbc/psammead-brand, @bbc/psammead-caption, @bbc/psammead-copyright...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#2312 Add lang to src of media player stories
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/index.stories.jsx
Labels: articles-av-epic, articles-features-stream, ws-media- LiveRadioV1, ws-media-stream

#2342 Fix Moment defineLocale warning
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/index.stories.jsx
Labels: simorgh-core-stream, ws-frontpage-stream

#2344 Update Punjabi text variant locale
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
Labels: ws-frontpage-stream

#2343 Add data attribute to navigation links
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
Labels: ws-frontpage-stream

#2296 Story promo 1008+px
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: ws-fp-phase3, ws-frontpage-stream

#2353 Add data attribute to SectionLabel Component
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/README.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.jsx
Labels: ws-frontpage-stream

#2294 Create Script Switch component
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/README.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-script-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-script-link/src/index.jsx
  packages/components/psammead-script-link/src/index.stories.jsx
  packages/components/psammead-script-link/src/index.test.jsx
Labels: ux, ws-fp-phase3, ws-frontpage-stream

#2318 bumping dependencies
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
  packages/components/psammead-play-button/src/__snapshots__/index.test.jsx.snap
Labels: dependencies, simorgh-core-stream

#2300 Add numeral system translator helper
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/numerals/index.stories.jsx
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
  packages/utilities/psammead-locales/src/numerals/__snapshots__/index.test.js.snap
  packages/utilities/psammead-locales/src/numerals/index.js
  packages/utilities/psammead-locales/src/numerals/index.test.js
Labels: articles-current-epic, articles-features-stream

#2349 Yeoman flakey test
  .yeoman/index.test.js
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2347 Return plain text for unsupported nodes
  packages/utilities/psammead-rich-text-transforms/CHANGELOG.md
  packages/utilities/psammead-rich-text-transforms/package-lock.json
  packages/utilities/psammead-rich-text-transforms/package.json
  packages/utilities/psammead-rich-text-transforms/src/candy-xml.js
  packages/utilities/psammead-rich-text-transforms/test/candy-xml.test.js
Labels: ws-media-asset-page-v1, ws-media-stream

#2359 delete Yeoman script tests
  .yeoman/index.test.js
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2354 Add data attribute to StoryPromo Component
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
Labels: ws-frontpage-stream

#2356 Talos - Bump @bbc/psammead-locales
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, simorgh-core-stream

#2365 Change size of column gap for useful links
  packages/components/psammead-useful-links/CHANGELOG.md
  packages/components/psammead-useful-links/package-lock.json
  packages/components/psammead-useful-links/package.json
  packages/components/psammead-useful-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-useful-links/src/index.jsx
Labels: ws-fp-phase3, ws-frontpage-stream

#2362 Fix ScriptLink breakpoints
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-script-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-script-link/src/index.jsx
Labels: ws-frontpage-stream

#2364 use xmldoc instead of xml-js, with refactor to accomadate new package
  packages/utilities/psammead-rich-text-transforms/CHANGELOG.md
  packages/utilities/psammead-rich-text-transforms/package-lock.json
  packages/utilities/psammead-rich-text-transforms/package.json
  packages/utilities/psammead-rich-text-transforms/src/candy-xml.js
  packages/utilities/psammead-rich-text-transforms/test/candy-xml.test.js
Labels: ws-media-asset-page-v1, ws-media-stream

#2360 Use Eastern Arabic numerals in Jalaali dates
  packages/utilities/psammead-calendars/CHANGELOG.md
  packages/utilities/psammead-calendars/README.md
  packages/utilities/psammead-calendars/package-lock.json
  packages/utilities/psammead-calendars/package.json
  packages/utilities/psammead-calendars/src/calendars/jalaali.js
  packages/utilities/psammead-calendars/src/calendars/jalaali.test.js
Labels: articles-features-stream

#2380 Talos - Bump @bbc/psammead-styles
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
  packages/components/psammead-useful-links/CHANGELOG.md
  packages/components/psammead-useful-links/package-lock.json
  packages/components/psammead-useful-links/package.json
Labels: simorgh-core-stream, talos, ws-frontpage-stream

#2315 Update Grid Stories
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/README.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-grid/src/index.stories.jsx
  packages/components/psammead-grid/src/index.test.jsx
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
Labels: grid, shared-components, ws-frontpage-stream

#2377 Spread extra props in components.
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.test.jsx
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.test.jsx
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.jsx
  packages/components/psammead-section-label/src/index.test.jsx
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
Labels: ws-frontpage-stream

#2303 Add logic for adding alternative calendars in timestamps
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/README.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/src/index.jsx
  packages/containers/psammead-timestamp-container/src/index.stories.jsx
  packages/containers/psammead-timestamp-container/src/index.test.jsx
  packages/containers/psammead-timestamp-container/src/timestampUtilities.js
  packages/containers/psammead-timestamp-container/src/timestampUtilities.test.js
Labels: articles-current-epic, articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream

#2402 With services knob
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/index.js
  packages/utilities/psammead-storybook-helpers/src/index.stories.jsx
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.jsx
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.test.jsx
Labels: simorgh-core-stream

#2375 Remove old Jalaali helpers in psammead-locales
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/README.md
  packages/utilities/psammead-locales/moment/fa.js
  packages/utilities/psammead-locales/moment/fa.test.js
  packages/utilities/psammead-locales/moment/helpers/jalaali.js
  packages/utilities/psammead-locales/moment/helpers/jalaali.test.js
  packages/utilities/psammead-locales/moment/helpers/stringHelper.js
  packages/utilities/psammead-locales/moment/helpers/stringHelper.test.js
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/moment/ps.js
  packages/utilities/psammead-locales/moment/ps.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-current-epic, articles-features-stream, ws-frontpage-stream

#2348 Add weather blue to colours and weather to fonts
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/colours.test.js.snap
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/colours.js
  packages/utilities/psammead-styles/src/colours.test.js
  packages/utilities/psammead-styles/src/font-families.js
Labels: articles-features-stream, articles-next-13, low-priority

#2406 Remove padding - useful links
  packages/components/psammead-useful-links/CHANGELOG.md
  packages/components/psammead-useful-links/package-lock.json
  packages/components/psammead-useful-links/package.json
  packages/components/psammead-useful-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-useful-links/src/index.jsx
Labels: ws-fp-phase3, ws-frontpage-stream

#2416 Psammead test helpers match snapshot async
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/__snapshots__/index.test.jsx.snap
  packages/utilities/psammead-test-helpers/index.test.jsx
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/index.js
Labels: ws-media-asset-page-v1, ws-media-stream

#2413 Talos - Bump @bbc/psammead-locales
  CHANGELOG.md
  package-lock.json
  package.json
  packages/utilities/psammead-calendars/CHANGELOG.md
  packages/utilities/psammead-calendars/package-lock.json
  packages/utilities/psammead-calendars/package.json
Labels: articles-current-epic, articles-features-stream

#2407 add buildRTLSubstories
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/buildRTLSubstories.js
  packages/utilities/psammead-storybook-helpers/src/buildRTLSubstories.test.js
  packages/utilities/psammead-storybook-helpers/src/index.js
Labels: simorgh-core-stream

#2421 Remove done from matchSnapshotAsync
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/__snapshots__/index.test.jsx.snap
  packages/utilities/psammead-test-helpers/index.test.jsx
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/index.js
Labels: ws-media-asset-page-v1, ws-media-stream

#2369 Fix Timestamp Container service locale
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/index.stories.jsx
  packages/containers/psammead-timestamp-container/src/index.test.jsx
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream

#2437 Remove import storybook-chromatic
  .storybook/config.js
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2410 Media player audio skin story placeholder
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/index.stories.jsx
Labels: ws-media- LiveRadioV1, ws-media-stream

#2434 Add title attribute to media player
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/README.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Amp/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Amp/index.jsx
  packages/components/psammead-media-player/src/Amp/index.test.jsx
  packages/components/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/Canonical/index.test.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
  packages/components/psammead-media-player/src/index.stories.jsx
  packages/components/psammead-media-player/src/index.test.jsx
Labels: a11y, ws-media-asset-page-v1, ws-media-stream

#2447 Replace relative timestamp snapshot tests with assertions
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/src/index.test.jsx
Labels: articles-current-epic, articles-features-stream

#2438 Fix rich-text-transform export
  packages/utilities/psammead-rich-text-transforms/CHANGELOG.md
  packages/utilities/psammead-rich-text-transforms/index.js
  packages/utilities/psammead-rich-text-transforms/package-lock.json
  packages/utilities/psammead-rich-text-transforms/package.json
  packages/utilities/psammead-rich-text-transforms/src/index.js
  packages/utilities/psammead-rich-text-transforms/test/candy-xml.test.js
  packages/utilities/psammead-rich-text-transforms/test/string.test.js
Labels: simorgh-core-stream, ws-media-asset-page-v1, ws-media-stream

#2436 Update Chinese text variant locales
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
Labels: ws-frontpage-stream

#2450 Talos - Bump @bbc/gel-foundations, @bbc/psammead-amp-geo, @bbc/psammead-assets...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2431 Fix nested grid in IE
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-grid/src/index.jsx
  packages/components/psammead-grid/src/index.stories.jsx
Labels: bug, grid, shared-components, ws-frontpage-stream

#2400 chore: bump dependencies (#2385 - #2396)
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2452 Bump dependencies (#2441 - #2445)
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Heracles, simorgh-core-stream

#2317 Add psammead-play-button to Media Player placeholder
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Placeholder/index.jsx
  packages/components/psammead-media-player/src/Placeholder/index.test.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
  packages/components/psammead-media-player/src/index.stories.jsx
  packages/components/psammead-media-player/src/index.test.jsx
Labels: a11y-swarm, articles-av-epic, articles-features-stream, ux

#2460 Fix Storybook console errors
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-image/src/index.amp.stories.jsx
  packages/components/psammead-image/src/index.stories.jsx
  packages/components/psammead-image/src/testHelpers/stories.jsx
Labels: Heracles, simorgh-core-stream

#2453 Ability to create RTL variants of specific/all stories of a kind as substories
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/buildRTLSubstories.js
  packages/utilities/psammead-storybook-helpers/src/buildRTLSubstories.test.js
  packages/utilities/psammead-storybook-helpers/src/index.js
Labels: shared-components, simorgh-core-stream

#2457 Fix storybook bug for Sitewide Links
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/index.stories.jsx
Labels: bug, ws-frontpage-stream

#2464 Add explanation to changeScanner error output
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/changeScanner/index.js
  scripts/changeScanner/index.test.js
Labels: articles-features-stream, simorgh-core-stream

#2471 Russian fonts
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/font-families.js
Labels: articles-features-stream, articles-rollout, blocking

#2477 Talos - Bump @bbc/psammead-styles
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-useful-links/CHANGELOG.md
  packages/components/psammead-useful-links/package-lock.json
  packages/components/psammead-useful-links/package.json
Labels: articles-features-stream, articles-rollout, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2481 Update Lerna to the latest patch release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: infra-tooling-stream

#2456 feat: remove react-test-renderer
  CHANGELOG.md
  package-lock.json
  package.json
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/README.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
Labels: simorgh-core-stream

#2433 Add script boilerplate for amp js
  CHANGELOG.md
  package-lock.json
  package.json
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/amp-boilerplate.jsx
Labels: simorgh-core-stream

#2462 Update line heights for latin with diacritics
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/scripts/latin-with-diacritics.js
Labels: shared-components

#2487 Talos - Bump @bbc/psammead-image-placeholder, @bbc/psammead-media-indicator, @bbc/psammead-media-player...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2490 Talos - Bump @bbc/psammead-brand, @bbc/psammead-caption, @bbc/psammead-consent-banner...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: shared-components

#2424 Add `srcset` to Media Player placeholder image
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/README.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Amp/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Amp/index.jsx
  packages/components/psammead-media-player/src/Amp/index.test.jsx
  packages/components/psammead-media-player/src/Placeholder/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
Labels: articles-av-epic, articles-features-stream

#2492 Add isExternal to url link
  packages/utilities/psammead-rich-text-transforms/CHANGELOG.md
  packages/utilities/psammead-rich-text-transforms/package-lock.json
  packages/utilities/psammead-rich-text-transforms/package.json
  packages/utilities/psammead-rich-text-transforms/src/candy-xml.js
  packages/utilities/psammead-rich-text-transforms/src/models/url-link.js
  packages/utilities/psammead-rich-text-transforms/test/candy-xml.test.js
  packages/utilities/psammead-rich-text-transforms/test/models/url-link.test.js
Labels: ws-media-asset-page-v1, ws-media-stream

#2495 Swap out constructor name from if block
  packages/utilities/psammead-rich-text-transforms/CHANGELOG.md
  packages/utilities/psammead-rich-text-transforms/package-lock.json
  packages/utilities/psammead-rich-text-transforms/package.json
  packages/utilities/psammead-rich-text-transforms/src/candy-xml.js
Labels: bug, ws-media-asset-page-v1, ws-media-stream

#2498 Fix caniuse lite errors
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2466 Create rtl substories
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/index.stories.jsx
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/index.stories.jsx
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/index.stories.jsx
  packages/utilities/psammead-rich-text-transforms/CHANGELOG.md
  packages/utilities/psammead-rich-text-transforms/package-lock.json
  packages/utilities/psammead-rich-text-transforms/package.json
Labels: simorgh-core-stream

#2494 Remove storybook IE workaround
  .storybook/webpack.config.js
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-frontpage-stream

#2458 Make all Grid column groups required
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/README.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/index.jsx
Labels: grid, shared-components, simorgh-core-stream, ws-frontpage-stream

#2474 Add scripLink prop to render `ScriptLink` component
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-brand/src/index.test.jsx
Labels: articles-features-stream, shared-components, ws-frontpage-stream

#2514 Add SerifLight and SansLight functions
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/font-families.js
  packages/utilities/psammead-styles/src/font-styles.js
Labels: shared-components

#2340 Add trustProjectLink to psammead-sitewide-links
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/README.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/List/index.jsx
  packages/components/psammead-sitewide-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/index.jsx
  packages/components/psammead-sitewide-links/src/index.stories.jsx
  packages/components/psammead-sitewide-links/src/index.test.jsx
Labels: articles-features-stream, articles-rollout, bug, shared-components, ws-frontpage-stream

#2520 Talos - Bump @bbc/psammead-brand, @bbc/psammead-caption, @bbc/psammead-consent-banner...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: shared-components, simorgh-core-stream

#2528 Update dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2531 guidance icon
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
Labels: articles-av-epic, articles-features-stream

#2525 Disable Chromatic QA on Moment Locales
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: simorgh-core-stream

#2533 Talos - Bump @bbc/psammead-assets
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
Labels: articles-features-stream

#2527 Create psammead-most-read component and add MostReadTitle
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/README.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/__snapshots__/title.test.jsx.snap
  packages/components/psammead-most-read/src/title.jsx
  packages/components/psammead-most-read/src/title.stories.jsx
  packages/components/psammead-most-read/src/title.test.jsx
Labels: most-read, shared-components

#2399 Layout iteration - Leading story promo 1008px+ layout
  packages/components/psammead-leading-story-promo/CHANGELOG.md
  packages/components/psammead-leading-story-promo/README.md
  packages/components/psammead-leading-story-promo/package-lock.json
  packages/components/psammead-leading-story-promo/package.json
  packages/components/psammead-leading-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-leading-story-promo/src/index.jsx
  packages/components/psammead-leading-story-promo/src/index.stories.jsx
  packages/components/psammead-leading-story-promo/src/index.test.jsx
Labels: a11y-swarm, ux, ws-fp-phase3, ws-frontpage-stream
