Repository bbc/psammead, pull requests merged in 2019-11, with the labels that each got.

#2476 AV: Add empty img alt tag to placeholder
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Placeholder/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
Labels: articles-av-epic, articles-features-stream

#2522 Remove alpha tag from Play Button
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/README.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
Labels: articles-av-epic, articles-features-stream, ws-media-stream

#2516 Fix prop type warnings
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/README.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Amp/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Amp/index.jsx
  packages/components/psammead-media-player/src/Amp/index.test.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
  packages/components/psammead-media-player/src/index.stories.jsx
  packages/components/psammead-media-player/src/index.test.jsx
Labels: articles-features-stream, ws-frontpage-stream

#2428 Alpha Component documentation
  CHANGELOG.md
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, ws-frontpage-stream, ws-media-stream

#2491 Export MostReadItem from psammead-most-read
  CHANGELOG.md
  package-lock.json
  package.json
  packages/README.md
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/README.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/__snapshots__/item.test.jsx.snap
  packages/components/psammead-most-read/src/item.jsx
  packages/components/psammead-most-read/src/item.stories.jsx
  packages/components/psammead-most-read/src/item.test.jsx
Labels: most-read, shared-components

#2539 Fix overlapping between ScriptLink and Brand
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.stories.jsx
Labels: ws-frontpage-stream

#2551 Talos - Bump @bbc/gel-foundations, @bbc/moment-timezone-include, @bbc/psammead-assets...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-leading-story-promo/CHANGELOG.md
  packages/components/psammead-leading-story-promo/package-lock.json
  packages/components/psammead-leading-story-promo/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-calendars/CHANGELOG.md
  packages/utilities/psammead-calendars/package-lock.json
  packages/utilities/psammead-calendars/package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2556 Tighten External Link Test
  packages/utilities/psammead-rich-text-transforms/CHANGELOG.md
  packages/utilities/psammead-rich-text-transforms/package-lock.json
  packages/utilities/psammead-rich-text-transforms/package.json
  packages/utilities/psammead-rich-text-transforms/src/candy-xml.js
  packages/utilities/psammead-rich-text-transforms/test/candy-xml.test.js
Labels: ws-media-asset-page-v2, ws-media-stream

#2565 Psammead Grid - handling case where child is undefined
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/index.jsx
Labels: shared-components

#2554 Dependency Updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2561 Talos - Bump @bbc/psammead-brand, @bbc/psammead-leading-story-promo, @bbc/psammead-timestamp-container...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2545 Update psammead-media-player prop documentation
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/README.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
Labels: articles-av-epic, articles-features-stream

#2567 Add white top border to Navigation
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
Labels: ws-frontpage-stream

#2517 Add guidance to Media player
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Guidance/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Guidance/index.jsx
  packages/components/psammead-media-player/src/Guidance/index.test.jsx
  packages/components/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Placeholder/index.jsx
  packages/components/psammead-media-player/src/Placeholder/index.test.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
  packages/components/psammead-media-player/src/index.stories.jsx
  packages/components/psammead-media-player/src/index.test.jsx
Labels: a11y-swarm, articles-av-epic, articles-features-stream, ux, ws-media-stream

#2564 Move `Skip to content` link from Navigation to the Brand - 2
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-brand/src/index.test.jsx
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
Labels: ws-frontpage-stream

#2576 Guidance adjustments for 240px
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Guidance/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Guidance/index.jsx
  packages/components/psammead-media-player/src/Guidance/index.test.jsx
  packages/components/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
Labels: articles-av-epic, articles-features-stream

#2575 Explicitly set h1 styles display and font weight
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-headings/src/index.jsx
Labels: ws-media-asset-page-v1, ws-media-stream

#2435 Create Bulletin component
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/README.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/index.jsx
  packages/components/psammead-bulletin/src/index.stories.jsx
  packages/components/psammead-bulletin/src/index.test.jsx
Labels: ws-fp-phase3, ws-frontpage-stream

#2586 Fix readme hyperlink
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2493 Show canonical placeholder while media is loading.
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
  packages/components/psammead-media-player/src/index.stories.jsx
Labels: ws-media-asset-page-v1, ws-media-stream

#2581 Add navigation icons to psammead-assets
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/README.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs.jsx
  packages/utilities/psammead-assets/src/svgs.stories.jsx
  packages/utilities/psammead-assets/src/svgs.test.jsx
  packages/utilities/psammead-assets/src/svgs/navigationIcons.jsx
Labels: ws-frontpage-stream

#2607 Bump dependencies
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-image/src/index.stories.jsx
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-timestamp/src/index.jsx
  scripts/publish/test/publish.test.js
Labels: Heracles, dependencies, simorgh-core-stream

#2569 Reduce height of Brand and Script Link components
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-script-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-script-link/src/index.jsx
Labels: ux, ws-fp-phase3, ws-frontpage-stream

#2578 AV: Fix HCM for guidance background colour
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Guidance/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Guidance/index.jsx
  packages/components/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
Labels: articles-av-epic, articles-features-stream

#2615 Talos - Bump @bbc/gel-foundations, @bbc/psammead-amp-geo, @bbc/psammead-assets...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2568 Grid negative margins
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-grid/src/index.jsx
  packages/components/psammead-grid/src/index.stories.jsx
  packages/components/psammead-grid/src/index.test.jsx
Labels: shared-components

#2612 Fix failing unit test in psammead timestamp container
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/timestampUtilities.test.js
Labels: Heracles, simorgh-core-stream

#2641 Add Core icons (Alert and Info) to Psammead Assets
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/README.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs.jsx
  packages/utilities/psammead-assets/src/svgs.stories.jsx
  packages/utilities/psammead-assets/src/svgs.test.jsx
  packages/utilities/psammead-assets/src/svgs/coreIcons.jsx
Labels: articles-av-epic, articles-features-stream, ws-media-stream

#2631 Add AMP_BIND, AMP_ACCESS, AMP_LIST, AMP_MUSTACHE scripts to amp-boilerplate exports
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/__snapshots__/amp-boilerplate.test.jsx.snap
  packages/utilities/psammead-assets/src/amp-boilerplate.jsx
  packages/utilities/psammead-assets/src/amp-boilerplate.test.jsx
Labels: shared-components

#2626 Fix TopStoryPromo Image and Summary width
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: ws-frontpage-stream

#2647 Talos - Bump @bbc/psammead-bulletin, @bbc/psammead-image-placeholder, @bbc/psammead-media-indicator...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
Labels: shared-components

#2627 Adds guidanceMessage prop to Play button
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/README.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
  packages/components/psammead-play-button/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-play-button/src/index.jsx
  packages/components/psammead-play-button/src/index.stories.jsx
  packages/components/psammead-play-button/src/index.test.jsx
Labels: articles-av-epic, articles-features-stream

#2650 Update Codeowners
  .github/CODEOWNERS
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2625 Create Embed Error component
  packages/components/psammead-embed-error/CHANGELOG.md
  packages/components/psammead-embed-error/README.md
  packages/components/psammead-embed-error/package-lock.json
  packages/components/psammead-embed-error/package.json
  packages/components/psammead-embed-error/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-embed-error/src/index.jsx
  packages/components/psammead-embed-error/src/index.stories.jsx
  packages/components/psammead-embed-error/src/index.test.jsx
Labels: articles-av-epic, articles-features-stream

#2652 Talos - Bump @bbc/psammead-play-button
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
Labels: articles-features-stream

#2628 Adds aria-hidden to media player placeholder guidance
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Guidance/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Guidance/index.jsx
  packages/components/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Placeholder/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
Labels: articles-av-epic, articles-features-stream

#2635 feat: add withServiceKnob to generated components
  .yeoman/templates/src/index.stories.jsx
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2648 Add `promoHasImage` prop documentation to `StoryPromo` `Headline` and `Summary`
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
Labels: ws-frontpage-stream

#2644 Bump dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, simorgh-core-stream

#2656 Talos - Bump @bbc/gel-foundations, @bbc/psammead-amp-geo, @bbc/psammead-assets...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-embed-error/CHANGELOG.md
  packages/components/psammead-embed-error/package-lock.json
  packages/components/psammead-embed-error/package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2655 Make navigation icons scale with font size
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs/navigationIcons.jsx
Labels: ws-frontpage-stream

#2583 Create psammead-bulleted-list component
  packages/components/psammead-bulleted-list/CHANGELOG.md
  packages/components/psammead-bulleted-list/README.md
  packages/components/psammead-bulleted-list/package-lock.json
  packages/components/psammead-bulleted-list/package.json
  packages/components/psammead-bulleted-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulleted-list/src/index.jsx
  packages/components/psammead-bulleted-list/src/index.stories.jsx
  packages/components/psammead-bulleted-list/src/index.test.jsx
Labels: a11y, a11y-swarm, ws-media-asset-page-v2, ws-media-stream

#2663 Talos - Bump @bbc/psammead-assets
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-embed-error/CHANGELOG.md
  packages/components/psammead-embed-error/package-lock.json
  packages/components/psammead-embed-error/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2657 Add Denis as a packages code owner
  .github/CODEOWNERS
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2666 Talos - Bump @bbc/psammead-bulletin, @bbc/psammead-embed-error, @bbc/psammead-image-placeholder...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2574 Create MostReadList component
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/README.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/__snapshots__/item.test.jsx.snap
  packages/components/psammead-most-read/src/__snapshots__/list.test.jsx.snap
  packages/components/psammead-most-read/src/__snapshots__/title.test.jsx.snap
  packages/components/psammead-most-read/src/item.jsx
  packages/components/psammead-most-read/src/item.stories.jsx
  packages/components/psammead-most-read/src/item.test.jsx
  packages/components/psammead-most-read/src/list.jsx
  packages/components/psammead-most-read/src/list.stories.jsx
  packages/components/psammead-most-read/src/list.test.jsx
  packages/components/psammead-most-read/src/title.jsx
  packages/components/psammead-most-read/src/title.stories.jsx
  packages/components/psammead-most-read/src/title.test.jsx
Labels: most-read, shared-components

#2543 explain how to use different withServiceKnob decorators per story
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
Labels: simorgh-core-stream

#2661 Update Nepali and Hindi font stacks and add Telugu Bold
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/font-families.js
  packages/utilities/psammead-styles/src/index.stories.jsx
Labels: articles-features-stream, articles-rollout, shared-components

#2685 Script Link - same style on hover and focus
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-script-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-script-link/src/index.jsx
Labels: ws-frontpage-stream

#2681 Talos - Bump @bbc/psammead-storybook-helpers
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2682 Fix layout on most read list
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/__snapshots__/list.test.jsx.snap
  packages/components/psammead-most-read/src/list.jsx
Labels: most-read, shared-components

#2668 Add service variant compatiablity
  CHANGELOG.md
  package-lock.json
  package.json
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.jsx
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.test.jsx
Labels: shared-components

#2684 AV: iFrame scrollbar media player fix
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Amp/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Amp/index.jsx
  packages/components/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
Labels: articles-av-epic, articles-features-stream

#2687 Talos - Bump @bbc/psammead-storybook-helpers
  CHANGELOG.md
  package-lock.json
  package.json
Labels: shared-components

#2691 Update text examples
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
Labels: shared-components

#2695 correct variant value of serbianLat
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
Labels: shared-components

#2611 Change yeoman generator
  .yeoman/index.js
  .yeoman/src/get-existing/index.js
  .yeoman/src/get-package-types/index.js
  .yeoman/src/get-package-types/index.test.js
  .yeoman/src/questions/index.js
  .yeoman/src/questions/index.test.js
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2686 Add a brand and colour for archive
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/__snapshots__/svgs.test.jsx.snap
  packages/utilities/psammead-assets/src/svgs.jsx
  packages/utilities/psammead-assets/src/svgs/archive.jsx
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/colours.test.js.snap
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/colours.js
  packages/utilities/psammead-styles/src/font-families.js
Labels: articles-features-stream, articles-rollout

#2577 Scrollable Navigation
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/hooks/useMediaQuery.js
  packages/components/psammead-navigation/hooks/useMediaQuery.test.js
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/scrollable/package.json
  packages/components/psammead-navigation/src/ScrollableNavigation/index.jsx
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
  packages/components/psammead-navigation/src/index.test.jsx
Labels: ws-fp-phase3, ws-frontpage-stream

#2700 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulleted-list, @bbc/psammead-bulletin...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2680 Fix skip to content link position
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/skip-link/package.json
  packages/components/psammead-brand/src/SkipLink/index.jsx
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-brand/src/index.test.jsx
Labels: ws-frontpage-stream

#2703 Talos - Bump @bbc/psammead-bulleted-list, @bbc/psammead-bulletin, @bbc/psammead-caption...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2694 Add props for screen readers to navigation icons
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs/navigationIcons.jsx
Labels: ws-frontpage-stream

#2704 Add default to variant
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.jsx
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.test.jsx
Labels: ws-frontpage-stream

#2705 Talos - Bump @bbc/psammead-assets
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-embed-error/CHANGELOG.md
  packages/components/psammead-embed-error/package-lock.json
  packages/components/psammead-embed-error/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2708 Talos - Bump @bbc/psammead-bulletin, @bbc/psammead-embed-error, @bbc/psammead-image-placeholder...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2712 Add more text examples
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/README.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.jsx
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.test.jsx
Labels: shared-components

#2646 More template generators
  .yeoman/index.js
  .yeoman/src/questions/index.js
  .yeoman/templates/components/CHANGELOG.md
  .yeoman/templates/components/README.md
  .yeoman/templates/components/package.json
  .yeoman/templates/components/src/index.jsx
  .yeoman/templates/components/src/index.stories.jsx
  .yeoman/templates/components/src/index.test.jsx
  .yeoman/templates/containers/CHANGELOG.md
  .yeoman/templates/containers/README.md
  .yeoman/templates/containers/package.json
  .yeoman/templates/containers/src/index.jsx
  .yeoman/templates/containers/src/index.stories.jsx
  .yeoman/templates/containers/src/index.test.jsx
  .yeoman/templates/src/index.jsx
  .yeoman/templates/utilities/CHANGELOG.md
  .yeoman/templates/utilities/README.md
  .yeoman/templates/utilities/package.json
  .yeoman/templates/utilities/src/index.js
  .yeoman/templates/utilities/src/index.test.js
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#2634 Bulletin component - tablet and desktop layout
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/README.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/index.jsx
  packages/components/psammead-bulletin/src/index.stories.jsx
Labels: ux, ws-fp-phase3, ws-frontpage-stream

#2714 Talos - Bump @bbc/psammead-storybook-helpers
  CHANGELOG.md
  package-lock.json
  package.json
Labels: shared-components

#2702 Integrate Most Read components
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/README.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Item/index.jsx
  packages/components/psammead-most-read/src/Item/index.test.jsx
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/List/index.jsx
  packages/components/psammead-most-read/src/List/index.test.jsx
  packages/components/psammead-most-read/src/Title/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Title/index.jsx
  packages/components/psammead-most-read/src/Title/index.test.jsx
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/index.jsx
  packages/components/psammead-most-read/src/index.stories.jsx
  packages/components/psammead-most-read/src/index.test.jsx
  packages/components/psammead-most-read/src/item.stories.jsx
  packages/components/psammead-most-read/src/list.stories.jsx
  packages/components/psammead-most-read/src/list.test.jsx
  packages/components/psammead-most-read/src/testHelpers/fixtureData.js
  packages/components/psammead-most-read/src/title.stories.jsx
Labels: most-read, shared-components

#2662 Adds No js fallback to Mediaplayer
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/README.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Guidance/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Guidance/index.jsx
  packages/components/psammead-media-player/src/Guidance/index.test.jsx
  packages/components/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Placeholder/index.jsx
  packages/components/psammead-media-player/src/Placeholder/index.test.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
  packages/components/psammead-media-player/src/index.stories.jsx
  packages/components/psammead-media-player/src/index.test.jsx
Labels: a11y-swarm, articles-av-epic, articles-features-stream

#2718 Fix vulnerability
  CHANGELOG.md
  package-lock.json
  package.json
Labels: shared-components

#2711 Dev Dependency Updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2613 Create dropdown navigation
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/dropdown/package.json
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
  packages/components/psammead-navigation/src/DropdownNavigation/index.test.jsx
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
Labels: ws-fp-phase3, ws-frontpage-stream

#2710 GEL Grid - Margins update
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/README.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-grid/src/index.jsx
  packages/components/psammead-grid/src/index.stories.jsx
  packages/components/psammead-grid/src/index.test.jsx
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
Labels: shared-components

#2725 Move hooks dir into src dir
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/ScrollableNavigation/index.jsx
  packages/components/psammead-navigation/src/hooks/useMediaQuery.js
  packages/components/psammead-navigation/src/hooks/useMediaQuery.test.js
Labels: ws-frontpage-stream

#2723 Fix Bulletin live screen reader UX
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/README.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/index.jsx
  packages/components/psammead-bulletin/src/index.stories.jsx
  packages/components/psammead-bulletin/src/index.test.jsx
Labels: ws-frontpage-stream
