Repository bbc/psammead, pull requests merged in 2019-03, with the labels that each got.

#306 Update Sitewide Links colours
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/List/index.jsx
  packages/components/psammead-sitewide-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/index.jsx
Labels: mergeable

#319 Fix dependancies
  .storybook/webpack.config.js
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
Labels: mergeable

#317 Update link command
  README.md
Labels: bug, documentation

#316 Ensure setup as specified in README works
  README.md
  package.json
Labels: high priority

#318 Use new font face and font family in psammead packages
  .storybook/config.js
  package-lock.json
  package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-copyright/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-copyright/src/index.jsx
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-headings/src/index.jsx
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-paragraph/src/index.jsx
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/index.jsx
Labels: v1.0

#338 Limit banner brand to Group 5
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
Labels: v1.0

#349 Add GEL Group A breakpoint
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/index.test.jsx
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/breakpoints.js
Labels: WS Component Library

#354 Update readme to use new naming syntax and add initial changelog
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: bug, documentation

#336 Add storybook addon to show components in RTL
  .storybook/addons.js
  .storybook/config.js
  CHANGELOG.md
  package-lock.json
  package.json
Labels: WS Component Library

#334 Copyright usage examples
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/README.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/README.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-figure/src/index.stories.jsx
Labels: WS Component Library

#371 Inline link colour
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-inline-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-inline-link/src/index.jsx
Labels: v1.0

#384 Added visually hidden text to component story (take 2)
  package-lock.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/README.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-copyright/src/index.stories.jsx
Labels: WS Component Library

#392 Increase padding bottom figure and paragraph
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-figure/src/index.jsx
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-paragraph/src/index.jsx
Labels: must, v1.0

#405 Package version bumps lost in conflicts
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
Labels: v1.0
