Repository bbc/psammead, pull requests merged in 2019-08, with the labels that each got.

#1565 Moment timezone include - Re-Revert
  .eslintignore
  package.json
  packages/utilities/moment-timezone-include/.gitignore
  packages/utilities/moment-timezone-include/CHANGELOG.md
  packages/utilities/moment-timezone-include/README.md
  packages/utilities/moment-timezone-include/package-lock.json
  packages/utilities/moment-timezone-include/package.json
  packages/utilities/moment-timezone-include/src/index.js
  packages/utilities/moment-timezone-include/src/index.test.js
  packages/utilities/moment-timezone-include/src/postInstall/index.js
  packages/utilities/moment-timezone-include/src/postInstall/index.test.js
  packages/utilities/moment-timezone-include/src/replaceOriginalTimezoneData/index.js
  packages/utilities/moment-timezone-include/src/replaceOriginalTimezoneData/index.test.js
  packages/utilities/moment-timezone-include/src/writeNewTimezoneData/index.js
  packages/utilities/moment-timezone-include/src/writeNewTimezoneData/index.test.js
  packages/utilities/moment-timezone-include/src/writeToNestedFile/index.js
  packages/utilities/moment-timezone-include/src/writeToNestedFile/index.test.js
  scripts/publish/src/getRegistryVersion.js
  scripts/publish/test/getRegistryVersion.test.js
Labels: high priority, simorgh-core-stream

#1537 Add CC_TEST_REPORTER_ID
  Jenkinsfile
Labels: infra-tooling-stream

#1359 Add 'LIVE' label to StoryPromo
  package-lock.json
  package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
Labels: a11y-swarm, high priority, ws-fp-phase2, ws-frontpage-stream

#1530 Add large type to gel-foundations
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/index.test.jsx
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/scripts/arabic-pashto.js
  packages/utilities/gel-foundations/src/scripts/arabic.js
  packages/utilities/gel-foundations/src/scripts/bengali.js
  packages/utilities/gel-foundations/src/scripts/burmese.js
  packages/utilities/gel-foundations/src/scripts/devanagari-and-gurmukhi.js
  packages/utilities/gel-foundations/src/scripts/latin-and-cyrillic.js
  packages/utilities/gel-foundations/src/scripts/latin-with-diacritics.js
  packages/utilities/gel-foundations/src/scripts/no-ascenders-or-descenders.js
  packages/utilities/gel-foundations/src/scripts/sinhalese.js
  packages/utilities/gel-foundations/src/scripts/tamil.js
  packages/utilities/gel-foundations/src/scripts/thai.js
  packages/utilities/gel-foundations/src/typography.js
Labels: articles-features-stream, shared-components, ws-frontpage-stream

#1591 Bump Story Promo to the right version
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
Labels: high priority, ws-frontpage-stream

#1566 Bump Up psammead Version
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-current-epic, articles-features-stream

#1570 Update storybook webpack config for full-control mode
  .storybook/webpack.config.js
Labels: simorgh-core-stream

#1595 bump gel-foundations
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
Labels: dependencies, simorgh-core-stream

#1597 bump dependencies
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
Labels: simorgh-core-stream

#1599 Bumping dependency
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: dependencies, simorgh-core-stream

#1592 bump dependencies to latest
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, simorgh-core-stream

#1644 revert bump on gh-pages
  package.json
Labels: simorgh-core-stream

#1645 force old version of gh-pages
  package-lock.json
  package.json
Labels: simorgh-core-stream

#1641 bump dependencies
  packages/components/psammead-inline-link/src/index.stories.jsx
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
Labels: simorgh-core-stream

#1667 bump dependencies
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
Labels: Heracles, dependencies, simorgh-core-stream

#1671 bump dependencies
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
Labels: dependencies, simorgh-core-stream

#1672 Bump heading
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/__snapshots__/index.test.jsx.snap
Labels: simorgh-core-stream

#1594 Consent banner - RTL
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/README.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-consent-banner/src/index.jsx
  packages/components/psammead-consent-banner/src/index.stories.jsx
  packages/components/psammead-consent-banner/src/index.test.jsx
Labels: articles-current-epic, articles-features-stream, shared-components

#1683 bump chromatic
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#1643 remove vertical spacing from story-promo-list
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo-list/src/index.jsx
Labels: ws-frontpage-stream

#1669 Media Indicator - Add support for Index Alsos
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/README.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-media-indicator/src/index.test.jsx
Labels: ws-fp-phase2, ws-frontpage-stream

#1685 Bump utility dependencies
  packages/components/psammead-amp-geo/package-lock.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-test-helpers/package-lock.json
Labels: simorgh-core-stream

#1686 bump deps
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: simorgh-core-stream

#1679 Remove text knob from input-provider
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/index.test.jsx
  packages/utilities/psammead-storybook-helpers/src/input-provider.jsx
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#1687 bumping dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#1680 Add definition of done ADR
  documentation/architecture-decision-records/ADR0003-definition_of_done.md
Labels: articles-features-stream, documentation, shared-components, ws-frontpage-stream

#1642 Lint only changed files in hooks
  package-lock.json
  package.json
Labels: infra-tooling-stream

#1714 Storybook helpers v5
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/index.test.jsx
  packages/utilities/psammead-storybook-helpers/src/input-provider.jsx
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
Labels: simorgh-core-stream, ws-media-stream

#1727 Psammead Styles - Fonts - BaseUrlPath update
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/fonts.js
Labels: shared-components

#1533 Talos
  Jenkinsfile
  Makefile
  package-lock.json
  package.json
  scripts/bumpChangelogs/index.js
  scripts/talos/checkoutBranch/index.js
  scripts/talos/checkoutBranch/index.test.js
  scripts/talos/cli.js
  scripts/talos/commitChanges/index.js
  scripts/talos/commitChanges/index.test.js
  scripts/talos/createPullRequest/index.js
  scripts/talos/createPullRequest/index.test.js
  scripts/talos/getBranchName/index.js
  scripts/talos/getBranchName/index.test.js
  scripts/talos/getChangedPackages/index.js
  scripts/talos/getChangedPackages/index.test.js
  scripts/talos/getPullRequestBody/index.js
  scripts/talos/getPullRequestBody/index.test.js
  scripts/talos/index.js
  scripts/talos/index.test.js
  scripts/updateDependants/index.js
  scripts/upgradeDependencies/index.js
  scripts/utilities/runExec/index.js
  scripts/utilities/runExec/index.test.js
Labels: simorgh-core-stream

#1751 fix vulnerability
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#1758 Thai typography update
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/scripts/thai.js
Labels: shared-components, ws-fp-phase2, ws-frontpage-stream

#1760 Add base to talos pr
  scripts/talos/createPullRequest/index.js
  scripts/talos/createPullRequest/index.test.js
Labels: high priority, simorgh-core-stream

#1731 Add space to copyright text
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/index.jsx
Labels: ws-media- LiveRadioV1, ws-media-stream

#1734 Talos - Bump @bbc/psammead-styles
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
Labels: shared-components, simorgh-core-stream

#1762 Talos - Bump @bbc/psammead-timestamp in @bbc/psammead-timestamp-container
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: simorgh-core-stream

#1567 Add Index Alsos
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/IndexAlsos/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/IndexAlsos/index.jsx
  packages/components/psammead-story-promo/src/IndexAlsos/index.test.jsx
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
  packages/components/psammead-story-promo/testHelpers/IndexAlsosContainer.jsx
  packages/components/psammead-story-promo/testHelpers/relatedItems.js
Labels: ws-fp-phase2, ws-frontpage-stream

#1713 Adding new scripted pipeline running on single node
  Jenkinsfile
  Makefile
  package.json
Labels: infra-tooling-stream

#1534 Section labels with links
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/README.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.jsx
  packages/components/psammead-section-label/src/index.stories.jsx
  packages/components/psammead-section-label/src/index.test.jsx
  packages/components/psammead-section-label/src/titles.jsx
Labels: ws-fp-phase2, ws-frontpage-stream

#1779 fix psammead publishing
  Makefile
Labels: high priority, infra-tooling-stream

#1759 Add SVG names & add Uzbek SVG
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/__snapshots__/svgs.test.jsx.snap
  packages/utilities/psammead-assets/src/svgs.jsx
  packages/utilities/psammead-assets/src/svgs/telugu.jsx
  packages/utilities/psammead-assets/src/svgs/ukrainian.jsx
  packages/utilities/psammead-assets/src/svgs/uzbek.jsx
Labels: shared-components

#1781 Talos - Bump @bbc/psammead-section-label, @bbc/psammead-assets
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
Labels: simorgh-core-stream

#1786 use the correct build result param
  Jenkinsfile
Labels: simorgh-core-stream

#1789 Manually set build result
  Jenkinsfile
Labels: simorgh-core-stream

#1790 Update PR & Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: shared-components

#1804 Talos - Bump @bbc/psammead-amp-geo, @bbc/psammead-brand, @bbc/psammead-caption, @bbc/psammead-consent-banner, @bbc/psammead-copyright, @bbc/psammead-figure, @bbc/psammead-headings, @bbc/psammead-image-placeholder, @bbc/psammead-image, @bbc/psammead-inline-link, @bbc/psammead-media-indicator, @bbc/psammead-navigation, @bbc/psammead-paragraph, @bbc/psammead-section-label, @bbc/psammead-sitewide-links, @bbc/psammead-story-promo-list, @bbc/psammead-story-promo, @bbc/psammead-timestamp, @bbc/psammead-visually-hidden-text, @bbc/psammead-timestamp-container, @bbc/gel-foundations, @bbc/moment-timezone-include, @bbc/psammead-assets, @bbc/psammead-locales, @bbc/psammead-storybook-helpers, @bbc/psammead-styles, @bbc/psammead-test-helpers
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
Labels: simorgh-core-stream

#1805 Talos - Bump @bbc/psammead-timestamp in @bbc/psammead-timestamp-container
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: simorgh-core-stream

#1777 Make psammead-styles treeshakable
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/colours.js
  packages/utilities/psammead-styles/colours/package.json
  packages/utilities/psammead-styles/detection.js
  packages/utilities/psammead-styles/detection/package.json
  packages/utilities/psammead-styles/font-styles.js
  packages/utilities/psammead-styles/font-styles/package.json
  packages/utilities/psammead-styles/fonts.js
  packages/utilities/psammead-styles/fonts/package.json
  packages/utilities/psammead-styles/index.test.jsx
Labels: Heracles, simorgh-core-stream

#1763 Allow Talos to be manually invoked
  Jenkinsfile
  Makefile
  scripts/talos/getChangedPackages/index.js
  scripts/talos/getChangedPackages/index.test.js
Labels: simorgh-core-stream

#1806 Change strings to booleans
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/breakpoints/package.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/prop-types/package.json
  packages/utilities/gel-foundations/scripts/package.json
  packages/utilities/gel-foundations/spacings/package.json
  packages/utilities/gel-foundations/typography/package.json
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/amp-boilerplate/package.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/svgs/package.json
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/numerals/package.json
  packages/utilities/psammead-locales/package.json
Labels: bug, simorgh-core-stream

#1800 buildDiscarder
  Jenkinsfile
Labels: infra-tooling-stream, simorgh-core-stream

#1826 Talos - Bump @bbc/gel-foundations, @bbc/psammead-assets, @bbc/psammead-locales
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
Labels: simorgh-core-stream

#1792 Dev updates - all non react
  package-lock.json
  package.json
Labels: simorgh-core-stream

#1837 fix storybook on ie11
  .storybook/webpack.config.js
  package.json
Labels: simorgh-core-stream, ws-frontpage-stream

#1831 Create Psammead Media Player
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/README.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Amp/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Amp/index.jsx
  packages/components/psammead-media-player/src/Amp/index.test.jsx
  packages/components/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/Canonical/index.test.jsx
  packages/components/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Placeholder/index.jsx
  packages/components/psammead-media-player/src/Placeholder/index.test.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
  packages/components/psammead-media-player/src/index.stories.jsx
  packages/components/psammead-media-player/src/index.test.jsx
Labels: articles-av-epic, articles-features-stream, high priority

#1832 Export `IndexAlsos` from `psammead_story_promo`
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/index-alsos/package.json
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
Labels: ws-fp-phase2, ws-frontpage-stream

#1842 Fix fullscreen for Firefox, Safari, IE
  packages/README.md
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
Labels: articles-av-epic, articles-features-stream

#1843 Talos - Improve PR title
  scripts/talos/createPullRequest/getPackageNames/index.js
  scripts/talos/createPullRequest/getPackageNames/index.test.js
  scripts/talos/createPullRequest/index.js
  scripts/talos/createPullRequest/index.test.js
Labels: Heracles, simorgh-core-stream, talos

#1845 Index Alsos - Remove padding bottom
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/IndexAlsos/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/IndexAlsos/index.jsx
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/testHelpers/IndexAlsosContainer.jsx
Labels: ws-fp-phase2, ws-frontpage-stream

#1846 Import test helper functions
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/README.md
  packages/utilities/psammead-test-helpers/index.test.jsx
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/index.js
Labels: Heracles, simorgh-core-stream

#1829 Visually hide section label on desktop
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/README.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.jsx
  packages/components/psammead-section-label/src/index.stories.jsx
  packages/components/psammead-section-label/src/index.test.jsx
Labels: ws-frontpage-stream

#1849 README.md update
  CHANGELOG.md
  package-lock.json
  package.json
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/README.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
Labels: Heracles, simorgh-core-stream

#1828 Bump root dependencies during Talos execution
  scripts/bumpPackages/index.js
  scripts/publish/src/getPackages.js
  scripts/publish/test/getPackages.test.js
  scripts/talos/commitChanges/index.js
  scripts/talos/commitChanges/index.test.js
  scripts/upgradeDependencies/index.js
  scripts/upgradeDependencies/index.test.js
  scripts/utilities/getPackages/index.js
  scripts/utilities/getPackages/index.test.js
Labels: simorgh-core-stream

#1862 Add code owners
  .github/CODEOWNERS
Labels: simorgh-core-stream

#1918 Revert "Visually hide section label on desktop"
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/README.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.jsx
  packages/components/psammead-section-label/src/index.stories.jsx
  packages/components/psammead-section-label/src/index.test.jsx
Labels: blocking, high priority, ws-frontpage-stream

#1919 Use @testing-library/react in psammead-media-player
  packages/components/psammead-media-player/src/Placeholder/index.test.jsx
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
Labels: simorgh-core-stream, ws-frontpage-stream

#1860 Make linking section labels work on IE11
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/titles.jsx
Labels: blocking, ws-frontpage-stream

#1920 Bump psammead-media-player
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
Labels: simorgh-core-stream, ws-frontpage-stream

#1923 Index Alsos - Add support for RTL
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/IndexAlsos/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/IndexAlsos/index.jsx
  packages/components/psammead-story-promo/src/IndexAlsos/index.test.jsx
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
  packages/components/psammead-story-promo/testHelpers/IndexAlsosContainer.jsx
Labels: ws-fp-phase2, ws-frontpage-stream

#1835 Desktop width top stories
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/IndexAlsos/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/IndexAlsos/index.jsx
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: ux, ws-frontpage-stream

#1925 Fix broken readme links
  packages/README.md
Labels: simorgh-core-stream

#1922 Revert "Revert "Visually hide section label on desktop""
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/README.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.jsx
  packages/components/psammead-section-label/src/index.stories.jsx
  packages/components/psammead-section-label/src/index.test.jsx
Labels: ws-frontpage-stream

#1929 Fix base level psammead issue in talos
  scripts/utilities/getPackagePath/index.js
  scripts/utilities/getPackagePath/index.test.js
Labels: high priority, simorgh-core-stream

#1924 update package-lock with audit fix
  package-lock.json
  package.json
Labels: simorgh-core-stream

#1931 Talos - Catchup on talos work
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/CHANGELOG.md
  packages/components/psammead-inline-link/package-lock.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
Labels: simorgh-core-stream

#1917 Remove react-test-renderer
  packages/utilities/moment-timezone-include/package-lock.json
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/README.md
  packages/utilities/psammead-test-helpers/index.test.jsx
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/index.js
Labels: Heracles, simorgh-core-stream, ws-frontpage-stream

#1937 Talos - Bump @bbc/psammead-test-helpers
  CHANGELOG.md
  package-lock.json
  package.json
Labels: simorgh-core-stream

#1935 Talos - Bump timestamp in timestamp container, and a bunch of top level dev deps
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: simorgh-core-stream

#1938 Consistent use of destructuring props
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/index.jsx
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-headings/src/index.jsx
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-paragraph/src/index.jsx
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/IndexAlsos/index.jsx
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-timestamp/src/index.jsx
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#1841 Modify month names/numerals for Arabic locale
  packages/utilities/psammead-locales/moment/ar.js
  packages/utilities/psammead-locales/moment/ar.test.js
  packages/utilities/psammead-locales/moment/index.stories.jsx
Labels: articles-current-epic, articles-features-stream, shared-components

#1946 Update psammead-locale package version
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: articles-current-epic, articles-features-stream
