Repository bbc/psammead, pull requests merged in 2020-02, with the labels that each got.

#3051 Bumping dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Heracles, ws-home, ws-media-stream, ws-stories

#3038 Display error message for non-JS MAP scenarios
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/README.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Amp/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Amp/index.jsx
  packages/components/psammead-media-player/src/Amp/index.test.jsx
  packages/components/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/Canonical/index.test.jsx
  packages/components/psammead-media-player/src/MediaMessage/index.jsx
  packages/components/psammead-media-player/src/MediaMessage/index.test.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
Labels: ws-media-stream

#3027 Leading story promo stylings on mobile and tablet
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/ImageStyles.jsx
  packages/components/psammead-story-promo/src/TextStyles.jsx
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
Labels: high priority, ws-front-page-layout, ws-home

#3029 Inline Media Indicator
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/README.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-media-indicator/src/index.test.jsx
Labels: high priority, ws-front-page-layout, ws-home

#3060 Refactored Message component to support AV streams expired message
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Amp/index.jsx
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/Message/index.jsx
  packages/components/psammead-media-player/src/Message/index.test.jsx
  packages/components/psammead-media-player/src/index.jsx
Labels: ws-media-stream

#3059 Update gradient on Scrollable Navigation for > 400px
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/index.test.jsx
  packages/components/psammead-navigation/src/ScrollableNavigation/index.jsx
Labels: ws-home

#3068 Style most read wrapper
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/index.jsx
Labels: most-read, ws-home

#3058 Spacing updates on the Story Promo List and Section Label
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.jsx
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo-list/src/index.jsx
Labels: ws-front-page-layout, ws-home

#3062 Media Indicator - remove spacing on the low-level component
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/README.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-media-indicator/src/index.test.jsx
Labels: ws-front-page-layout, ws-home

#3070 Story Promo List - Padding update
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo-list/src/index.jsx
Labels: ws-front-page-layout, ws-home

#3075 Media Indicator - Pass script
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/README.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-media-indicator/src/index.test.jsx
Labels: ws-front-page-layout, ws-home

#3071 Update MostRead README
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/README.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
Labels: most-read, ws-home

#3076 Add parentEnableGelGutters to grid documentation
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/README.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
Labels: ws-home

#3064 Update Russian month translations
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/ru.js
  packages/utilities/psammead-locales/moment/ru.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-home

#3078 Export timestamp-container utilities
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/README.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/index.jsx
  packages/containers/psammead-timestamp-container/src/utilities/timestampUtilities.js
  packages/containers/psammead-timestamp-container/src/utilities/timestampUtilities.test.js
  packages/containers/psammead-timestamp-container/utilities/package.json
Labels: ws-home

#3082 Talos - Bump @bbc/gel-foundations, @bbc/psammead-amp-geo, @bbc/psammead-assets...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-calendars/CHANGELOG.md
  packages/utilities/psammead-calendars/package-lock.json
  packages/utilities/psammead-calendars/package.json
Labels: ws-home, ws-media-stream, ws-stories

#3085 Rename timestampUtilities with index for export
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/index.jsx
  packages/containers/psammead-timestamp-container/src/utilities/index.js
  packages/containers/psammead-timestamp-container/src/utilities/index.test.js
Labels: ws-home

#3061 Create Byline component
  packages/components/psammead-byline/CHANGELOG.md
  packages/components/psammead-byline/README.md
  packages/components/psammead-byline/package-lock.json
  packages/components/psammead-byline/package.json
  packages/components/psammead-byline/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-byline/src/index.jsx
  packages/components/psammead-byline/src/index.stories.jsx
  packages/components/psammead-byline/src/index.test.jsx
Labels: ws-stories

#3104 Bumping dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Heracles, dependencies, ws-home, ws-media-stream, ws-stories

#3105 Use node v12.15.0 & npm 6.13.7
  .npmrc
  .nvmrc
  CHANGELOG.md
  Jenkinsfile
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3073 Use updated media indicator in Story Promo and Index Alsos
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/index.stories.jsx
  packages/components/psammead-grid/src/testHelpers.jsx
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/IndexAlsos/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/IndexAlsos/index.jsx
  packages/components/psammead-story-promo/src/TextStyles.jsx
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
  packages/components/psammead-story-promo/testHelpers/IndexAlsosContainer.jsx
Labels: high priority, ws-front-page-layout, ws-home

#3109 Media Indicator - Pass dir
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/README.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-media-indicator/src/index.test.jsx
Labels: ws-front-page-layout, ws-home

#3074 Format hidden start time in program-card for Radio Schedules
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/README.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/testHelpers/helper.jsx
Labels: radio-schedules, ws-home

#3113 Adding padding between audio player and footer
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
Labels: ws-media-stream

#3114 Add formatDuration utility function to Timestamp-container package
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/utilities/index.js
  packages/containers/psammead-timestamp-container/src/utilities/index.test.js
Labels: radio-schedules, ws-home

#3117 Remove alpha tag from Byline
  packages/components/psammead-byline/CHANGELOG.md
  packages/components/psammead-byline/README.md
  packages/components/psammead-byline/package-lock.json
  packages/components/psammead-byline/package.json
Labels: ws-stories

#3107 Update top-level Story-Promo and Grid
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/index.stories.jsx
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/IndexAlsos/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
  packages/components/psammead-story-promo/testHelpers/IndexAlsosContainer.jsx
Labels: high priority, ws-front-page-layout, ws-home

#3102 Fix double digit column spacing in MostRead
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Rank/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Rank/index.jsx
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/testHelpers/doubleDigitOverride.js
Labels: most-read, ws-home

#3050 create radio schedules wrapper component
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/README.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/programCard/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/ProgramCard/index.test.jsx
  packages/components/psammead-radio-schedule/src/StartTime/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/StartTime/index.jsx
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/index.jsx
  packages/components/psammead-radio-schedule/src/index.stories.jsx
  packages/components/psammead-radio-schedule/src/index.test.jsx
  packages/components/psammead-radio-schedule/src/testHelpers/helper.jsx
Labels: radio-schedules, ws-home

#3121 Talos - Bump @bbc/psammead-grid, @bbc/psammead-story-promo-list, @bbc/psammead-story-promo
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
Labels: high priority, ws-home

#3128 Update GEL_GROUP_4_SCREEN_WIDTH_MAX breakpoint
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/breakpoints.js
Labels: ws-front-page-layout, ws-home

#3130 Apply link to start-time
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/index.jsx
Labels: radio-schedules, ws-home

#3127 Breakpoints restructuring
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/breakpoints.js
Labels: ws-home, ws-media-stream, ws-stories

#3136 Story promo - visually hidden text update
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/IndexAlsos/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/IndexAlsos/index.jsx
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
Labels: ws-front-page-layout, ws-home

#3116 Render max item two columns for most-read
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/README.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Item/index.jsx
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/List/index.jsx
  packages/components/psammead-most-read/src/List/index.test.jsx
  packages/components/psammead-most-read/src/Rank/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Rank/index.jsx
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/index.jsx
  packages/components/psammead-most-read/src/index.stories.jsx
  packages/components/psammead-most-read/src/testHelpers/doubleDigitOverride.js
  packages/components/psammead-most-read/src/testHelpers/gridProps.js
Labels: most-read, ws-home

#3079 Format duration timestamp
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/README.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/ProgramCard/index.test.jsx
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/testHelpers/helper.jsx
Labels: radio-schedules, ws-home

#3151 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulleted-list, @bbc/psammead-bulletin...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: ws-home, ws-stories

#3132 Update RadioSchedule wrapper to include correct hidden start time
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/index.jsx
Labels: radio-schedules, ws-home

#3120 3115 mostread cleanup
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/README.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/index.jsx
  packages/components/psammead-most-read/src/Item/index.test.jsx
  packages/components/psammead-most-read/src/List/index.jsx
  packages/components/psammead-most-read/src/List/index.test.jsx
  packages/components/psammead-most-read/src/Rank/index.jsx
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/index.jsx
  packages/components/psammead-most-read/src/index.stories.jsx
  packages/components/psammead-most-read/src/index.test.jsx
  packages/components/psammead-most-read/src/utilities/doubleDigitOverride.js
  packages/components/psammead-most-read/src/utilities/gridProps.js
  packages/components/psammead-most-read/src/utilities/index.jsx
Labels: most-read, ws-home

#3153 Talos - Bump @bbc/psammead-brand, @bbc/psammead-content-anchor, @bbc/psammead-media-player...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: ws-home

#3155 feat: add matchSnapshotAsync method to README
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/README.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
Labels: ws-stories

#3157 Update Dev Dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3158 Talos - Bump @bbc/gel-foundations, @bbc/moment-timezone-include, @bbc/psammead-assets...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3159 Talos - Bump @bbc/psammead-radio-schedule, @bbc/psammead-test-helpers
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3137 TimestampContainer - fix P3 a11y bug degrading iOS Voice Over UX
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/src/index.jsx
  packages/containers/psammead-timestamp-container/src/index.test.jsx
Labels: a11y, bug, ws-home, ws-media-stream, ws-stories

#3150 Story Promo - Fallback spacing for Leading promo
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/ImageStyles.jsx
  packages/components/psammead-story-promo/src/TextStyles.jsx
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-story-promo/src/index.stories.jsx
Labels: ws-front-page-layout, ws-home

#3161 Bump yargs-parser
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3154 Remove alpha tag from Story Promo component
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
Labels: ws-front-page-layout, ws-home

#3164 Talos - Bump @bbc/psammead-story-promo, @bbc/psammead-timestamp-container
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: ws-home, ws-media-stream, ws-stories

#3175 Fix spacing for pidgin on group2 breakpoint for MostRead
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/utilities/doubleDigitOverride.js
Labels: most-read, ws-home

#3176 Bumping dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3177 Add pointer cursor to menu button.
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
Labels: ws-home

#3181 Alias radio schedule to be a list
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/index.jsx
Labels: radio-schedules, ws-home

#3133 Change background colour from white to ghost
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/titles.jsx
Labels: bug, ws-home, ws-stories
