Repository bbc/psammead, pull requests merged in 2020-08, with the labels that each got.

#3655 Update elliptic to security patched 6.5.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team, security

#3660 Update C_LUNAR_LIGHT
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/colours.test.js.snap
  packages/utilities/psammead-styles/src/colours.js
Labels: ads, cross-team, ws-home

#3663 bump enquirer version to 2.3.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, ws-engage

#3665 Bump yargs-parser
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies

#3666 Add story for Media Message component & remove border
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Message/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Message/index.jsx
  packages/components/psammead-media-player/src/Message/index.test.jsx
  packages/components/psammead-media-player/src/index.stories.jsx
Labels: a11y, ws-media

#3689 force versions of dependencies to remove security vulnerabilities
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team

#3664 Bumping dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies

#3706 Update dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team, dependencies

#3711 Update change scanner in jenkinsfile
  CHANGELOG.md
  Jenkinsfile
  package-lock.json
  package.json
Labels: cross-team

#3712 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulleted-list, @bbc/psammead-bulletin...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: cross-team, dependencies, talos

#3713 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulletin, @bbc/psammead-content-anchor...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: cross-team, dependencies, talos

#3714 Talos - Bump @bbc/psammead-radio-schedule
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team, dependencies, talos
