Repository bbc/psammead, pull requests merged in 2020-09, with the labels that each got.

#3729 Bumping dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies

#3732 Update dependencies for @babel/core & eslint
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team, dependencies, technical-work

#3661 Create Maintainers file
  CHANGELOG.md
  MAINTAINERS.md
  package-lock.json
  package.json
Labels: cross-team, documentation

#3734 Bumping dev dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies

#3725 Create bullet out of CSS instead of SVG for a11y
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-bulleted-list/CHANGELOG.md
  packages/components/psammead-bulleted-list/package-lock.json
  packages/components/psammead-bulleted-list/package.json
  packages/components/psammead-bulleted-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulleted-list/src/index.jsx
Labels: a11y, ws-media

#3736 downgrade storybook versions
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team, ws-engage

#3733 Remove bottom margin from the media player
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
Labels: ws-engage

#3754 Force `prismjs` version again
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies

#3762 Depency bumps
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-engage

#3769 Add Emotion migration notice to README
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: cross-team, technical-work

#3768 Update Node v12.18.4 and npm 6.14.6
  .npmrc
  .nvmrc
  CHANGELOG.md
  Jenkinsfile
  package-lock.json
  package.json
Labels: cross-team

#3780 Dependency bumps
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, ws-engage

#3782 Reduce Thai font size
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/scripts/thai.js
Labels: ws-engage

#3783 Fix white circle in psammead bulleted list bullet
  packages/components/psammead-bulleted-list/CHANGELOG.md
  packages/components/psammead-bulleted-list/package-lock.json
  packages/components/psammead-bulleted-list/package.json
  packages/components/psammead-bulleted-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulleted-list/src/index.jsx
Labels: a11y, a11y-swarm, ws-media

#3798 Talos - Bump Dependencies
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: cross-team, dependencies, talos

#3799 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulletin, @bbc/psammead-content-anchor...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: cross-team, dependencies, talos

#3803 Talos - Bump @bbc/psammead-radio-schedule
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team, dependencies, talos
