Repository bbc/psammead, pull requests merged in 2020-01, with the labels that each got.

#2860 update props for most read
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/README.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/index.jsx
  packages/components/psammead-most-read/src/Item/index.test.jsx
  packages/components/psammead-most-read/src/List/index.jsx
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/index.jsx
  packages/components/psammead-most-read/src/index.stories.jsx
  packages/components/psammead-most-read/src/testHelpers/itemsHelper.js
  packages/components/psammead-most-read/src/testHelpers/itemsHelper.jsx
Labels: most-read, shared-components

#2857 Talos - Bump @bbc/psammead-locales
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-calendars/CHANGELOG.md
  packages/utilities/psammead-calendars/package-lock.json
  packages/utilities/psammead-calendars/package.json
Labels: shared-components

#2863 Talos - Bump @bbc/gel-foundations, @bbc/psammead-amp-geo, @bbc/psammead-assets...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2865 Dev Dep Updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: articles-features-stream, shared-components, simorgh-core-stream, ws-frontpage-stream, ws-media-stream

#2847 Canonical animation for dropdown nav
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
  packages/components/psammead-navigation/src/DropdownNavigation/index.test.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
  packages/components/psammead-navigation/src/index.test.jsx
Labels: ws-frontpage-stream

#2876 Psammead Grid - Remove alpha tag
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/README.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
Labels: ws-frontpage-stream

#2879 Bump browserslist and lerna
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Heracles, articles-features-stream

#2858 Typography updates.
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/scripts/devanagari-and-gurmukhi.js
  packages/utilities/gel-foundations/src/scripts/tamil.js
Labels: ws-home

#2880 Talos - Bump @bbc/psammead-grid
  packages/components/psammead-leading-story-promo/CHANGELOG.md
  packages/components/psammead-leading-story-promo/package-lock.json
  packages/components/psammead-leading-story-promo/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
Labels: ws-home

#2875 Remove aria-hidden from scrollable navigation
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/ScrollableNavigation/index.jsx
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
  packages/components/psammead-navigation/src/index.test.jsx
Labels: ws-home

#2878 Add Psammead Grid as dependency at top-level
  CHANGELOG.md
  package-lock.json
  package.json
  packages/README.md
Labels: ws-home

#2884 Fix bulleted list spacing
  packages/components/psammead-bulleted-list/CHANGELOG.md
  packages/components/psammead-bulleted-list/package-lock.json
  packages/components/psammead-bulleted-list/package.json
  packages/components/psammead-bulleted-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulleted-list/src/index.jsx
  packages/components/psammead-bulleted-list/src/index.test.jsx
Labels: ws-media-stream

#2887 Update script link margin
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-script-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-script-link/src/index.jsx
Labels: ws-home

#2892 Update January in Bengali
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/bn.js
  packages/utilities/psammead-locales/moment/bn.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-home

#2893 Update grid props
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/README.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/index.jsx
Labels: ws-home

#2894 Talos - Bump @bbc/psammead-locales
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-calendars/CHANGELOG.md
  packages/utilities/psammead-calendars/package-lock.json
  packages/utilities/psammead-calendars/package.json
Labels: ws-home

#2869 update most read prop structure
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/README.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Item/index.jsx
  packages/components/psammead-most-read/src/Item/index.test.jsx
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/List/index.jsx
  packages/components/psammead-most-read/src/List/index.test.jsx
  packages/components/psammead-most-read/src/Rank/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Rank/index.jsx
  packages/components/psammead-most-read/src/Rank/index.test.jsx
  packages/components/psammead-most-read/src/Title/index.jsx
  packages/components/psammead-most-read/src/Title/index.test.jsx
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/index.jsx
  packages/components/psammead-most-read/src/index.stories.jsx
  packages/components/psammead-most-read/src/index.test.jsx
  packages/components/psammead-most-read/src/testHelpers/gridProps.js
  packages/components/psammead-most-read/src/testHelpers/index.jsx
  packages/components/psammead-most-read/src/testHelpers/itemsHelper.jsx
Labels: most-read, ws-home

#2917 Remove alpha tag from Brand component
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
Labels: ws-fp-phase3, ws-home

#2807 Bulletin tweaks
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/index.jsx
Labels: ux, ws-home

#2896 Add border only to script link on hover
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-script-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-script-link/src/index.jsx
  packages/components/psammead-script-link/src/index.stories.jsx
Labels: ws-home

#2918 Bumping developer dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-stories

#2921 Fix image knobs from appearing on first load in storybook
  packages/components/psammead-leading-story-promo/CHANGELOG.md
  packages/components/psammead-leading-story-promo/package-lock.json
  packages/components/psammead-leading-story-promo/package.json
  packages/components/psammead-leading-story-promo/src/index.stories.jsx
Labels: ws-home

#2928 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulleted-list, @bbc/psammead-bulletin...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-leading-story-promo/CHANGELOG.md
  packages/components/psammead-leading-story-promo/package-lock.json
  packages/components/psammead-leading-story-promo/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: ws-home, ws-media-stream, ws-stories

#2930 Talos - Bump @bbc/psammead-brand, @bbc/psammead-leading-story-promo, @bbc/psammead-media-player...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#2923 Update navigation padding
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
Labels: ux, ws-home

#2895 Export Most Read Section, Add Faux area for link and fix invalid most read html
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Item/index.jsx
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/List/index.jsx
  packages/components/psammead-most-read/src/Rank/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Rank/index.jsx
  packages/components/psammead-most-read/src/Title/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Title/index.jsx
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/index.jsx
Labels: most-read, ws-home

#2933 Add most read timestamp story
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Item/index.test.jsx
  packages/components/psammead-most-read/src/index.jsx
  packages/components/psammead-most-read/src/index.stories.jsx
  packages/components/psammead-most-read/src/index.test.jsx
  packages/components/psammead-most-read/src/testHelpers/index.jsx
Labels: most-read, ws-home

#2836 Add AV embed timeout handling to Media Player
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/README.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/Canonical/index.test.jsx
  packages/components/psammead-media-player/src/Canonical/useTimeout.jsx
  packages/components/psammead-media-player/src/Canonical/useTimeout.test.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
Labels: articles-av-epic, ws-media-stream, ws-stories

#2940 Update uk china key value
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.test.jsx
Labels: ws-home

#2943 Add and export KINGFISHER colour
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/colours.test.js.snap
  packages/utilities/psammead-styles/src/colours.js
Labels: radio-schedules, ws-home

#2889 Shrink brand before wrap
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-brand/src/index.jsx
Labels: ws-home

#2939 Most Read: fix variant example in storybook
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/index.stories.jsx
  packages/components/psammead-most-read/src/testHelpers/index.jsx
Labels: most-read, ws-home

#2951 Replace aria label with text for nav button
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
Labels: ws-home

#2954 Fix storybook build command
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home

#2955 Talos - Bump @bbc/psammead-storybook-helpers
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home

#2947 Added additional GEL_SPACING for 2.5 - 3.5rem
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/index.test.jsx
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/spacings.js
Labels: ws-media-stream

#2936 Increase viewport of the 1 column most read list, add timestamp spacing, export service overrides for double digit
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Item/index.jsx
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/List/index.jsx
  packages/components/psammead-most-read/src/Rank/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Rank/index.jsx
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/testHelpers/doubleDigitOverride.js
  packages/components/psammead-most-read/src/testHelpers/gridProps.js
Labels: most-read, ws-home

#2952 Use section label in most read
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/README.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Title/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Title/index.jsx
  packages/components/psammead-most-read/src/Title/index.test.jsx
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/index.jsx
  packages/components/psammead-most-read/src/index.stories.jsx
Labels: most-read, ws-home

#2983 Conditionally render timestamp wrapper
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Item/index.jsx
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
Labels: bug, most-read, ws-home

#2982 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulleted-list, @bbc/psammead-bulletin...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-leading-story-promo/CHANGELOG.md
  packages/components/psammead-leading-story-promo/package-lock.json
  packages/components/psammead-leading-story-promo/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: ws-home, ws-media-stream, ws-stories

#2984 Talos - Bump @bbc/psammead-brand, @bbc/psammead-leading-story-promo, @bbc/psammead-media-player...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#2980 Bump babel/cli to 7.8.3 and remove --configFile option from build script
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#2987 Dependency Updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#2946 Move skip link top so it fits within brand banner
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/SkipLink/index.jsx
Labels: ws-home

#2935 Add clock icon for Radio Schedules
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/README.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs/coreIcons.jsx
  packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
Labels: radio-schedules, ws-home

#2937 Story promo generalisation
  packages/components/psammead-leading-story-promo/CHANGELOG.md
  packages/components/psammead-leading-story-promo/README.md
  packages/components/psammead-leading-story-promo/package-lock.json
  packages/components/psammead-leading-story-promo/package.json
  packages/components/psammead-leading-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-leading-story-promo/src/index.jsx
  packages/components/psammead-leading-story-promo/src/index.stories.jsx
  packages/components/psammead-leading-story-promo/src/index.test.jsx
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/README.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/ImageStyles.jsx
  packages/components/psammead-story-promo/src/TextStyles.jsx
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-story-promo/src/index.stories.jsx
  packages/components/psammead-story-promo/src/index.test.jsx
Labels: ws-front-page-layout, ws-home

#2989 Talos - Bump @bbc/psammead-assets
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-embed-error/CHANGELOG.md
  packages/components/psammead-embed-error/package-lock.json
  packages/components/psammead-embed-error/package.json
  packages/components/psammead-embed-error/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
  packages/components/psammead-play-button/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/IndexAlsos/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
Labels: ws-home, ws-media-stream, ws-stories

#2992 Talos - Bump @bbc/psammead-bulletin, @bbc/psammead-embed-error, @bbc/psammead-image-placeholder...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
Labels: ws-home, ws-media-stream, ws-stories

#2991 Revert 2836 - Add AV embed timeout handling to MP
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/README.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/Canonical/index.test.jsx
  packages/components/psammead-media-player/src/Canonical/useTimeout.jsx
  packages/components/psammead-media-player/src/Canonical/useTimeout.test.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
Labels: ws-stories

#2986 Update most read doc
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/README.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
Labels: most-read, ws-home

#2990 Use new GEL spacing constants
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/index.jsx
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/ScrollableNavigation/index.jsx
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-script-link/src/index.jsx
  packages/components/psammead-script-link/src/index.stories.jsx
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/titles.jsx
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/package-lock.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/List/index.jsx
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/index.jsx
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/index.jsx
  packages/components/psammead-useful-links/CHANGELOG.md
  packages/components/psammead-useful-links/package-lock.json
  packages/components/psammead-useful-links/package.json
  packages/components/psammead-useful-links/src/index.jsx
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs.stories.jsx
  packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
Labels: ws-home

#2995 Merge pull request #2995 from bbc/script-link-storybook
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-script-link/src/index.stories.jsx
Labels: ws-home

#2996 Merge pull request #2996 from bbc/Talos/2020123125310
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-embed-error/CHANGELOG.md
  packages/components/psammead-embed-error/package-lock.json
  packages/components/psammead-embed-error/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
Labels: ws-home, ws-media-stream, ws-stories

#2998 Remove unused package `jest-styled-components`
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#2997 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulletin, @bbc/psammead-embed-error...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
Labels: ws-home, ws-media-stream, ws-stories

#3000 Talos - Bump @bbc/psammead-brand, @bbc/psammead-media-player
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3014 Update Story Promo List border-bottom
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo-list/src/index.jsx
Labels: ws-home

#3016 Update typography on headline links in MostRead
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Item/index.jsx
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/__snapshots__/index.test.jsx.snap
Labels: most-read, ws-home

#3021 Bring MostRead out of alpha
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/README.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
Labels: most-read, ws-home

#3023 Fix no image story styling
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: ws-front-page-layout, ws-home

#3026 Story Promo headline tweaks
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: ws-front-page-layout, ws-home

#3028 Bring Navigation out of alpha
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
Labels: ws-home

#3020 Add brand, colour and fonts for Learning English
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/__snapshots__/svgs.test.jsx.snap
  packages/utilities/psammead-assets/src/svgs.jsx
  packages/utilities/psammead-assets/src/svgs/learningenglish.jsx
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/colours.test.js.snap
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/colours.js
  packages/utilities/psammead-styles/src/font-families.js
Labels: ws-home, ws-stories

#3025 Dependabot updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#2582 add ContentAnchor component
  .stylelintrc
  CHANGELOG.md
  babel.config.js
  package-lock.json
  package.json
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/README.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-content-anchor/src/index.jsx
  packages/components/psammead-content-anchor/src/index.stories.jsx
  packages/components/psammead-content-anchor/src/index.test.jsx
Labels: a11y-swarm, ws-home

#3033 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulleted-list, @bbc/psammead-bulletin...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: ws-home, ws-stories

#3018 Update Bulletin promo to match desktop layout
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/ImageStyles.jsx
  packages/components/psammead-bulletin/src/TextStyles.jsx
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/index.jsx
Labels: ux, ws-front-page-layout, ws-home

#2938 Add program card component to radio-schedule
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/README.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/ProgramCard/index.test.jsx
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/index.jsx
  packages/components/psammead-radio-schedule/src/index.stories.jsx
  packages/components/psammead-radio-schedule/src/index.test.jsx
  packages/components/psammead-radio-schedule/src/testHelpers/helper.jsx
Labels: radio-schedules, ws-home

#3034 Talos - Bump @bbc/psammead-brand, @bbc/psammead-media-player, @bbc/psammead-most-read...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#2988 Display start time of programme with clock and timestamp
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/README.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/StartTime/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/StartTime/index.jsx
  packages/components/psammead-radio-schedule/src/StartTime/index.test.jsx
  packages/components/psammead-radio-schedule/src/index.stories.jsx
  packages/components/psammead-radio-schedule/startTime/package.json
Labels: radio-schedules, ws-home
