Repository bbc/psammead, pull requests merged in 2020-05, with the labels that each got.

#3442 Add link to code reviews guide
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Code-Standards-and-Ways-of-Working.md
  README.md
  package-lock.json
  package.json
  packages/README.md
  scripts/talos/README.md
Labels: ws-home, ws-media-stream, ws-stories

#3427 Dependency updates
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3443 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulletin, @bbc/psammead-navigation...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3408 Update durationLabel usage with detokeniser
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/README.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/index.jsx
  packages/components/psammead-radio-schedule/src/testHelpers/helper.jsx
  packages/components/psammead-radio-schedule/src/utilities/index.js
  packages/components/psammead-radio-schedule/src/utilities/index.test.js
Labels: radio-schedules, ws-home

#3451 Talos - Bump @bbc/psammead-radio-schedule
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3450 Social embed amp validation fix
  packages/components/psammead-social-embed/CHANGELOG.md
  packages/components/psammead-social-embed/package-lock.json
  packages/components/psammead-social-embed/package.json
  packages/components/psammead-social-embed/src/Canonical/index.jsx
  packages/components/psammead-social-embed/src/__snapshots__/index.test.jsx.snap
Labels: ws-stories

#3454 Update radio schedule prop types
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/README.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/index.jsx
Labels: radio-schedules, ws-home

#3456 Talos - Bump @bbc/psammead-radio-schedule
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3457 Disabling chromatic tests for content anchor stories
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-content-anchor/src/index.stories.jsx
Labels: ws-home, ws-media-stream, ws-stories

#3455 Dev dependency updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3453 Import updated locales to storybook
  .storybook/config.js
  .storybook/webpack.config.js
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/index.stories.jsx
Labels: ws-home, ws-stories

#3459 Talos - Bump @bbc/psammead-timestamp-container
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: ws-home, ws-media-stream, ws-stories

#3463 Dev dependency updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3465 Talos - Bump @bbc/psammead-radio-schedule
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3466 Add lunar light colour
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/colours.test.js.snap
  packages/utilities/psammead-styles/src/colours.js
Labels: ws-home

#3468 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulleted-list, @bbc/psammead-bulletin...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: ws-home, ws-media-stream, ws-stories

#3470 Section label: apply GHOST background to `See more` link
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/titles.jsx
Labels: ws-home

#3471 Talos - Bump @bbc/psammead-section-label
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home

#3482 Talos - Bump @bbc/gel-foundations, @bbc/moment-timezone-include, @bbc/psammead-amp-geo...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3483 Dev Dependency Updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3476 Resolve Social Embed hydration warning
  packages/components/psammead-social-embed/CHANGELOG.md
  packages/components/psammead-social-embed/package-lock.json
  packages/components/psammead-social-embed/package.json
  packages/components/psammead-social-embed/src/Canonical/index.jsx
  packages/components/psammead-social-embed/src/Canonical/useScript.js
  packages/components/psammead-social-embed/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-social-embed/src/index.test.jsx
Labels: bug, social-embeds, ws-stories

#3472 do not return current date when timestamp is undefined
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/utilities/index.js
  packages/containers/psammead-timestamp-container/src/utilities/index.test.js
Labels: ws-media-stream

#3484 Voice Over MacOS repeating bulleted list items
  packages/components/psammead-bulleted-list/CHANGELOG.md
  packages/components/psammead-bulleted-list/package-lock.json
  packages/components/psammead-bulleted-list/package.json
  packages/components/psammead-bulleted-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulleted-list/src/index.jsx
Labels: a11y, bug, ws-stories

#3501 Create psammead-heading-index package
  packages/components/psammead-heading-index/CHANGELOG.md
  packages/components/psammead-heading-index/README.md
  packages/components/psammead-heading-index/package-lock.json
  packages/components/psammead-heading-index/package.json
  packages/components/psammead-heading-index/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-heading-index/src/index.jsx
  packages/components/psammead-heading-index/src/index.stories.jsx
  packages/components/psammead-heading-index/src/index.test.jsx
Labels: ws-home

#3502 Most read item padding bottom
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Item/index.jsx
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
Labels: most-read, ux, ws-home

#3504 Talos - Bump @bbc/psammead-most-read
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home
