Repository bbc/psammead, pull requests merged in 2020-07, with the labels that each got.

#3570 Dev dependency updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-engage, ws-home, ws-media-stream

#3571 Adding new packages to base package.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-engage, ws-home, ws-media-stream

#3573 Add option to render a link in Psammead Embed Error
  packages/components/psammead-embed-error/CHANGELOG.md
  packages/components/psammead-embed-error/README.md
  packages/components/psammead-embed-error/package-lock.json
  packages/components/psammead-embed-error/package.json
  packages/components/psammead-embed-error/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-embed-error/src/index.jsx
  packages/components/psammead-embed-error/src/index.stories.jsx
  packages/components/psammead-embed-error/src/index.test.jsx
Labels: ux, ws-engage

#3575 adds bottom margin to videoplayer
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
Labels: ws-engage

#3583 Mediaplayer Margin fix
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
Labels: ws-engage

#3584 Talos - Bump @bbc/psammead-media-player
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-engage, ws-media-stream

#3585 adds prop to override h2 element
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/README.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.jsx
  packages/components/psammead-section-label/src/index.stories.jsx
  packages/components/psammead-section-label/src/index.test.jsx
Labels: a11y, ws-engage

#3594 Update Pashto translation for July
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/ps.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-engage

#3588 Adds support to configure story-promo-list to different padding rules
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/README.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo-list/src/index.jsx
  packages/components/psammead-story-promo-list/src/index.stories.jsx
  packages/components/psammead-story-promo-list/src/index.test.jsx
Labels: ws-engage

#3602 Update Thai Canon typography
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/scripts/thai.js
Labels: ws-engage, ws-home, ws-media

#3605 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulleted-list, @bbc/psammead-bulletin...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: ws-engage, ws-home, ws-media

#3610 Adding a 'dark mode' base64 version of BBC_BLOCKS
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs.jsx
  packages/utilities/psammead-assets/src/svgs.stories.jsx
  packages/utilities/psammead-assets/src/svgs.test.jsx
  packages/utilities/psammead-assets/src/svgs/bbcBlocksDarkMode.js
Labels: ws-media

#3615 Moves embed-error out of alpha with a11y fixes
  packages/components/psammead-embed-error/CHANGELOG.md
  packages/components/psammead-embed-error/README.md
  packages/components/psammead-embed-error/package-lock.json
  packages/components/psammead-embed-error/package.json
  packages/components/psammead-embed-error/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-embed-error/src/index.jsx
Labels: includes, ws-engage

#3616 Update Bengali inline link styling
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/scripts/bengali.js
Labels: high priority, ws-engage

#3611 Implementing 'dark mode' for psammead-image-placeholder
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/README.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image-placeholder/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-image-placeholder/src/index.jsx
  packages/components/psammead-image-placeholder/src/index.stories.jsx
  packages/components/psammead-image-placeholder/src/index.test.jsx
Labels: ux, ws-media

#3627 Add spacing between embed error elements
  packages/components/psammead-embed-error/CHANGELOG.md
  packages/components/psammead-embed-error/package-lock.json
  packages/components/psammead-embed-error/package.json
  packages/components/psammead-embed-error/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-embed-error/src/index.jsx
Labels: ws-engage

#3628 Hide visible pink line below nav element
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
Labels: ux, ws-media

#3600 Adding loading state to psammead-media-player
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
  packages/components/psammead-media-player/src/index.stories.jsx
  packages/components/psammead-media-player/src/index.test.jsx
Labels: ux, ws-media

#3636 [DNM] Decouple jest-styled-components from psammead-test-helpers
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/index.js
Labels: technical-work, ws-engage

#3638 [2/2] Decouple jest-styled-components from psammead-test-helpers
  CHANGELOG.md
  jest.config.js
  package-lock.json
  package.json
Labels: technical-work, ws-engage

#3640 Conditionally apply z-index change to psammead-media-player based on whether the loadingImage is being used
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.stories.jsx
Labels: ws-media

#3641 Media-player changelog PR listing updated
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
Labels: ws-media
