Repository bbc/psammead, pull requests merged in 2020-04, with the labels that each got.

#3321 Fix radio schedule duration
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
Labels: radio-schedules, ws-home

#3318 Fix StartTime styling bugs
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/StartTime/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/StartTime/index.jsx
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
Labels: radio-schedules, ws-home

#3327 Minimist vulnerability updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3328 Invalid HTML bug in section label
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/titles.jsx
Labels: ws-home

#3324 Fix FireFox High Contrast Mode for Radio Schedule
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
Labels: radio-schedules, ws-home

#3326 Radio Schedules - Update Program Card Heading markup and CSS
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
Labels: radio-schedules, ws-home

#3340 Attempt to fix talos
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/upgradeDependencies/index.js
  scripts/upgradeDependencies/index.test.js
Labels: ws-home, ws-stories

#3345 Remove white border from Program Card
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
Labels: radio-schedules, ws-home

#3348 Radio Schedules - Fix VoiceOver bug with the NEXT card headline
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
Labels: high priority, radio-schedules, ws-home

#3350 Remove alpha tag from Radio Schedules component
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/README.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: radio-schedules, ws-home

#3351 Update translation for hours in Arabic
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/ar.js
  packages/utilities/psammead-locales/moment/ar.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-home

#3339 Dependency updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3356 Talos - Bump @bbc/gel-foundations, @bbc/moment-timezone-include, @bbc/psammead-amp-geo...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
Labels: ws-home, ws-media-stream, ws-stories

#3357 Update Pashto locale date format for LL & LLL
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/ps.js
  packages/utilities/psammead-locales/moment/ps.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-home

#3359 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulletin
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3349 Social Embed - resolve a11y issues and release
  packages/components/psammead-social-embed/CHANGELOG.md
  packages/components/psammead-social-embed/README.md
  packages/components/psammead-social-embed/package-lock.json
  packages/components/psammead-social-embed/package.json
  packages/components/psammead-social-embed/src/Notice/index.jsx
  packages/components/psammead-social-embed/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-social-embed/src/index.jsx
  packages/components/psammead-social-embed/src/utilities/index.js
  packages/components/psammead-social-embed/src/utilities/index.test.js
Labels: social-embeds, ws-stories

#3374 Add amp ad script to boilerplate
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/__snapshots__/amp-boilerplate.test.jsx.snap
  packages/utilities/psammead-assets/src/amp-boilerplate.jsx
  packages/utilities/psammead-assets/src/amp-boilerplate.test.jsx
Labels: ws-home

#3376 psammead-storybook-helper - add timezone to withServicesKnob helper
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.jsx
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.test.jsx
Labels: ws-home

#3379 Talos - Bump @bbc/psammead-storybook-helpers
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
Labels: ws-home

#3381 Talos - Bump @bbc/gel-foundations, @bbc/moment-timezone-include, @bbc/psammead-amp-geo...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-embed-error/CHANGELOG.md
  packages/components/psammead-embed-error/package-lock.json
  packages/components/psammead-embed-error/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-calendars/CHANGELOG.md
  packages/utilities/psammead-calendars/package-lock.json
  packages/utilities/psammead-calendars/package.json
Labels: ws-home, ws-media-stream, ws-stories

#3362 Update to Node v12.16.2 and npm 6.14.4
  .npmrc
  .nvmrc
  CHANGELOG.md
  Jenkinsfile
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3382 Dependency updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3387 Talos - Bump @bbc/psammead-bulletin, @bbc/psammead-embed-error, @bbc/psammead-image-placeholder...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: ws-home, ws-media-stream, ws-stories

#3388 Update react-helmet
  .storybook/config.js
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Amp/index.jsx
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
  packages/components/psammead-social-embed/CHANGELOG.md
  packages/components/psammead-social-embed/package-lock.json
  packages/components/psammead-social-embed/package.json
  packages/components/psammead-social-embed/src/Amp/index.jsx
  packages/components/psammead-social-embed/src/Canonical/index.jsx
  packages/components/psammead-social-embed/src/index.stories.jsx
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/index.test.jsx
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
Labels: ws-home, ws-media-stream, ws-stories

#3392 Talos - Bump @bbc/gel-foundations, @bbc/moment-timezone-include, @bbc/psammead-amp-geo...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3390 Bump Prettier and disable brackets around single prop
  .prettierrc
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/index.jsx
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/testHelpers/helper.jsx
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/index.stories.jsx
  packages/containers/psammead-timestamp-container/src/index.test.jsx
  packages/containers/psammead-timestamp-container/src/utilities/index.test.js
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/ar.js
  packages/utilities/psammead-locales/moment/ps.js
  packages/utilities/psammead-locales/moment/sr-cyrl.js
  packages/utilities/psammead-locales/moment/sr.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/fonts.js
  scripts/talos/getBranchName/index.js
  scripts/talos/getChangelogHead/index.js
  scripts/upgradeDependencies/parseUpgradedPackages.js
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3398 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulleted-list, @bbc/psammead-bulletin...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3400 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulletin, @bbc/psammead-content-anchor...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3401 Talos - Bump @bbc/psammead-radio-schedule
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3402 Dependency updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3403 Update timestamp utilities - localisation
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/README.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/index.jsx
  packages/containers/psammead-timestamp-container/src/utilities/index.js
  packages/containers/psammead-timestamp-container/src/utilities/index.test.js
Labels: high priority, radio-schedules, ws-home

#3393 Add a detokeniser utility to Psammead
  packages/utilities/psammead-detokeniser/CHANGELOG.md
  packages/utilities/psammead-detokeniser/README.md
  packages/utilities/psammead-detokeniser/package-lock.json
  packages/utilities/psammead-detokeniser/package.json
  packages/utilities/psammead-detokeniser/src/index.js
  packages/utilities/psammead-detokeniser/src/index.test.js
Labels: high priority, radio-schedules, ws-home, ws-stories

#3377 Radio Schedule - ProgramCard - Episode Title & Duration update
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/README.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/index.jsx
  packages/components/psammead-radio-schedule/src/index.stories.jsx
  packages/components/psammead-radio-schedule/src/index.test.jsx
  packages/components/psammead-radio-schedule/src/testHelpers/helper.jsx
Labels: high priority, radio-schedules, ws-home

#3405 Talos - Bump @bbc/psammead-radio-schedule
  CHANGELOG.md
  package-lock.json
  package.json
Labels: radio-schedules, ws-home

#3407 Talos - Bump @bbc/psammead-styles, @bbc/gel-foundations, @bbc/psammead-assets...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home

#3410 Story Promo - Add overflow-wrap property to Link
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/index.jsx
Labels: ws-home

#3412 Update Swahili relative timestamps
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/sw.js
  packages/utilities/psammead-locales/moment/sw.test.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: ws-home

#3413 Talos - Bump @bbc/psammead-locales
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-calendars/CHANGELOG.md
  packages/utilities/psammead-calendars/package-lock.json
  packages/utilities/psammead-calendars/package.json
Labels: ws-home

#3414 Talos - Bump @bbc/psammead-timestamp-container, @bbc/psammead-calendars
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: ws-home

#3430 Change default lang prop in bulletin
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/README.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/index.jsx
  packages/components/psammead-bulletin/src/index.test.jsx
Labels: ws-home

#3409 Adds option to change Typography for MostRead
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/README.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/index.jsx
  packages/components/psammead-most-read/src/Rank/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Rank/index.jsx
  packages/components/psammead-most-read/src/index.stories.jsx
  packages/components/psammead-most-read/src/utilities/index.jsx
  packages/components/psammead-most-read/src/utilities/rankMinWidth.js
Labels: most-read, ws-home, ws-stories

#3438 Export visually hidden text styles
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
  packages/components/psammead-visually-hidden-text/src/index.jsx
Labels: ws-home, ws-stories

#3431 Do not display bulletin summary when it's not available
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/README.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/index.jsx
  packages/components/psammead-bulletin/src/index.stories.jsx
  packages/components/psammead-bulletin/src/index.test.jsx
Labels: ws-home
