Repository bbc/psammead, pull requests merged in 2020-10, with the labels that each got.

#3771 Create Optimo Base service
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/font-families.js
Labels: cross-team

#3809 Dependencies update - eslint, yargs-parser, browserslist
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, ws-media

#3812 Remove package publishing slack notification code
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/publish/src/publish.js
  scripts/publish/src/slackNotification.js
  scripts/publish/test/publish.test.js
  scripts/publish/test/slackNotification.test.js
Labels: cross-team

#3829 Talos - Bump @bbc/psammead-social-embed, @bbc/psammead-story-promo-list, @bbc/psammead-story-promo...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: cross-team, dependencies, talos

#3830 bump minor and patch versions
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team, dependencies

#3831 Talos - Bump @bbc/psammead-bulletin, @bbc/psammead-radio-schedule, @bbc/psammead-timestamp-container
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: cross-team, dependencies, talos

#3805 BBC Reith Qalam typography
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/README.md
  packages/utilities/gel-foundations/index.test.jsx
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/scripts.js
  packages/utilities/gel-foundations/src/scripts/arabic-pashto.js
  packages/utilities/gel-foundations/src/scripts/arabic.js
  packages/utilities/gel-foundations/tests/__snapshots__/getTypeSizes.test.js.snap
  packages/utilities/gel-foundations/tests/getTypeSizes.test.js
Labels: ws-engage

#3806 Storybook support for BBC Reith Qalam scripts
  .storybook/preview.js
  CHANGELOG.md
  package-lock.json
  package.json
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.test.jsx
Labels: ws-engage

#3784 Web vitals
  packages/utilities/web-vitals/CHANGELOG.md
  packages/utilities/web-vitals/README.md
  packages/utilities/web-vitals/__mocks__/react-adaptive-hooks/index.js
  packages/utilities/web-vitals/package-lock.json
  packages/utilities/web-vitals/package.json
  packages/utilities/web-vitals/src/index.js
  packages/utilities/web-vitals/src/index.test.js
  packages/utilities/web-vitals/src/use-event.js
  packages/utilities/web-vitals/src/use-event.test.js
Labels: cross-team, technical-work

#3834 Talos - Bump @bbc/psammead-storybook-helpers, @bbc/web-vitals
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team, dependencies, talos

#3832 Storybook updates to support Reith Qalam
  .storybook/static/fonts/ReithQalam/bold.woff
  .storybook/static/fonts/ReithQalam/bold.woff2
  .storybook/static/fonts/ReithQalam/extrabold.woff
  .storybook/static/fonts/ReithQalam/extrabold.woff2
  .storybook/static/fonts/ReithQalam/light.woff
  .storybook/static/fonts/ReithQalam/light.woff2
  .storybook/static/fonts/ReithQalam/normal.woff
  .storybook/static/fonts/ReithQalam/normal.woff2
  CHANGELOG.md
  package-lock.json
  package.json
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
Labels: ws-engage

#3804 Support for BBC Reith Qalam - font & font family
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/README.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/font-families.test.js.snap
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/__snapshots__/fonts.test.js.snap
  packages/utilities/psammead-styles/src/font-families.js
  packages/utilities/psammead-styles/src/font-families.test.js
  packages/utilities/psammead-styles/src/fonts.js
  packages/utilities/psammead-styles/src/fonts.test.js
Labels: ws-engage

#3838 add updateMinorPatch script
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team

#3842 Optimise jenkins
  CHANGELOG.md
  Makefile
  package-lock.json
  package.json
Labels: cross-team

#3770 Update Code of Conduct to Version 2.0 of Contributor Covenant
  .github/CODE_OF_CONDUCT.md
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  README.md
  package-lock.json
  package.json
Labels: documentation

#3851 Revert premature release of psammead-styles v5.0.0
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/README.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/font-families.test.js.snap
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/__snapshots__/fonts.test.js.snap
  packages/utilities/psammead-styles/src/font-families.js
  packages/utilities/psammead-styles/src/fonts.js
Labels: high priority, ws-engage

#3856 Put Talos to sleep prior to the Emotion migration
  CHANGELOG.md
  Jenkinsfile
  package-lock.json
  package.json
Labels: cross-team, ws-engage

#3867 Install Emotion whilst being backwards compatible with Styled Components
  Jenkinsfile
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  packages/components/psammead-brand/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulleted-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-byline/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-consent-banner/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-copyright/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-embed-error/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-figure/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-grid/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-heading-index/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-headings/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-image-placeholder/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-image/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-inline-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-livel-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Guidance/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Message/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Rank/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/DropdownNavigation/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-paragraph/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-play-button/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/StartTime/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-script-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/Link/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-social-embed/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/IndexAlsos/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-timestamp/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-useful-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-visually-hidden-text/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
Labels: cross-team

#3875 Migrate psammead-assets to Emotion
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs.stories.jsx
Labels: cross-team, technical-work

#3876 Migrate image to emotion
  packages/components/psammead-image/CHANGELOG.md
  packages/components/psammead-image/package-lock.json
  packages/components/psammead-image/package.json
  packages/components/psammead-image/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-image/src/index.jsx
Labels: cross-team, technical-work

#3880 Migrate psammead-styles to Emotion
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/global-styles.test.jsx.snap
  packages/utilities/psammead-styles/src/global-styles.jsx
  packages/utilities/psammead-styles/src/global-styles.test.jsx
Labels: cross-team, technical-work

#3882 Migrate psammead-content-anchor to Emotion
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-content-anchor/src/index.jsx
  packages/components/psammead-content-anchor/src/index.stories.jsx
  packages/components/psammead-content-anchor/src/index.test.jsx
Labels: cross-team, technical-work

#3887 Un-parallelise Psammead build script
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team, technical-work

#3890 L2 - Emotion
  packages/components/psammead-headings/CHANGELOG.md
  packages/components/psammead-headings/package-lock.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-headings/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-headings/src/index.jsx
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image-placeholder/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-image-placeholder/src/index.jsx
  packages/components/psammead-paragraph/CHANGELOG.md
  packages/components/psammead-paragraph/package-lock.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-paragraph/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-paragraph/src/index.jsx
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-script-link/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-script-link/src/index.jsx
  packages/components/psammead-script-link/src/index.stories.jsx
  packages/components/psammead-social-embed/CHANGELOG.md
  packages/components/psammead-social-embed/package-lock.json
  packages/components/psammead-social-embed/package.json
  packages/components/psammead-social-embed/src/Canonical/index.jsx
  packages/components/psammead-social-embed/src/CaptionWrapper/index.jsx
  packages/components/psammead-social-embed/src/Notice/index.jsx
  packages/components/psammead-social-embed/src/SkipLinkWrapper/index.jsx
  packages/components/psammead-social-embed/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-useful-links/CHANGELOG.md
  packages/components/psammead-useful-links/package-lock.json
  packages/components/psammead-useful-links/package.json
  packages/components/psammead-useful-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-useful-links/src/index.jsx
Labels: cross-team, technical-work

#3892 [level 2] Migrate copyright & consent-banner
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-consent-banner/src/index.jsx
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/package-lock.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-copyright/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-copyright/src/index.jsx
Labels: cross-team, technical-work

#3888 [level 2] Migrate bulleted list & heading index
  packages/components/psammead-bulleted-list/CHANGELOG.md
  packages/components/psammead-bulleted-list/package-lock.json
  packages/components/psammead-bulleted-list/package.json
  packages/components/psammead-bulleted-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulleted-list/src/index.jsx
  packages/components/psammead-heading-index/CHANGELOG.md
  packages/components/psammead-heading-index/package-lock.json
  packages/components/psammead-heading-index/package.json
  packages/components/psammead-heading-index/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-heading-index/src/index.jsx
Labels: cross-team, technical-work

#3886 [level 2] Migrate section label to emotion
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.jsx
Labels: cross-team, technical-work

#3899 [Level 3] Migrate psammead-most-read to Emotion
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Item/index.jsx
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/List/index.jsx
  packages/components/psammead-most-read/src/Rank/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Rank/index.jsx
Labels: cross-team, technical-work

#3896 [Emotion - L3] Migrate
  packages/components/psammead-embed-error/CHANGELOG.md
  packages/components/psammead-embed-error/package-lock.json
  packages/components/psammead-embed-error/package.json
  packages/components/psammead-embed-error/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-embed-error/src/index.jsx
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/README.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-indicator/src/index.stories.jsx
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-most-read/src/Item/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Item/index.jsx
  packages/components/psammead-most-read/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/List/index.jsx
  packages/components/psammead-most-read/src/Rank/__snapshots__/index.test.jsx.snap
  packages/components/psammead-most-read/src/Rank/index.jsx
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
  packages/components/psammead-play-button/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-play-button/src/index.jsx
Labels: cross-team, technical-work

#3900 [Level 4] Migrate psammead-navigation
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
  packages/components/psammead-navigation/src/ScrollableNavigation/index.jsx
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
Labels: cross-team, technical-work

#3902 [Emotion L4] Media Player
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/Guidance/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Guidance/index.jsx
  packages/components/psammead-media-player/src/Message/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Message/index.jsx
  packages/components/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Placeholder/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
  packages/components/psammead-media-player/src/index.stories.jsx
Labels: cross-team, technical-work

#3901 [Level 4] Migration
  packages/components/psammead-figure/CHANGELOG.md
  packages/components/psammead-figure/package-lock.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-figure/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-figure/src/index.jsx
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/Guidance/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Guidance/index.jsx
  packages/components/psammead-media-player/src/Message/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Message/index.jsx
  packages/components/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Placeholder/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
  packages/components/psammead-media-player/src/index.stories.jsx
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
  packages/components/psammead-navigation/src/ScrollableNavigation/index.jsx
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
Labels: cross-team, technical-work

#3904 [Emotion lvl 2] Migrated section-label titles.jsx & story-promo-list
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/titles.jsx
  packages/components/psammead-story-promo-list/CHANGELOG.md
  packages/components/psammead-story-promo-list/package-lock.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo-list/src/index.jsx
Labels: cross-team, technical-work

#3922 Migrate psammead-bulletin to Emotion
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/ImageStyles.jsx
  packages/components/psammead-bulletin/src/TextStyles.jsx
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/index.jsx
Labels: cross-team, technical-work

#3924 Emotion migration cleanup: styles, live-label, caption
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-live-label/CHANGELOG.md
  packages/components/psammead-live-label/package-lock.json
  packages/components/psammead-live-label/package.json
  packages/components/psammead-live-label/src/index.stories.jsx
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/index.stories.jsx
  packages/utilities/psammead-styles/src/typography.stories.jsx
Labels: cross-team, technical-work

#3921 [Level 6 and cleanup] Migrate radio schedule to emotion
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-bulletin/src/ImageStyles.jsx
  packages/components/psammead-bulletin/src/TextStyles.jsx
  packages/components/psammead-bulletin/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-bulletin/src/index.jsx
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-live-label/CHANGELOG.md
  packages/components/psammead-live-label/package-lock.json
  packages/components/psammead-live-label/package.json
  packages/components/psammead-live-label/src/index.stories.jsx
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/StartTime/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/StartTime/index.jsx
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/index.jsx
  packages/components/psammead-visually-hidden-text/CHANGELOG.md
  packages/components/psammead-visually-hidden-text/package-lock.json
  packages/components/psammead-visually-hidden-text/package.json
  packages/components/psammead-visually-hidden-text/src/index.jsx
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs/coreIcons.jsx
  packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
  packages/utilities/psammead-assets/src/svgs/navigationIcons.jsx
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/index.stories.jsx
  packages/utilities/psammead-locales/numerals/index.stories.jsx
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/index.stories.jsx
  packages/utilities/psammead-styles/src/typography.stories.jsx
Labels: cross-team, technical-work

#3929 Resolve media indicator versioning
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
Labels: cross-team, technical-work

#3927 Emotion 'styled-components' mentions cleanup
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Placeholder/index.jsx
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
  packages/components/psammead-script-link/CHANGELOG.md
  packages/components/psammead-script-link/package-lock.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-script-link/src/index.jsx
  packages/components/psammead-useful-links/CHANGELOG.md
  packages/components/psammead-useful-links/package-lock.json
  packages/components/psammead-useful-links/package.json
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
Labels: cross-team, technical-work

#3926 To Emotion and beyond
  .storybook/webpack.config.js
  .stylelintrc
  CHANGELOG.md
  README.md
  babel.config.js
  lib/stylelint/processorRemoveMixins.js
  lib/stylelint/processorRemoveMixins.test.js
  package-lock.json
  package.json
  stylelint.config.js
Labels: cross-team, technical-work

#3941 Chromatic tests not running on Psammead
  CHANGELOG.md
  Makefile
  package-lock.json
  package.json
Labels: cross-team

#3960 Ensure we monitor all events for getCLS and getLCP
  packages/utilities/web-vitals/CHANGELOG.md
  packages/utilities/web-vitals/package-lock.json
  packages/utilities/web-vitals/package.json
  packages/utilities/web-vitals/src/index.js
Labels: performance

#3837 Recent Episodes - Psammead Episode List
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/README.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/Description.jsx
  packages/components/psammead-episode-list/src/Episode.jsx
  packages/components/psammead-episode-list/src/Link.jsx
  packages/components/psammead-episode-list/src/MediaIndicator.jsx
  packages/components/psammead-episode-list/src/Metadata.jsx
  packages/components/psammead-episode-list/src/Title.jsx
  packages/components/psammead-episode-list/src/fixtures.jsx
  packages/components/psammead-episode-list/src/index.jsx
  packages/components/psammead-episode-list/src/index.stories.jsx
  packages/components/psammead-episode-list/src/index.test.jsx
Labels: ws-media

#3961 Update readme to include an example of createGlobalStyles in Simorgh
  CHANGELOG.md
  package-lock.json
  package.json
  packages/README.md
Labels: cross-team

#3962 Recent Episodes play icon padding
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/Episode.jsx
  packages/components/psammead-episode-list/src/MediaIndicator.jsx
  packages/components/psammead-episode-list/src/index.jsx
  packages/components/psammead-episode-list/src/index.stories.jsx
Labels: ws-media
