Repository bbc/psammead, pull requests merged in 2020-12, with the labels that each got.

#4071 Update BBC Reith Qalam base URL
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/fonts.test.js.snap
  packages/utilities/psammead-styles/src/fonts.js
Labels: high priority, ws-engage

#4073 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulleted-list, @bbc/psammead-bulletin...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-podcast-promo/CHANGELOG.md
  packages/components/psammead-podcast-promo/package-lock.json
  packages/components/psammead-podcast-promo/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: ws-engage

#4074 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulletin, @bbc/psammead-content-anchor...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: ws-engage

#4077 Talos - Bump @bbc/psammead-radio-schedule
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-engage

#4075 Update RadioSchedules to be able to use client side routing
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/README.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/ProgramCard/index.test.jsx
  packages/components/psammead-radio-schedule/src/index.jsx
  packages/components/psammead-radio-schedule/src/index.test.jsx
  packages/components/psammead-radio-schedule/src/testHelpers/helper.jsx
Labels: ws-media

#4085 Talos - Bump @bbc/psammead-episode-list
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-media

#4087 I'm a Talos - Bump @bbc/psammead, @bbc/gel-foundations, @bbc/moment-timezone-include...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-embed-error/CHANGELOG.md
  packages/components/psammead-embed-error/package-lock.json
  packages/components/psammead-embed-error/package.json
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package-lock.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package-lock.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-play-button/CHANGELOG.md
  packages/components/psammead-play-button/package-lock.json
  packages/components/psammead-play-button/package.json
  packages/components/psammead-podcast-promo/CHANGELOG.md
  packages/components/psammead-podcast-promo/package-lock.json
  packages/components/psammead-podcast-promo/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: ws-engage

#4088 Talos - Bump @bbc/psammead-bulletin, @bbc/psammead-embed-error, @bbc/psammead-episode-list...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-podcast-promo/CHANGELOG.md
  packages/components/psammead-podcast-promo/package-lock.json
  packages/components/psammead-podcast-promo/package.json
Labels: ws-engage

#4089 Talos - Bump @bbc/psammead-episode-list, @bbc/psammead-media-player, @bbc/psammead-podcast-promo
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-engage

#4091 Set correct propTypes for radio schedules link component
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/README.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/index.jsx
Labels: ws-media

#4109 enable style overrides in timestamp
  packages/components/psammead-timestamp/CHANGELOG.md
  packages/components/psammead-timestamp/package-lock.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-timestamp/src/index.jsx
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/index.jsx
Labels: cross-team

#4110 Remove wrapping div from Brand's skip-link
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.jsx
Labels: bug, cross-team, ws-engage

#4112 Bump package version for psammead-timestamp-container
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: cross-team

#4050 Episode list a11y bug fixes
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/Description.jsx
  packages/components/psammead-episode-list/src/Episode.jsx
  packages/components/psammead-episode-list/src/Image.jsx
  packages/components/psammead-episode-list/src/Link.jsx
  packages/components/psammead-episode-list/src/MediaIndicator.jsx
  packages/components/psammead-episode-list/src/Metadata.jsx
  packages/components/psammead-episode-list/src/Title.jsx
  packages/components/psammead-episode-list/src/fixtures.jsx
  packages/components/psammead-episode-list/src/index.test.jsx
Labels: a11y, ws-media

#4116 filter out undefined children
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/Episode.jsx
  packages/components/psammead-episode-list/src/fixtures.jsx
Labels: ws-media

#4118 Episode list a11y bug fixes
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/MediaIndicator.jsx
Labels: ws-media

#4120 Episode list a11y bug fixes
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/MediaIndicator.jsx
Labels: ws-media

#4126 Recent Episodes - Improve Text Resize Handling (P1 A11y)
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/Episode.jsx
  packages/components/psammead-episode-list/src/Image.jsx
  packages/components/psammead-episode-list/src/index.jsx
Labels: ws-media

#4125 Use CSS border for episode duration separator
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/README.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/fixtures.jsx
  packages/components/psammead-episode-list/src/index.jsx
  packages/components/psammead-episode-list/src/index.test.jsx
Labels: ws-media

#4153 Security patch update
  CHANGELOG.md
  package-lock.json
  package.json
Labels: security

#4152 Recent tv episodes link & dateTime storybook fixture updates
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/fixtures.jsx
Labels: Recent Episodes TV, a11y, ws-media

#4156 Captions update
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
  packages/components/psammead-caption/src/index.stories.jsx
Labels: Weekly goal, ws-engage
