Repository bbc/psammead, pull requests merged in 2020-11, with the labels that each got.

#3986 Adds div for skip link in Brand component
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.jsx
Labels: a11y, ws-engage

#3979 [Alpha] Update Episode List to support Videos and Dark Mode
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/README.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/Description.jsx
  packages/components/psammead-episode-list/src/Episode.jsx
  packages/components/psammead-episode-list/src/Image.jsx
  packages/components/psammead-episode-list/src/Link.jsx
  packages/components/psammead-episode-list/src/MediaIndicator.jsx
  packages/components/psammead-episode-list/src/Metadata.jsx
  packages/components/psammead-episode-list/src/Title.jsx
  packages/components/psammead-episode-list/src/fixtures.jsx
  packages/components/psammead-episode-list/src/helpers.jsx
  packages/components/psammead-episode-list/src/index.jsx
  packages/components/psammead-episode-list/src/index.stories.jsx
  packages/components/psammead-episode-list/src/index.test.jsx
Labels: ws-media

#3992 Fix grid styles
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-grid/src/index.jsx
Labels: bug

#3990 fix firefox not allowing fullscreen
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Canonical/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Canonical/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
Labels: ws-media

#3991 Radio Schedule Padding
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/index.jsx
Labels: ux, ws-media

#4006 Update RTL wording in buildRTLSubstories helper
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/buildRTLSubstories.js
  packages/utilities/psammead-storybook-helpers/src/buildRTLSubstories.test.js
Labels: cross-team

#4009 Add podcast icons to psammead-assets
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/svgs/mediaIcons.jsx
Labels: ws-media

#4002 Replace instances of BBC Nassim with BBC Reith Qalam
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/font-families.test.js.snap
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/__snapshots__/fonts.test.js.snap
  packages/utilities/psammead-styles/src/font-families.js
  packages/utilities/psammead-styles/src/fonts.js
Labels: ws-engage

#4028 Talos - Bump @bbc/psammead-bulletin, @bbc/psammead-embed-error, @bbc/psammead-episode-list...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
Labels: ws-engage

#4030 [1] Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulleted-list, @bbc/psammead-bulletin...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/containers/psammead-timestamp-container/src/__snapshots__/index.test.jsx.snap
Labels: ws-engage

#4031 [2] Talos - Bump @bbc/psammead-media-player
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-engage

#4032 [3] Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulletin, @bbc/psammead-content-anchor...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/StartTime/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
Labels: ws-engage

#4040 Social Embeds - Add support for lazy loading
  packages/components/psammead-social-embed/CHANGELOG.md
  packages/components/psammead-social-embed/README.md
  packages/components/psammead-social-embed/package-lock.json
  packages/components/psammead-social-embed/package.json
  packages/components/psammead-social-embed/src/Canonical/index.jsx
  packages/components/psammead-social-embed/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-social-embed/src/index.test.jsx
Labels: ws-engage

#4043 [1] Talos - Bump @bbc/psammead-bulletin, @bbc/psammead-radio-schedule
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-engage

#4008 Use BBC Reith Qalam font sizes and line-heights
  packages/utilities/gel-foundations/CHANGELOG.md
  packages/utilities/gel-foundations/README.md
  packages/utilities/gel-foundations/index.test.jsx
  packages/utilities/gel-foundations/package-lock.json
  packages/utilities/gel-foundations/package.json
  packages/utilities/gel-foundations/src/scripts.js
  packages/utilities/gel-foundations/src/scripts/arabic-pashto.js
  packages/utilities/gel-foundations/src/scripts/arabic.js
  packages/utilities/gel-foundations/tests/__snapshots__/getTypeSizes.test.js.snap
  packages/utilities/gel-foundations/tests/getTypeSizes.test.js
Labels: ws-engage

#4053 [2] Talos - let's go
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: high priority, ws-engage

#4054 [3] Talos - is ok
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: high priority, ws-engage

#4055 Talos - Bump @bbc/psammead-radio-schedule
  CHANGELOG.md
  package-lock.json
  package.json
Labels: high priority, ws-engage

#4056 Use correct BBC Reith Qalam fontPathMap prefix for Storybook
  .storybook/preview.js
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-engage

#3946 Remove all SVG chromatic tests & replace with snapshot tests instead
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/__snapshots__/svgs.test.jsx.snap
  packages/utilities/psammead-assets/src/svgs.stories.jsx
  packages/utilities/psammead-assets/src/svgs.test.jsx
Labels: cross-team
