Repository bbc/psammead, pull requests merged in 2020-06, with the labels that each got.

#3507 Talos - Bump @bbc/gel-foundations, @bbc/moment-timezone-include, @bbc/psammead-amp-geo...
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3508 Dev Dependency Updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3510 Add support for span tags to the rich-text-transforms package
  packages/utilities/psammead-rich-text-transforms/CHANGELOG.md
  packages/utilities/psammead-rich-text-transforms/package-lock.json
  packages/utilities/psammead-rich-text-transforms/package.json
  packages/utilities/psammead-rich-text-transforms/src/candy-xml.js
  packages/utilities/psammead-rich-text-transforms/test/candy-xml.test.js
Labels: ws-stories

#3512 Update Byline text colour
  packages/components/psammead-byline/CHANGELOG.md
  packages/components/psammead-byline/package-lock.json
  packages/components/psammead-byline/package.json
  packages/components/psammead-byline/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-byline/src/index.jsx
Labels: ux, ws-stories

#3513 Update fallback text colour in Social Embed
  packages/components/psammead-social-embed/CHANGELOG.md
  packages/components/psammead-social-embed/package-lock.json
  packages/components/psammead-social-embed/package.json
  packages/components/psammead-social-embed/src/Notice/index.jsx
  packages/components/psammead-social-embed/src/__snapshots__/index.test.jsx.snap
Labels: ux, ws-stories

#3523 Dependency updates
  CHANGELOG.md
  package-lock.json
  package.json
  packages/utilities/psammead-locales/CHANGELOG.md
  packages/utilities/psammead-locales/moment/.eslintrc.js
  packages/utilities/psammead-locales/package-lock.json
  packages/utilities/psammead-locales/package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3524 Talos - Bump @bbc/psammead-locales
  CHANGELOG.md
  package-lock.json
  package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-calendars/CHANGELOG.md
  packages/utilities/psammead-calendars/package-lock.json
  packages/utilities/psammead-calendars/package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3525 Talos - Bump @bbc/psammead-timestamp-container, @bbc/psammead-calendars
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3526 Talos - Bump @bbc/psammead-radio-schedule
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-home, ws-media-stream, ws-stories

#3527 Remove alpha tag from Index Heading component
  packages/components/psammead-heading-index/CHANGELOG.md
  packages/components/psammead-heading-index/README.md
  packages/components/psammead-heading-index/package-lock.json
  packages/components/psammead-heading-index/package.json
Labels: ws-home

#3514 Update Section Label to use correct colour in secondary column
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/package-lock.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/index.jsx
  packages/components/psammead-section-label/src/titles.jsx
Labels: ux, ws-stories

#3530 Remove Index Alsos from Grid stories
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/index.stories.jsx
Labels: ws-home

#3529 Create Security.md
  CHANGELOG.md
  SECURITY.md
  package-lock.json
  package.json
Labels: documentation, security

#3539 Add geolocation group for locations that should not be shown ads
  packages/components/psammead-amp-geo/CHANGELOG.md
  packages/components/psammead-amp-geo/README.md
  packages/components/psammead-amp-geo/package-lock.json
  packages/components/psammead-amp-geo/package.json
  packages/components/psammead-amp-geo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-amp-geo/src/index.jsx
Labels: ads, ws-home

#3541 Top Stories headline promo spacing
  packages/components/psammead-story-promo/CHANGELOG.md
  packages/components/psammead-story-promo/package-lock.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-story-promo/src/TextStyles.jsx
Labels: ux, ws-stories

#3543 Talos - Bump @bbc/gel-foundations, @bbc/moment-timezone-include, @bbc/psammead-amp-geo...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
Labels: ws-home, ws-media-stream, ws-stories

#3557 Talos - Bump @bbc/gel-foundations, @bbc/moment-timezone-include, @bbc/psammead-amp-geo...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3558 Talos - Bump @bbc/psammead-bulletin
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3554 Dev Dependency Updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependencies, ws-home, ws-media-stream, ws-stories

#3559 Update radio time indicator styling
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
Labels: ws-media-stream
