Repository bbc/psammead, pull requests merged in 2021-09, with the labels that each got.

#4546 Moves psammead-image-placeholder padding ratio to inline style
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image-placeholder/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-image-placeholder/src/index.jsx
  packages/components/psammead-image-placeholder/src/index.stories.jsx
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-podcast-promo/CHANGELOG.md
  packages/components/psammead-podcast-promo/package.json
  packages/components/psammead-podcast-promo/src/__snapshots__/index.test.jsx.snap
  yarn.lock
Labels: cross-team

#4550 Adds on pull_request event to change scanner to support forking
  .github/workflows/psammead-change-scanner.yml
Labels: technical-work, cross-team

#4549 Add forward style prop img placeholder
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/README.md
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image-placeholder/src/index.jsx
  packages/components/psammead-image-placeholder/src/index.stories.jsx
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package.json
  packages/components/psammead-podcast-promo/CHANGELOG.md
  packages/components/psammead-podcast-promo/package.json
  yarn.lock
Labels: cross-team

#4558 remove aria-labelledby attribute
  packages/components/psammead-section-label/CHANGELOG.md
  packages/components/psammead-section-label/README.md
  packages/components/psammead-section-label/package.json
  packages/components/psammead-section-label/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-section-label/src/titles.jsx
Labels: a11y, cross-team
