Repository bbc/psammead, pull requests merged in 2021-04, with the labels that each got.

#4445 remove vuln packages via force resolutions
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cross-team, technical-work, ws-articles, ws-media

#4450 fix publish script
  CHANGELOG.md
  package.json
  scripts/publish/index.js
  scripts/publish/test/index.test.js
Labels: cross-team

#4451 Fix changescanner
  CHANGELOG.md
  package.json
  scripts/changeScanner/index.js
  scripts/changeScanner/index.test.js
Labels: cross-team

#4454 fix - different output in ci for shelljs
  scripts/publish/test/index.test.js
  scripts/utilities/getPackages/index.js
  scripts/utilities/getPackages/index.test.js
Labels: cross-team

#4452 Add linkId prop to psammead-brand
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.stories.jsx
  packages/components/psammead-brand/src/index.test.jsx
Labels: a11y, ws-articles

#4455 remove root package from getPackages
  scripts/bumpPackages/getVersionBumpCommitMessage.js
  scripts/bumpPackages/index.js
  scripts/bumpPackages/index.test.js
  scripts/publish/index.js
  scripts/utilities/getPackageNames/index.js
  scripts/utilities/getPackageNames/index.test.js
  scripts/utilities/getPackagePath/index.js
  scripts/utilities/getPackagePath/index.test.js
  scripts/utilities/getPackages/index.js
  scripts/utilities/getPackages/index.test.js
  scripts/utilities/initialPrompt/index.js
  yarn.lock
Labels: cross-team

#4449 Remove psammead-amp-geo
  package.json
  packages/README.md
  packages/components/psammead-amp-geo/CHANGELOG.md
  packages/components/psammead-amp-geo/README.md
  packages/components/psammead-amp-geo/package.json
  packages/components/psammead-amp-geo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-amp-geo/src/index.jsx
  packages/components/psammead-amp-geo/src/index.test.jsx
Labels: ws-articles

#4464 Delete yeoman
  .yarnrc
  .yeoman/README.md
  .yeoman/index.js
  .yeoman/src/fs-actions/index.js
  .yeoman/src/fs-actions/index.test.js
  .yeoman/src/get-existing/index.js
  .yeoman/src/get-existing/index.test.js
  .yeoman/src/get-package-types/index.js
  .yeoman/src/get-package-types/index.test.js
  .yeoman/src/questions/index.js
  .yeoman/src/questions/index.test.js
  .yeoman/templates/components/CHANGELOG.md
  .yeoman/templates/components/README.md
  .yeoman/templates/components/package.json
  .yeoman/templates/components/src/index.jsx
  .yeoman/templates/components/src/index.stories.jsx
  .yeoman/templates/components/src/index.test.jsx
  .yeoman/templates/containers/CHANGELOG.md
  .yeoman/templates/containers/README.md
  .yeoman/templates/containers/package.json
  .yeoman/templates/containers/src/index.jsx
  .yeoman/templates/containers/src/index.stories.jsx
  .yeoman/templates/containers/src/index.test.jsx
  .yeoman/templates/utilities/CHANGELOG.md
  .yeoman/templates/utilities/README.md
  .yeoman/templates/utilities/package.json
  .yeoman/templates/utilities/src/index.js
  .yeoman/templates/utilities/src/index.test.js
  package.json
  yarn.lock
Labels: security, tech-debt, technical-work

#4457 Remove psammead-episode-list and psammead-sitewide-links from psammead
  package.json
  packages/README.md
  packages/components/psammead-copyright/CHANGELOG.md
  packages/components/psammead-copyright/README.md
  packages/components/psammead-copyright/package.json
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/README.md
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/DateTimeDuration.jsx
  packages/components/psammead-episode-list/src/Description.jsx
  packages/components/psammead-episode-list/src/Episode.jsx
  packages/components/psammead-episode-list/src/Image.jsx
  packages/components/psammead-episode-list/src/Link.jsx
  packages/components/psammead-episode-list/src/MediaIndicator.jsx
  packages/components/psammead-episode-list/src/Title.jsx
  packages/components/psammead-episode-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-episode-list/src/fixtures.jsx
  packages/components/psammead-episode-list/src/helpers.jsx
  packages/components/psammead-episode-list/src/index.jsx
  packages/components/psammead-episode-list/src/index.stories.jsx
  packages/components/psammead-episode-list/src/index.test.jsx
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/README.md
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-sitewide-links/src/Link/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/Link/index.jsx
  packages/components/psammead-sitewide-links/src/Link/index.test.jsx
  packages/components/psammead-sitewide-links/src/List/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/List/index.jsx
  packages/components/psammead-sitewide-links/src/List/index.test.jsx
  packages/components/psammead-sitewide-links/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-sitewide-links/src/index.jsx
  packages/components/psammead-sitewide-links/src/index.stories.jsx
  packages/components/psammead-sitewide-links/src/index.test.jsx
Labels: cross-team, technical-work
