Repository bbc/psammead, pull requests merged in 2021-01, with the labels that each got.

#4167 Fix captions margin
  packages/components/psammead-caption/CHANGELOG.md
  packages/components/psammead-caption/package-lock.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-caption/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-caption/src/index.jsx
Labels: ws-engage

#4154 [amp-validation] Expand omit list for episode-list-image
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/Image.jsx
Labels: ws-media

#4172 Add new workflows for ci & cd process
  .github/workflows/cancel-previous-runs.yml
  .github/workflows/psammead-change-scanner.yml
  .github/workflows/psammead-chromaticqa.yml
  .github/workflows/psammead-deploy-storybook.yml
  .github/workflows/psammead-publish.yml
  .github/workflows/psammead-unit-tests.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team

#4124 Range of podcast promo a11y fixes
  packages/components/psammead-podcast-promo/CHANGELOG.md
  packages/components/psammead-podcast-promo/README.md
  packages/components/psammead-podcast-promo/package-lock.json
  packages/components/psammead-podcast-promo/package.json
  packages/components/psammead-podcast-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-podcast-promo/src/components/card-call-to-action.jsx
  packages/components/psammead-podcast-promo/src/components/card-content.jsx
  packages/components/psammead-podcast-promo/src/components/card-episodes-text.jsx
  packages/components/psammead-podcast-promo/src/components/card-image-wrapper.jsx
  packages/components/psammead-podcast-promo/src/components/card-link.jsx
  packages/components/psammead-podcast-promo/src/components/card.jsx
  packages/components/psammead-podcast-promo/src/components/title.jsx
  packages/components/psammead-podcast-promo/src/examples/basic.jsx
  packages/components/psammead-podcast-promo/src/icons/podcast.jsx
  packages/components/psammead-podcast-promo/src/icons/series-stack.jsx
  packages/components/psammead-podcast-promo/src/index.jsx
  packages/components/psammead-podcast-promo/src/index.test.jsx
Labels: a11y, podcasts, ws-media

#4178 Bumped psammead-caption dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-articles

#4168 Support dynamic fixture data for podcast promo to help a11y swarm
  packages/components/psammead-podcast-promo/CHANGELOG.md
  packages/components/psammead-podcast-promo/package-lock.json
  packages/components/psammead-podcast-promo/package.json
  packages/components/psammead-podcast-promo/src/examples/basic.jsx
  packages/components/psammead-podcast-promo/src/examples/fixtureData.js
  packages/components/psammead-podcast-promo/src/index.stories.jsx
Labels: podcasts, ws-media

#4180 Bye bye Jenkins
  .github/CODEOWNERS
  CHANGELOG.md
  Code-Standards-and-Ways-of-Working.md
  Jenkinsfile
  Makefile
  package-lock.json
  package.json
  scripts/talos/README.md
Labels: cross-team, technical-work

#4150 Remove hanging separator span
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/README.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/Metadata.jsx
  packages/components/psammead-episode-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-episode-list/src/fixtures.jsx
  packages/components/psammead-episode-list/src/index.jsx
  packages/components/psammead-episode-list/src/index.test.jsx
Labels: ws-media

#4183 Setup github users before pushing talos PR
  .github/workflows/psammead-publish.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team

#4179 Move duplicated styles from media queries to grid/grid-item root style
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package-lock.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-grid/src/index.jsx
Labels: cross-team, ws-articles

#4160 Add SVGs and colours for Sport and Newsround
  packages/utilities/psammead-assets/CHANGELOG.md
  packages/utilities/psammead-assets/index.test.jsx
  packages/utilities/psammead-assets/package-lock.json
  packages/utilities/psammead-assets/package.json
  packages/utilities/psammead-assets/src/__snapshots__/svgs.test.jsx.snap
  packages/utilities/psammead-assets/src/svgs.jsx
  packages/utilities/psammead-assets/src/svgs/newsround.jsx
  packages/utilities/psammead-assets/src/svgs/sport.jsx
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/colours.test.js.snap
  packages/utilities/psammead-styles/src/__snapshots__/font-families.test.js.snap
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/colours.js
  packages/utilities/psammead-styles/src/font-families.js
Labels: ws-articles

#4191 remove all use of deprecated waitForDomChange
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.test.jsx
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/renderWithHelmet.js
Labels: cross-team, technical-work

#4197 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulleted-list, @bbc/psammead-bulletin...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-podcast-promo/CHANGELOG.md
  packages/components/psammead-podcast-promo/package-lock.json
  packages/components/psammead-podcast-promo/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: ws-articles

#4190 Add brand colours to text variants
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
Labels: ws-articles

#4199 Talos - Bump @bbc/psammead-storybook-helpers
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-articles

#4198 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulletin, @bbc/psammead-content-anchor...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: ws-articles

#4203 Export colours from knobs, add a colour, and fix my spelling
  packages/utilities/psammead-storybook-helpers/CHANGELOG.md
  packages/utilities/psammead-storybook-helpers/package-lock.json
  packages/utilities/psammead-storybook-helpers/package.json
  packages/utilities/psammead-storybook-helpers/src/text-variants.js
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.jsx
  packages/utilities/psammead-storybook-helpers/src/withServicesKnob.test.jsx
Labels: ws-articles

#4211 Talos - Bump @bbc/psammead-storybook-helpers
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-articles

#4201 remove async snapshot functionality
  packages/utilities/psammead-test-helpers/CHANGELOG.md
  packages/utilities/psammead-test-helpers/__snapshots__/index.test.jsx.snap
  packages/utilities/psammead-test-helpers/index.test.jsx
  packages/utilities/psammead-test-helpers/package-lock.json
  packages/utilities/psammead-test-helpers/package.json
  packages/utilities/psammead-test-helpers/src/index.js
  packages/utilities/psammead-test-helpers/src/renderWithHelmet.js
Labels: cross-team, technical-work

#4187 Update psammead-navigation to require colours as props
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/README.md
  packages/components/psammead-navigation/package-lock.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/ScrollableNavigation/index.jsx
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/index.jsx
  packages/components/psammead-navigation/src/index.stories.jsx
  packages/components/psammead-navigation/src/index.test.jsx
Labels: ws-articles

#4224 Talos - Bump @bbc/psammead-navigation
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-articles

#4223 Update pinned dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team

#4221 [PS AMP] Add colours needed for Navigations
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/colours.test.js.snap
  packages/utilities/psammead-styles/src/colours.js
Labels: ws-articles

#4227 Talos - Bump @bbc/psammead-brand, @bbc/psammead-bulleted-list, @bbc/psammead-bulletin...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-content-anchor/CHANGELOG.md
  packages/components/psammead-content-anchor/package-lock.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package-lock.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-podcast-promo/CHANGELOG.md
  packages/components/psammead-podcast-promo/package-lock.json
  packages/components/psammead-podcast-promo/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
  packages/containers/psammead-timestamp-container/CHANGELOG.md
  packages/containers/psammead-timestamp-container/package-lock.json
  packages/containers/psammead-timestamp-container/package.json
Labels: ws-articles

#4229 Talos - Bump @bbc/psammead-radio-schedule
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ws-articles

#4246 Add new action to manually run Talos
  .github/workflows/psammead-manual-talos.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team, technical-work

#4249 Remove ARGS declaration from manual Talos PR workflow
  .github/workflows/psammead-manual-talos.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team, technical-work

#4250 Revert #4249 changes to psammead-manual-talos workflow name
  .github/workflows/psammead-manual-talos.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cross-team, technical-work

#4231 Upgrade psammead-styles to emotion 11
  CHANGELOG.md
  package-lock.json
  package.json
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/global-styles.test.jsx.snap
  packages/utilities/psammead-styles/src/global-styles.jsx
Labels: emotion, technical-work

#4253 Fix constant name from newsbeat to newsround in fonts
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/font-families.test.js.snap
  packages/utilities/psammead-styles/src/__snapshots__/font-styles.test.js.snap
  packages/utilities/psammead-styles/src/font-families.js
Labels: ws-articles

#4245 Add consent focus colour
  packages/utilities/psammead-styles/CHANGELOG.md
  packages/utilities/psammead-styles/index.test.jsx
  packages/utilities/psammead-styles/package-lock.json
  packages/utilities/psammead-styles/package.json
  packages/utilities/psammead-styles/src/__snapshots__/colours.test.js.snap
  packages/utilities/psammead-styles/src/colours.js
Labels: ws-articles

#4273 Talos - Bump @bbc/psammead-amp-geo, @bbc/psammead-brand, @bbc/psammead-brand/skip-link...
  CHANGELOG.md
  package-lock.json
  package.json
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package-lock.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulletin/CHANGELOG.md
  packages/components/psammead-bulletin/package-lock.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package-lock.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-podcast-promo/CHANGELOG.md
  packages/components/psammead-podcast-promo/package-lock.json
  packages/components/psammead-podcast-promo/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package-lock.json
  packages/components/psammead-radio-schedule/package.json
Labels: cross-team, technical-work

#4225 Update consent banner
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-consent-banner/src/index.jsx
  packages/components/psammead-consent-banner/src/index.stories.jsx
Labels: ux, ws-articles

#4270 Update radio EpisodeList fixture to use time element when relevant
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-episode-list/src/fixtures.jsx
Labels: a11y, ws-media

#4289 fix IE11 bug
  packages/components/psammead-podcast-promo/CHANGELOG.md
  packages/components/psammead-podcast-promo/package-lock.json
  packages/components/psammead-podcast-promo/package.json
  packages/components/psammead-podcast-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-podcast-promo/src/components/card-image-wrapper.jsx
  packages/components/psammead-podcast-promo/src/components/card.jsx
Labels: ws-media

#4292 add flex-basis (min-width) for image when viewport < 400px
  packages/components/psammead-podcast-promo/CHANGELOG.md
  packages/components/psammead-podcast-promo/package-lock.json
  packages/components/psammead-podcast-promo/package.json
  packages/components/psammead-podcast-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-podcast-promo/src/components/card-image-wrapper.jsx
Labels: ws-media

#4293 Canonical ConsentBanner UX and a11y amendments
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-consent-banner/src/index.jsx
Labels: ux, ws-articles
