Repository bbc/psammead, pull requests merged in 2021-02, with the labels that each got.

#4299 Canonical ConsentBanner a11y changes
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-consent-banner/src/index.jsx
Labels: a11y-swarm, ux, ws-articles

#4301 Wrapper padding bottom reduced to 8px
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package-lock.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-consent-banner/src/index.jsx
Labels: ux, ws-articles

#4294 Rename recent episodes metadata & fix storybook fixture style
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/README.md
  packages/components/psammead-episode-list/package-lock.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-episode-list/src/DateTimeDuration.jsx
  packages/components/psammead-episode-list/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-episode-list/src/fixtures.jsx
  packages/components/psammead-episode-list/src/index.jsx
  packages/components/psammead-episode-list/src/index.test.jsx
Labels: ws-media

#4339 Storybook preview
  .github/workflows/psammead-change-scanner.yml
  .github/workflows/psammead-storybook-preview.yml
Labels: cross-team

#4352 fix deploys - use node script publish not yarn publish
  .github/workflows/psammead-publish.yml
  CHANGELOG.md
  package.json
  scripts/changeScanner/getChanges.js
  scripts/changeScanner/getChanges.test.js
  scripts/changeScanner/index.js
  scripts/changeScanner/index.test.js
Labels: cross-team

#4371 Only run chromatic/change scanner when the packages directory has changed
  .github/workflows/psammead-change-scanner.yml
  .github/workflows/psammead-chromaticqa.yml
Labels: cross-team

#4334 Image placeholder amp support
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/README.md
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image-placeholder/src/__snapshots__/index.amp.test.jsx.snap
  packages/components/psammead-image-placeholder/src/index.amp.jsx
  packages/components/psammead-image-placeholder/src/index.amp.stories.jsx
  packages/components/psammead-image-placeholder/src/index.amp.test.jsx
  packages/components/psammead-image-placeholder/src/index.jsx
Labels: bug, cross-team

#4248 Topic tags to storybook
  packages/components/psammead-topic-tags/CHANGELOG.md
  packages/components/psammead-topic-tags/README.md
  packages/components/psammead-topic-tags/package.json
  packages/components/psammead-topic-tags/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-topic-tags/src/index.jsx
  packages/components/psammead-topic-tags/src/index.stories.jsx
  packages/components/psammead-topic-tags/src/index.test.jsx
  packages/components/psammead-topic-tags/yarn.lock
Labels: cross-team, ux

#4370 fix changeScanner for new packages
  CHANGELOG.md
  package.json
  scripts/changeScanner/index.js
Labels: bug, cross-team

#4380 Make consent banner and brand components externally focusable
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.test.jsx
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/README.md
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-consent-banner/src/index.jsx
  packages/components/psammead-consent-banner/src/index.test.jsx
Labels: ws-articles

#4382 Change focusRef prop-type to any for consent banner and brand
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/index.jsx
Labels: ws-articles
