Repository bbc/psammead, pull requests merged in 2021-03, with the labels that each got.

#4402 remove dependabot config
  .github/dependabot.yml
  CHANGELOG.md
  package.json
Labels: cross-team

#4376 Adding Listen screenreader label for Radio Schedule
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-radio-schedule/src/index.jsx
  packages/components/psammead-radio-schedule/src/testHelpers/helper.jsx
Labels: a11y, ws-media

#4426 psammead-brand forwardRefs to SvgWrapper
  packages/components/psammead-brand/CHANGELOG.md
  packages/components/psammead-brand/README.md
  packages/components/psammead-brand/package.json
  packages/components/psammead-brand/src/index.jsx
  packages/components/psammead-brand/src/index.test.jsx
  packages/components/psammead-consent-banner/CHANGELOG.md
  packages/components/psammead-consent-banner/README.md
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-consent-banner/src/index.jsx
  packages/components/psammead-consent-banner/src/index.test.jsx
Labels: a11y, ws-articles

#4433 pin bbc/psammead interdependencies
  package.json
  packages/components/psammead-brand/package.json
  packages/components/psammead-bulleted-list/package.json
  packages/components/psammead-bulletin/package.json
  packages/components/psammead-byline/package.json
  packages/components/psammead-caption/package.json
  packages/components/psammead-consent-banner/package.json
  packages/components/psammead-content-anchor/package.json
  packages/components/psammead-copyright/package.json
  packages/components/psammead-embed-error/package.json
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-figure/package.json
  packages/components/psammead-grid/package.json
  packages/components/psammead-heading-index/package.json
  packages/components/psammead-headings/package.json
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-inline-link/package.json
  packages/components/psammead-live-label/package.json
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-player/package.json
  packages/components/psammead-most-read/package.json
  packages/components/psammead-navigation/package.json
  packages/components/psammead-paragraph/package.json
  packages/components/psammead-play-button/package.json
  packages/components/psammead-podcast-promo/package.json
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-script-link/package.json
  packages/components/psammead-section-label/package.json
  packages/components/psammead-sitewide-links/package.json
  packages/components/psammead-social-embed/package.json
  packages/components/psammead-story-promo-list/package.json
  packages/components/psammead-story-promo/package.json
  packages/components/psammead-timestamp/package.json
  packages/components/psammead-topic-tags/package.json
  packages/components/psammead-useful-links/package.json
  packages/containers/psammead-timestamp-container/package.json
  packages/utilities/psammead-storybook-helpers/package.json
Labels: cross-team

#4436 add data-e2e attributes for e2e tests
  package.json
  packages/components/psammead-episode-list/CHANGELOG.md
  packages/components/psammead-episode-list/package.json
  packages/components/psammead-image-placeholder/CHANGELOG.md
  packages/components/psammead-image-placeholder/package.json
  packages/components/psammead-image-placeholder/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-image-placeholder/src/index.jsx
  packages/components/psammead-media-indicator/CHANGELOG.md
  packages/components/psammead-media-indicator/package.json
  packages/components/psammead-media-indicator/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-indicator/src/index.jsx
  packages/components/psammead-media-player/CHANGELOG.md
  packages/components/psammead-media-player/package.json
  packages/components/psammead-media-player/src/Amp/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Amp/index.jsx
  packages/components/psammead-media-player/src/Guidance/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Guidance/index.jsx
  packages/components/psammead-media-player/src/Placeholder/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/Placeholder/index.jsx
  packages/components/psammead-media-player/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-media-player/src/index.jsx
  packages/components/psammead-navigation/src/ScrollableNavigation/index.jsx
  packages/components/psammead-navigation/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-podcast-promo/CHANGELOG.md
  packages/components/psammead-podcast-promo/package.json
  packages/components/psammead-podcast-promo/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/IndexAlsos/__snapshots__/index.test.jsx.snap
  packages/components/psammead-story-promo/src/__snapshots__/index.test.jsx.snap
Labels: cross-team

#4437 bump psammead-navigation
  package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package.json
Labels: cross-team

#4438 add data-e2e attributes for e2e tests
  package.json
  packages/components/psammead-navigation/CHANGELOG.md
  packages/components/psammead-navigation/package.json
  packages/components/psammead-navigation/src/DropdownNavigation/__snapshots__/index.test.jsx.snap
  packages/components/psammead-navigation/src/DropdownNavigation/index.jsx
Labels: cross-team

#4428 Revamp radio schedule
  CHANGELOG.md
  package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package.json
  packages/components/psammead-radio-schedule/src/ProgramCard/index.jsx
  packages/components/psammead-radio-schedule/src/ScheduleItemHeader/index.jsx
  packages/components/psammead-radio-schedule/src/ScheduleItemHeader/index.test.jsx
  packages/components/psammead-radio-schedule/src/index.jsx
  packages/components/psammead-radio-schedule/src/testHelpers/helper.jsx
  packages/components/psammead-radio-schedule/src/utilities/index.js
  yarn.lock
Labels: ws-media

#4419 Update topic tags component to use new designs
  packages/components/psammead-topic-tags/CHANGELOG.md
  packages/components/psammead-topic-tags/package.json
  packages/components/psammead-topic-tags/src/__snapshots__/index.test.jsx.snap
  packages/components/psammead-topic-tags/src/index.jsx
  packages/components/psammead-topic-tags/yarn.lock
Labels: a11y, cross-team, ux

#4442 remove jitterbit/get-changed-files action from change-scanner action
  .github/workflows/psammead-change-scanner.yml
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cross-team

#4441 remove Talos bumper bot
  .github/CODE_OF_CONDUCT.md
  .github/workflows/psammead-manual-talos.yml
  .github/workflows/psammead-publish.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Code-Standards-and-Ways-of-Working.md
  README.md
  package.json
  packages/README.md
  scripts/talos/README.md
  scripts/talos/checkoutBranch/index.js
  scripts/talos/checkoutBranch/index.test.js
  scripts/talos/cli.js
  scripts/talos/commitChanges/index.js
  scripts/talos/commitChanges/index.test.js
  scripts/talos/createPullRequest/getPackageNames/index.js
  scripts/talos/createPullRequest/getPackageNames/index.test.js
  scripts/talos/createPullRequest/index.js
  scripts/talos/createPullRequest/index.test.js
  scripts/talos/getBranchName/index.js
  scripts/talos/getBranchName/index.test.js
  scripts/talos/getChangedPackages/index.js
  scripts/talos/getChangedPackages/index.test.js
  scripts/talos/getChangelogHead/index.js
  scripts/talos/getChangelogHead/index.test.js
  scripts/talos/getChangelogHead/mockChangelogs.js
  scripts/talos/getPullRequestBody/index.js
  scripts/talos/getPullRequestBody/index.test.js
  scripts/talos/index.js
  scripts/talos/index.test.js
Labels: cross-team

#4439 Document versioning changelogs
  CHANGELOG.md
  CONTRIBUTING.md
  package.json
  scripts/bumpChangelogs/cli.js
  scripts/bumpPackages/cli.js
Labels: cross-team

#4440 Add deprecation notice to psammead-sitewide-links
  CHANGELOG.md
  package.json
  packages/components/psammead-sitewide-links/CHANGELOG.md
  packages/components/psammead-sitewide-links/README.md
  packages/components/psammead-sitewide-links/package.json
  yarn.lock
Labels: cross-team

#4443 Fix docs link
  .github/CODE_OF_CONDUCT.md
  CHANGELOG.md
  CONTRIBUTING.md
  Code-Standards-and-Ways-of-Working.md
  README.md
  package.json
  packages/README.md
Labels: cross-team

#4444 Remove lerna package
  CHANGELOG.md
  package.json
  scripts/runPackagesInstall/index.js
  scripts/runPackagesInstall/index.test.js
  scripts/upgradeDependencies/index.js
  scripts/upgradeDependencies/index.test.js
  scripts/upgradeDependencies/parseUpgradedPackages.js
  scripts/utilities/commitChanges/index.js
  scripts/utilities/commitChanges/index.test.js
  scripts/utilities/getPackagePath/index.js
  scripts/utilities/getPackagePath/index.test.js
  scripts/utilities/getPackages/index.js
  scripts/utilities/getPackages/index.test.js
  scripts/utilities/promptStageAndCommit/index.js
  scripts/utilities/promptStageAndCommit/index.test.js
  scripts/utilities/stageFile/index.js
  scripts/utilities/stageFile/index.test.js
  yarn.lock
Labels: cross-team
