Repository bbc/psammead, pull requests merged in 2021-05, with the labels that each got.

#4465 Document the component deprecation process
  .github/CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/Code-Standards-and-Ways-of-Working.md
  docs/Creating-a-new-component.md
  docs/Deprecating-a-Package.md
Labels: cross-team, documentation

#4474 Remove a reference to psammead-amp-geo
  scripts/utilities/getPackages/index.test.js
Labels: cross-team, technical-work

#4470 upgrade husky to v6
  .husky/.gitignore
  .husky/pre-commit
  .husky/pre-push
  package.json
  yarn.lock
Labels: cross-team

#4479 Fix security vulnerability and update storybook
  package.json
  yarn.lock
Labels: cross-team, dependencies, security

#4485 Fix normalize-url vulnerabilities
  package.json
  yarn.lock
Labels: cross-team, dependencies, technical-work

#4484 Forward ref in psammead-grid
  package.json
  packages/components/psammead-grid/CHANGELOG.md
  packages/components/psammead-grid/package.json
  packages/components/psammead-grid/src/index.jsx
  packages/components/psammead-most-read/CHANGELOG.md
  packages/components/psammead-most-read/package.json
  packages/components/psammead-radio-schedule/CHANGELOG.md
  packages/components/psammead-radio-schedule/package.json
Labels: cross-team
